name = "promptdeck"
pages_build_output_dir = "./dist-static"
compatibility_date = "2026-07-22"

[[kv_namespaces]]
binding = "PROMPTDECK_ADMIN_KV"
id = "5ec653ae566046a289843ed7a54f8ce7"
preview_id = "d60436ab1a3c42d781af3f2942c18107"
