(function (global) {
  "use strict";

  const packs = global.PromptDeckSlideStylePresetPacks || (global.PromptDeckSlideStylePresetPacks = {});

  packs.commercialVisual = [
    {
      id: "soft-rounded-business", category: "branding", nameKo: "소프트 라운드 비즈니스", nameEn: "Soft Rounded Business",
      aliases: ["라운드 비즈니스", "파스텔 업무", "친근한 회사 소개"], description: "부드러운 곡선과 낮은 채도의 색으로 전문성과 친근함을 함께 전달합니다.", bestFor: "서비스 소개 · 고객 안내 · 사내 커뮤니케이션", tags: ["라운드", "파스텔", "친근", "서비스"],
      promptKo: "둥근 모서리, 완만한 곡선, 낮은 채도의 블루·민트·코랄을 사용한다. 친근한 인상을 유지하되 제목, 수치와 절차의 위계는 업무 문서처럼 명확하게 정렬한다.", promptEn: "Use rounded corners, gentle curves, and low-saturation blue, mint, and coral. Keep a friendly tone while aligning headings, figures, and procedures with business-document clarity.",
      keywords: "친근, 부드러움, 접근성, 정돈", motif: "연결되는 라운드 패널과 작은 원형 포인트", visual: { formality: 3, energy: 3, expression: 3, rationality: 2, geometry: 3, depth: 2 }, compositionProfile: "controlled",
      composition: { formLanguage: "softGeometric", lineLanguage: "shapeLed", surfaceLanguage: "mattePanels", spatialRhythm: "flowing", hierarchyBehavior: "colorScale", container: "cards", density: "balanced", primaryVisualLanguage: "diagram", secondaryVisualLanguage: "illustration", whitespacePercent: 24 }, palette: { mode: "light", background: "#F7FAFC", primary: "#385A7C", secondary: "#79B8A4", accent: "#F08A7E", surface: "#FFFFFF" }, typographyPreset: "public", resources: { icons: "allow", illustration: "allow", diagramInfographic: "allow" },
      introducedIn: 7, facets: { useCases: ["service-introduction", "internal-comms"], audiences: ["customer", "employee"], moods: ["friendly", "soft"], media: ["diagram", "illustration"], industries: ["service", "education"] }, distinctiveRules: ["낮은 채도", "일관된 라운드 반경", "곡선형 연결"], avoidRules: ["유아용 캐릭터 톤", "젤리형 과도한 그림자"],
    },
    {
      id: "duotone-corporate-photo", category: "branding", nameKo: "듀오톤 코퍼레이트 포토", nameEn: "Duotone Corporate Photo",
      aliases: ["듀오톤", "투톤 사진", "브랜드 사진", "코퍼레이트 포토"], description: "현장 사진을 두 개의 브랜드 역할색으로 통일해 강한 기업 인상을 만듭니다.", bestFor: "기업 비전 · 브랜드 캠페인 · 컨퍼런스", tags: ["듀오톤", "사진", "브랜드", "대비"],
      promptKo: "제공된 기업·현장 사진을 짙은 네이비와 선명한 청록의 듀오톤으로 처리하고 큰 제목과 짧은 메시지를 결합한다. 사람과 제품의 형태는 보존하고 데이터 영역에는 색상 처리를 적용하지 않는다.", promptEn: "Treat supplied corporate and field photography in deep navy and vivid teal duotone, paired with a large headline and concise message. Preserve people and product forms, and keep data areas free from color treatment.",
      keywords: "브랜드, 사진, 대비, 통일", motif: "듀오톤 사진과 흰색 타이포 밴드", visual: { formality: 2, energy: 4, expression: 4, rationality: 3, geometry: 2, depth: 3 }, compositionProfile: "editorial",
      composition: { formLanguage: "mixed", lineLanguage: "boldDirectional", surfaceLanguage: "controlledLayer", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "layerPosition", container: "borderless", density: "balanced", primaryVisualLanguage: "photo", secondaryVisualLanguage: "typography", whitespacePercent: 18, layerCount: 3 }, palette: { mode: "dark", background: "#071B33", primary: "#F8FAFC", secondary: "#00A7A5", accent: "#F2C14E", surface: "#102844", textPrimary: "#FFFFFF" }, typographyPreset: "editorial", backgroundProfile: "technology", background: { intensity: "expressive", photoMode: "conditional", photoSaturation: "low", photoOverlay: "medium" }, resources: { photo: "allow", layeredComposite: "allow", typographicFocal: "allow" }, photoComposite: { mode: "preferred", visualRole: "atmosphere", layerLogic: "heroData", styleBlend: "unifiedMaterial" },
      introducedIn: 7, facets: { useCases: ["company-profile", "brand", "event"], audiences: ["public", "partner"], moods: ["bold", "credible"], media: ["photo", "typography"], industries: ["general-business"] }, distinctiveRules: ["두 역할색 사진 처리", "큰 흰색 제목", "데이터 원색 보존"], avoidRules: ["피부·제품 형태 왜곡", "모든 요소에 듀오톤 적용"],
    },
    {
      id: "cinematic-keynote", category: "branding", nameKo: "시네마틱 키노트", nameEn: "Cinematic Keynote",
      aliases: ["시네마틱", "영화형 키노트", "비전 발표", "무대 발표"], description: "한 장면과 한 문장에 집중해 대형 무대에서 강한 몰입을 만드는 키노트 스타일입니다.", bestFor: "비전 선포 · 신제품 발표 · 대형 행사", tags: ["시네마틱", "키노트", "무대", "몰입"],
      promptKo: "한 장의 실제 제공 이미지나 맥락에 맞는 사실적 장면을 넓게 사용하고 한 문장 또는 한 수치만 시각적 초점으로 둔다. 어두운 가장자리와 보호된 텍스트 영역으로 원거리 가독성을 확보한다.", promptEn: "Use one supplied image or a context-faithful realistic scene at full scale, with only one sentence or figure as the focal point. Protect presentation-distance legibility with darkened edges and a clean text-safe zone.",
      keywords: "몰입, 비전, 장면, 무대", motif: "풀블리드 장면과 단일 초대형 문장", visual: { formality: 3, energy: 5, expression: 5, rationality: 4, geometry: 3, depth: 5 }, compositionProfile: "dynamic",
      composition: { formLanguage: "mixed", lineLanguage: "minimalDivider", surfaceLanguage: "controlledLayer", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "scalePosition", container: "borderless", density: "airy", primaryVisualLanguage: "photo", secondaryVisualLanguage: "typography", whitespacePercent: 30, focalAreaPercent: 52, layerCount: 3 }, palette: { mode: "dark", background: "#090B10", primary: "#FFFFFF", secondary: "#9AA7B8", accent: "#FF5C35", surface: "#151922", textPrimary: "#FFFFFF" }, typographyPreset: "data", backgroundProfile: "technology", background: { intensity: "expressive", photoMode: "conditional", photoSaturation: "natural", photoOverlay: "medium" }, resources: { photo: "allow", layeredComposite: "allow", typographicFocal: "allow", gradients: "allow" }, photoComposite: { mode: "preferred", visualRole: "atmosphere", layerLogic: "heroData", styleBlend: "contrastMedia" },
      introducedIn: 7, facets: { useCases: ["keynote", "event", "product-launch"], audiences: ["public", "customer"], moods: ["dramatic", "bold"], media: ["photo", "typography"], industries: ["general-business", "technology"] }, distinctiveRules: ["한 장면", "한 메시지", "원거리 가독성"], avoidRules: ["한 화면에 여러 카드", "장면을 가리는 장문"],
    },
    {
      id: "premium-serif-neutral", category: "branding", nameKo: "프리미엄 세리프 뉴트럴", nameEn: "Premium Serif Neutral",
      aliases: ["세리프 프리미엄", "고급 뉴트럴", "럭셔리 베이지", "브랜드 북"], description: "제목용 명조와 절제된 뉴트럴 팔레트로 조용한 고급감을 표현합니다.", bestFor: "프리미엄 브랜드 · 건축·공간 · 전문서비스", tags: ["세리프", "뉴트럴", "프리미엄", "여백"],
      promptKo: "큰 제목과 짧은 인용에만 정제된 한글 명조 인상을 사용하고 본문·수치·주석은 선명한 산세리프로 유지한다. 크림, 차콜과 옅은 브론즈를 넓은 여백 안에서 절제해 사용한다.", promptEn: "Use a refined Korean serif character only for large headings and short quotations, keeping body copy, figures, and annotations in a crisp sans serif. Restrain cream, charcoal, and pale bronze within generous whitespace.",
      keywords: "정제, 품격, 여백, 대비", motif: "대형 명조 제목과 얇은 브론즈 선", visual: { formality: 1, energy: 1, expression: 3, rationality: 3, geometry: 2, depth: 2 }, compositionProfile: "editorial",
      composition: { formLanguage: "preciseGeometric", lineLanguage: "minimalDivider", surfaceLanguage: "material", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "whitespaceScale", container: "borderless", density: "airy", primaryVisualLanguage: "typography", secondaryVisualLanguage: "photo", whitespacePercent: 36 }, palette: { mode: "light", background: "#F4F0E8", primary: "#24221F", secondary: "#776E63", accent: "#A98052", surface: "#FBF9F4", textPrimary: "#24221F" }, typographyPreset: "premium", typography: { emphasis: "balanced", voice: "editorial", hierarchyStyle: "editorialContrast", rhythm: "airy", fallback: "refined Korean serif headlines with legible sans-serif body", headlineCharacter: "restrained", headlineScale: "xlarge", bodyScale: "standard", letterSpacing: "wide" }, resources: { photo: "allow", typographicFocal: "allow", gradients: "exclude" }, photoComposite: { mode: "conditional", visualRole: "concept", layerLogic: "editorialCollage", styleBlend: "controlledHybrid" },
      introducedIn: 7, facets: { useCases: ["brand", "company-profile", "proposal"], audiences: ["client", "public"], moods: ["premium", "restrained"], media: ["typography", "photo"], industries: ["luxury", "architecture", "professional-service"] }, distinctiveRules: ["명조는 큰 제목만", "크림·차콜 중심", "얇은 브론즈 선"], avoidRules: ["본문 전체 명조", "금색 광택 효과"],
    },
    {
      id: "eco-material", category: "branding", nameKo: "에코 내추럴 머티리얼", nameEn: "Eco Natural Material",
      aliases: ["친환경", "내추럴", "지속가능 소재", "에코 브랜드"], description: "재생지·목재·식물의 실제 질감과 환경 데이터를 함께 사용하는 지속가능 디자인입니다.", bestFor: "친환경 사업 · ESG 캠페인 · 로컬 브랜드", tags: ["친환경", "재생지", "자연", "ESG"],
      promptKo: "재생지, 목재, 식물과 원재료의 사실적 질감을 절제된 배경과 사진에 사용한다. 환경 주장과 수치는 제공된 근거만 표시하고 자연 이미지를 장식용 그린워싱으로 사용하지 않는다.", promptEn: "Use realistic textures of recycled paper, wood, plants, and raw materials in restrained backgrounds and photography. Show only supplied evidence for environmental claims and avoid decorative greenwashing imagery.",
      keywords: "자연, 소재, 순환, 진정성", motif: "재생지 표면과 순환형 데이터 링", visual: { formality: 2, energy: 2, expression: 4, rationality: 2, geometry: 4, depth: 3 }, compositionProfile: "editorial",
      composition: { formLanguage: "organic", lineLanguage: "fineStructural", surfaceLanguage: "material", spatialRhythm: "flowing", hierarchyBehavior: "layerPosition", container: "mixed", density: "balanced", primaryVisualLanguage: "photo", secondaryVisualLanguage: "data", whitespacePercent: 24, layerCount: 3 }, palette: { mode: "light", background: "#EEE9DC", primary: "#285943", secondary: "#7B7755", accent: "#C7673A", surface: "#F8F5EC", textPrimary: "#26312B" }, typographyPreset: "editorial", backgroundProfile: "conditional", resources: { photo: "allow", dataVisualization: "allow", diagramInfographic: "allow", layeredComposite: "allow" }, photoComposite: { mode: "preferred", visualRole: "evidence", layerLogic: "contextEvidenceAnnotation", styleBlend: "unifiedMaterial" },
      introducedIn: 7, facets: { useCases: ["esg", "brand", "campaign"], audiences: ["public", "customer", "investor"], moods: ["natural", "credible"], media: ["photo", "texture", "data"], industries: ["environment", "consumer", "food"] }, distinctiveRules: ["실제 소재 질감", "근거 기반 환경 수치", "자연색의 국소 사용"], avoidRules: ["근거 없는 친환경 상징", "전면 녹색 워시"],
    },
    {
      id: "retail-seasonal-campaign", category: "korea-commercial", nameKo: "리테일 시즌 캠페인", nameEn: "Retail Seasonal Campaign",
      aliases: ["시즌 프로모션", "유통 캠페인", "상품 기획전", "이벤트 제안"], description: "상품·시즌 메시지·채널 일정과 판매 목표를 하나의 캠페인 보드로 묶습니다.", bestFor: "유통 기획전 · 브랜드 프로모션 · 채널 제안", tags: ["리테일", "시즌", "상품", "프로모션"],
      promptKo: "제공된 상품 이미지, 시즌 키비주얼, 핵심 혜택, 채널별 일정과 목표를 하나의 캠페인 시스템으로 구성한다. 가격·할인·판매 수치는 입력된 값만 사용하고 강조색은 혜택과 행동 요청에만 집중한다.", promptEn: "Organize supplied product imagery, seasonal key visual, core offer, channel schedule, and targets as one campaign system. Use only supplied prices, discounts, and sales figures, concentrating accent color on benefits and calls to action.",
      keywords: "시즌, 상품, 혜택, 채널", motif: "상품 히어로와 채널 캘린더 밴드", visual: { formality: 4, energy: 5, expression: 5, rationality: 3, geometry: 2, depth: 4 }, compositionProfile: "dynamic",
      composition: { formLanguage: "mixed", lineLanguage: "boldDirectional", surfaceLanguage: "controlledLayer", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "colorScale", container: "mixed", density: "dense", primaryVisualLanguage: "photo", secondaryVisualLanguage: "data", whitespacePercent: 12, layerCount: 4 }, palette: { mode: "light", background: "#FFF7ED", primary: "#1E293B", secondary: "#E85D3F", accent: "#FFCC33", surface: "#FFFFFF" }, typographyPreset: "data", backgroundProfile: "conditional", resources: { photo: "allow", layeredComposite: "allow", dataVisualization: "allow", typographicFocal: "allow", icons: "allow" }, photoComposite: { mode: "preferred", visualRole: "concept", layerLogic: "heroData", styleBlend: "contrastMedia" },
      introducedIn: 7, facets: { useCases: ["campaign", "sales", "product-launch"], audiences: ["customer", "partner"], moods: ["energetic", "bold"], media: ["photo", "data"], industries: ["retail", "consumer", "food"] }, distinctiveRules: ["상품 히어로", "혜택과 CTA 한정 강조", "채널 일정 밴드"], avoidRules: ["가짜 가격·할인", "상품을 가리는 장식"],
    },
    {
      id: "hospitality-sensory", category: "branding", nameKo: "호스피탈리티 센서리", nameEn: "Hospitality Sensory",
      aliases: ["호텔 감성", "여행 브랜드", "F&B 감성", "센서리"], description: "빛·공간·음식·재료의 감각을 크게 보여주는 경험 중심 브랜드 프레젠테이션입니다.", bestFor: "호텔·관광 · F&B · 공간 브랜드", tags: ["호스피탈리티", "감각", "사진", "경험"],
      promptKo: "공간, 음식, 재료와 사람의 경험을 자연광과 실제 질감이 살아 있는 사진으로 보여준다. 큰 사진, 짧은 감각 언어와 구체적인 서비스 정보가 균형을 이루게 한다.", promptEn: "Show spaces, food, materials, and human experience through photography with natural light and tangible texture. Balance large imagery and concise sensory language with specific service information.",
      keywords: "경험, 감각, 공간, 환대", motif: "풀블리드 감각 사진과 작은 정보 캡션", visual: { formality: 3, energy: 3, expression: 5, rationality: 4, geometry: 4, depth: 4 }, compositionProfile: "editorial",
      composition: { formLanguage: "organic", lineLanguage: "minimalDivider", surfaceLanguage: "material", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "scalePosition", container: "borderless", density: "airy", primaryVisualLanguage: "photo", secondaryVisualLanguage: "typography", whitespacePercent: 30, layerCount: 3 }, palette: { mode: "light", background: "#F5EFE6", primary: "#2D2926", secondary: "#8A6D52", accent: "#B84A3A", surface: "#FCFAF6" }, typographyPreset: "editorial", backgroundProfile: "conditional", resources: { photo: "allow", layeredComposite: "allow", typographicFocal: "allow" }, photoComposite: { mode: "preferred", visualRole: "atmosphere", layerLogic: "editorialCollage", styleBlend: "unifiedMaterial" },
      introducedIn: 7, facets: { useCases: ["brand", "proposal", "campaign"], audiences: ["customer", "partner"], moods: ["sensory", "warm", "premium"], media: ["photo", "texture"], industries: ["hospitality", "tourism", "food"] }, distinctiveRules: ["자연광", "재료 질감", "짧은 감각 언어"], avoidRules: ["과도한 필터", "서비스 정보 없는 분위기 사진"],
    },
    {
      id: "clay-3d-friendly", category: "creative", nameKo: "클레이 3D 프렌들리", nameEn: "Friendly Clay 3D",
      aliases: ["클레이 3D", "점토 일러스트", "친근한 3D", "소프트 3D"], description: "단순한 점토 질감의 3D 개체로 서비스와 교육 개념을 부담 없이 설명합니다.", bestFor: "서비스 안내 · 교육 · 조직 캠페인", tags: ["3D", "클레이", "친근", "일러스트"],
      promptKo: "매트한 점토 질감, 단순한 둥근 3D 개체와 부드러운 그림자를 사용해 핵심 개념을 설명한다. 3D 개체는 의미 있는 범주나 단계에만 사용하고 한글과 데이터는 평면에서 선명하게 유지한다.", promptEn: "Use matte clay texture, simple rounded 3D objects, and soft shadows to explain key concepts. Reserve 3D objects for meaningful categories or stages, keeping Korean text and data crisp on a flat plane.",
      keywords: "친근, 입체, 설명, 부드러움", motif: "점토 오브젝트와 평면 라벨", visual: { formality: 4, energy: 4, expression: 5, rationality: 3, geometry: 4, depth: 5 }, compositionProfile: "dynamic",
      composition: { formLanguage: "softGeometric", lineLanguage: "shapeLed", surfaceLanguage: "material", spatialRhythm: "modular", hierarchyBehavior: "layerPosition", container: "mixed", density: "balanced", primaryVisualLanguage: "technical3d", secondaryVisualLanguage: "typography", whitespacePercent: 22, layerCount: 4 }, palette: { mode: "light", background: "#F7F4FF", primary: "#584A86", secondary: "#63B3A6", accent: "#F28B66", surface: "#FFFFFF" }, typographyPreset: "public", backgroundProfile: "conditional", resources: { threeD: "allow", illustration: "allow", typographicFocal: "allow", icons: "exclude" },
      introducedIn: 7, facets: { useCases: ["service-introduction", "training", "campaign"], audiences: ["customer", "employee", "student"], moods: ["friendly", "playful"], media: ["3d", "illustration"], industries: ["service", "education", "consumer"] }, distinctiveRules: ["매트 점토 재질", "단순한 의미 오브젝트", "평면 텍스트 레이어"], avoidRules: ["장난감 도시", "3D 텍스트", "불필요한 캐릭터"],
    },
  ];
})(window);
