(function (global) {
  "use strict";

  const packs = global.PromptDeckSlideStylePresetPacks || (global.PromptDeckSlideStylePresetPacks = {});

  packs.commercialCore = [
    {
      id: "korean-clean-office", category: "reporting", nameKo: "한국형 클린 오피스", nameEn: "Korean Clean Office",
      aliases: ["클린 오피스", "사내 보고", "업무 보고", "깔끔한 회사 PPT"], description: "화이트 캔버스와 블루·그레이 역할색으로 국내 기업의 일상 보고를 빠르게 정리합니다.", bestFor: "주간보고 · 부서회의 · 업무계획", tags: ["사내", "깔끔", "블루", "업무"],
      promptKo: "국내 기업의 실무 보고서처럼 흰색 바탕, 블루·그레이 역할색, 얇은 구분선과 정돈된 표·차트를 사용한다. 장식보다 결론, 담당, 일정과 수치를 먼저 읽히게 한다.", promptEn: "Use a Korean corporate working-report style with a white canvas, blue-gray role colors, thin dividers, and orderly tables and charts. Prioritize conclusions, owners, schedules, and figures over decoration.",
      keywords: "실무, 명료, 정돈, 실행", motif: "블루 제목선과 정렬된 업무 블록", visual: { formality: 1, energy: 2, expression: 1, rationality: 1, geometry: 1, depth: 1 }, compositionProfile: "stable",
      composition: { lineLanguage: "minimalDivider", spatialRhythm: "ordered", hierarchyBehavior: "scalePosition", container: "borderless", density: "balanced", primaryVisualLanguage: "data", secondaryVisualLanguage: "diagram", whitespacePercent: 26 }, palette: { mode: "light", background: "#FFFFFF", primary: "#174A8B", secondary: "#64748B", accent: "#0EA5A8", surface: "#F5F7FA" }, typographyPreset: "public", resources: { dataVisualization: "allow", diagramInfographic: "allow", icons: "allow" },
      recommended: true, introducedIn: 7, facets: { useCases: ["report", "planning"], audiences: ["internal", "manager"], moods: ["restrained", "clear"], media: ["data", "diagram"], industries: ["general-business"] }, distinctiveRules: ["화이트 캔버스", "얇은 블루 제목선", "담당·일정·수치 우선"], avoidRules: ["과한 카드 중첩", "장식용 그라데이션"],
    },
    {
      id: "neutral-beige-proposal", category: "reporting", nameKo: "뉴트럴 베이지 제안서", nameEn: "Neutral Beige Proposal",
      aliases: ["베이지 제안서", "웜 미니멀", "아이보리 기획서"], description: "아이보리와 웜그레이를 사용해 차분하면서도 딱딱하지 않은 제안서 인상을 만듭니다.", bestFor: "프로젝트 제안 · 파트너십 · 서비스 기획", tags: ["베이지", "제안", "차분", "미니멀"],
      promptKo: "아이보리 캔버스와 웜그레이 구조, 짙은 갈색 텍스트, 절제된 테라코타 강조를 사용한다. 넓은 여백과 편안한 문단 폭을 유지하면서 제안의 문제, 해법과 기대효과가 순서대로 읽히게 한다.", promptEn: "Use an ivory canvas, warm-gray structure, dark brown text, and restrained terracotta accents. Preserve generous whitespace and comfortable line lengths while making the problem, solution, and expected impact read in sequence.",
      keywords: "따뜻함, 신뢰, 제안, 여백", motif: "아이보리 여백과 얇은 테라코타 포인트", visual: { formality: 2, energy: 2, expression: 2, rationality: 2, geometry: 2, depth: 1 }, compositionProfile: "controlled",
      composition: { formLanguage: "softGeometric", lineLanguage: "minimalDivider", surfaceLanguage: "flat", spatialRhythm: "ordered", hierarchyBehavior: "whitespaceScale", container: "borderless", density: "balanced", primaryVisualLanguage: "typography", secondaryVisualLanguage: "diagram", whitespacePercent: 32 }, palette: { mode: "light", background: "#F7F1E8", primary: "#3B342F", secondary: "#8A7B70", accent: "#C66A4A", surface: "#FFFDFC", textPrimary: "#2B2724" }, typographyPreset: "editorial", resources: { diagramInfographic: "allow", typographicFocal: "allow", photo: "allow" },
      recommended: true, introducedIn: 7, facets: { useCases: ["proposal", "planning"], audiences: ["client", "partner"], moods: ["warm", "restrained"], media: ["typography", "diagram"], industries: ["general-business", "service"] }, distinctiveRules: ["아이보리 바탕", "웜그레이 정보 구조", "테라코타 최소 강조"], avoidRules: ["전체 화면 베이지 단색화", "낮은 본문 대비"],
    },
    {
      id: "mono-executive", category: "reporting", nameKo: "모노크롬 경영진 보고", nameEn: "Monochrome Executive",
      aliases: ["흑백 경영보고", "블랙 앤 화이트", "임원 보고"], description: "흑백 고대비와 큰 숫자로 판단에 필요한 결론만 강하게 남깁니다.", bestFor: "경영회의 · 원페이지 요약 · 의사결정", tags: ["흑백", "경영진", "고대비", "원페이지"],
      promptKo: "순백과 짙은 흑연색만으로 구조를 만들고 핵심 결론과 숫자 한두 개에만 크기 대비를 집중한다. 선, 표와 차트는 회색 단계로 구분하며 불필요한 색과 장식을 사용하지 않는다.", promptEn: "Build the structure with pure white and deep graphite, concentrating scale contrast on one conclusion and one or two key figures. Separate lines, tables, and charts with gray levels and avoid unnecessary color or decoration.",
      keywords: "결정, 절제, 흑백, 대비", motif: "초대형 핵심 수치와 가는 흑연 기준선", visual: { formality: 1, energy: 2, expression: 2, rationality: 1, geometry: 1, depth: 1 }, compositionProfile: "dataFocus",
      composition: { lineLanguage: "fineStructural", surfaceLanguage: "flat", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "scalePosition", container: "borderless", density: "balanced", primaryVisualLanguage: "data", secondaryVisualLanguage: "typography", whitespacePercent: 30, focalAreaPercent: 48 }, palette: { mode: "light", background: "#FFFFFF", primary: "#111111", secondary: "#707070", accent: "#111111", surface: "#F4F4F2", textPrimary: "#111111" }, typographyPreset: "data", resources: { dataVisualization: "allow", typographicFocal: "allow", gradients: "exclude", illustration: "exclude" },
      introducedIn: 7, facets: { useCases: ["report", "executive-summary"], audiences: ["executive"], moods: ["restrained", "authoritative"], media: ["data", "typography"], industries: ["general-business"] }, distinctiveRules: ["무채색 단계만 사용", "한 개 결론 중심", "초대형 숫자"], avoidRules: ["장식색 추가", "여러 강조점 경쟁"],
    },
    {
      id: "b2b-sales-proposal", category: "korea-commercial", nameKo: "B2B 영업 제안", nameEn: "B2B Sales Proposal",
      aliases: ["영업 제안서", "세일즈 덱", "고객 제안", "솔루션 제안서"], description: "고객의 문제에서 도입 효과와 실행 범위까지 이어지는 설득 흐름을 만듭니다.", bestFor: "고객 제안 · 솔루션 영업 · 파트너 미팅", tags: ["영업", "고객", "솔루션", "효과"],
      promptKo: "고객의 현재 문제, 해결 구조, 기대 성과, 도입 단계와 다음 행동이 한 방향으로 이어지게 한다. 고객 근거와 도입 효과를 네이비·틸의 명확한 비교 구조로 보여주고 과장된 성과 수치는 만들지 않는다.", promptEn: "Connect the customer's current problem, solution structure, expected impact, rollout steps, and next action in one direction. Show customer evidence and impact through clear navy-teal comparisons without inventing performance figures.",
      keywords: "고객, 문제, 해법, 전환", motif: "문제에서 성과로 이어지는 단일 흐름", visual: { formality: 1, energy: 3, expression: 2, rationality: 1, geometry: 1, depth: 2 }, compositionProfile: "controlled",
      composition: { lineLanguage: "boldDirectional", surfaceLanguage: "mattePanels", spatialRhythm: "modular", hierarchyBehavior: "scalePosition", container: "mixed", density: "balanced", primaryVisualLanguage: "diagram", secondaryVisualLanguage: "data", whitespacePercent: 20 }, palette: { mode: "light", background: "#F7FAFC", primary: "#0A2E5D", secondary: "#117A8B", accent: "#F26A3D", surface: "#FFFFFF" }, typographyPreset: "public", resources: { diagramInfographic: "allow", dataVisualization: "allow", icons: "allow", photo: "allow" },
      recommended: true, introducedIn: 7, facets: { useCases: ["proposal", "sales"], audiences: ["client", "decision-maker"], moods: ["clear", "persuasive"], media: ["diagram", "data"], industries: ["b2b", "service", "technology"] }, distinctiveRules: ["고객 문제부터 시작", "도입효과 비교", "명확한 다음 행동"], avoidRules: ["근거 없는 성과 수치", "공급자 소개로 시작"],
    },
    {
      id: "photo-company-profile", category: "branding", nameKo: "포토 회사소개서", nameEn: "Photo-led Company Profile",
      aliases: ["회사소개서", "기업소개", "현장 사진", "브랜드 프로필"], description: "실제 사람·시설·제품 사진을 중심으로 기업의 규모와 신뢰를 보여줍니다.", bestFor: "회사소개 · 파트너십 · 채용·전시", tags: ["회사소개", "사진", "기업", "현장"],
      promptKo: "실제 제공된 사람, 시설, 제품과 현장 사진을 넓게 사용하고 사진 위 텍스트는 최소화한다. 기업 개요, 역량, 주요 실적과 네트워크를 사진 캡션과 정돈된 숫자 블록으로 연결한다.", promptEn: "Use supplied photography of people, facilities, products, and operations at generous scale with minimal text over images. Connect company overview, capabilities, evidence, and network through captions and orderly numeric blocks.",
      keywords: "현장, 규모, 사람, 신뢰", motif: "넓은 현장 사진과 간결한 캡션 레일", visual: { formality: 2, energy: 3, expression: 3, rationality: 2, geometry: 2, depth: 3 }, compositionProfile: "editorial",
      composition: { formLanguage: "mixed", surfaceLanguage: "controlledLayer", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "layerPosition", container: "borderless", density: "balanced", primaryVisualLanguage: "photo", secondaryVisualLanguage: "typography", whitespacePercent: 20, layerCount: 3 }, palette: { mode: "light", background: "#F8F8F6", primary: "#172033", secondary: "#607080", accent: "#D65A38", surface: "#FFFFFF" }, typographyPreset: "editorial", backgroundProfile: "conditional", background: { photoMode: "conditional", photoSaturation: "natural", photoOverlay: "light" }, resources: { photo: "allow", layeredComposite: "allow", typographicFocal: "allow", dataVisualization: "allow" }, photoComposite: { mode: "preferred", visualRole: "evidence", layerLogic: "contextEvidenceAnnotation", styleBlend: "contrastMedia" },
      introducedIn: 7, facets: { useCases: ["company-profile", "proposal"], audiences: ["client", "partner", "candidate"], moods: ["credible", "human"], media: ["photo", "typography"], industries: ["general-business"] }, distinctiveRules: ["실제 제공 사진 중심", "짧은 캡션 레일", "사람과 현장 우선"], avoidRules: ["무관한 스톡 사진", "사진 위 장문"],
    },
    {
      id: "service-introduction", category: "korea-commercial", nameKo: "서비스 소개서", nameEn: "Service Introduction",
      aliases: ["서비스 설명서", "서비스 제안", "이용 흐름", "플랫폼 소개"], description: "서비스 가치와 사용 과정을 친절한 단계·화면·접점 구조로 설명합니다.", bestFor: "신규 서비스 · 플랫폼 소개 · 제휴 설명", tags: ["서비스", "사용자", "프로세스", "소개"],
      promptKo: "서비스가 해결하는 상황, 핵심 기능, 사용자 흐름, 운영 방식과 도입 가치를 단계적으로 설명한다. 둥근 선과 절제된 색면을 사용하되 화면이나 기능은 제공된 내용만 표현한다.", promptEn: "Explain the situation solved by the service, core capabilities, user flow, operating model, and adoption value in stages. Use rounded lines and restrained color fields while depicting only supplied screens and functions.",
      keywords: "서비스, 사용자, 흐름, 친절", motif: "접점을 잇는 라운드 단계선", visual: { formality: 2, energy: 3, expression: 3, rationality: 2, geometry: 2, depth: 2 }, compositionProfile: "controlled",
      composition: { formLanguage: "softGeometric", lineLanguage: "shapeLed", surfaceLanguage: "mattePanels", spatialRhythm: "flowing", hierarchyBehavior: "colorScale", container: "cards", density: "balanced", primaryVisualLanguage: "diagram", secondaryVisualLanguage: "illustration", whitespacePercent: 22 }, palette: { mode: "light", background: "#F7FBFA", primary: "#145E75", secondary: "#4F8F85", accent: "#F28C5B", surface: "#FFFFFF" }, typographyPreset: "public", resources: { diagramInfographic: "allow", icons: "allow", illustration: "allow" },
      introducedIn: 7, facets: { useCases: ["service-introduction", "proposal"], audiences: ["customer", "partner"], moods: ["friendly", "clear"], media: ["diagram", "illustration"], industries: ["service", "platform"] }, distinctiveRules: ["상황-기능-흐름-가치 순서", "라운드 단계선", "접점 중심"], avoidRules: ["가짜 앱 화면", "기능 과장"],
    },
    {
      id: "people-culture", category: "korea-commercial", nameKo: "피플·조직문화", nameEn: "People & Culture",
      aliases: ["조직문화", "HR 보고", "인사 전략", "피플 리포트"], description: "사람·조직·제도를 따뜻한 인물 사진과 명료한 조직 지표로 함께 다룹니다.", bestFor: "인사전략 · 조직문화 · 타운홀", tags: ["HR", "조직", "문화", "사람"],
      promptKo: "구성원 경험, 조직 원칙, 인재 지표와 실행 과제를 사람 중심의 사진과 부드러운 데이터 블록으로 연결한다. 개인을 장식처럼 소비하지 않고 제공된 조직 사실과 익명화된 지표만 사용한다.", promptEn: "Connect employee experience, organizational principles, people metrics, and actions through human-centered photography and soft data blocks. Do not use people as decoration, and use only supplied organizational facts and anonymized metrics.",
      keywords: "사람, 연결, 문화, 성장", motif: "인물 사진과 연결 원형 지표", visual: { formality: 2, energy: 3, expression: 3, rationality: 2, geometry: 3, depth: 3 }, compositionProfile: "editorial",
      composition: { formLanguage: "organic", lineLanguage: "shapeLed", surfaceLanguage: "mattePanels", spatialRhythm: "flowing", hierarchyBehavior: "scalePosition", container: "mixed", density: "balanced", primaryVisualLanguage: "photo", secondaryVisualLanguage: "data", whitespacePercent: 24 }, palette: { mode: "light", background: "#FBF8F2", primary: "#214A47", secondary: "#8B6F5A", accent: "#E46E5D", surface: "#FFFFFF" }, typographyPreset: "editorial", backgroundProfile: "conditional", resources: { photo: "allow", dataVisualization: "allow", icons: "allow" }, photoComposite: { mode: "preferred", visualRole: "evidence", layerLogic: "contextEvidenceAnnotation", styleBlend: "controlledHybrid" },
      introducedIn: 7, facets: { useCases: ["hr", "report", "townhall"], audiences: ["employee", "manager"], moods: ["human", "warm"], media: ["photo", "data"], industries: ["general-business"] }, distinctiveRules: ["사람과 지표의 균형", "따뜻한 중성색", "조직 원칙 시각화"], avoidRules: ["개인정보 노출", "과도한 행복 연출"],
    },
    {
      id: "employee-handbook", category: "korea-commercial", nameKo: "온보딩·직원 가이드", nameEn: "Employee Handbook",
      aliases: ["직원 가이드", "온보딩", "신입사원 교육", "업무 매뉴얼"], description: "규정과 업무 절차를 찾기 쉬운 목차·아이콘·체크리스트 체계로 구성합니다.", bestFor: "온보딩 · 사내 규정 · 업무 안내", tags: ["온보딩", "가이드", "체크리스트", "사내"],
      promptKo: "직원이 필요한 정보를 빠르게 찾도록 섹션 번호, 짧은 규칙, 체크리스트, 연락·절차 블록을 일관된 위치에 둔다. 친근하지만 장난스럽지 않은 블루와 민트로 안내 체계를 구분한다.", promptEn: "Place section numbers, concise rules, checklists, contacts, and procedures in consistent locations so employees can find information quickly. Use friendly but professional blue and mint to separate guidance levels.",
      keywords: "안내, 규칙, 탐색, 온보딩", motif: "번호 탭과 체크리스트 레일", visual: { formality: 2, energy: 2, expression: 2, rationality: 1, geometry: 2, depth: 1 }, compositionProfile: "stable",
      composition: { formLanguage: "softGeometric", lineLanguage: "fineStructural", surfaceLanguage: "flat", spatialRhythm: "modular", hierarchyBehavior: "colorScale", container: "cards", density: "balanced", primaryVisualLanguage: "diagram", secondaryVisualLanguage: "typography", whitespacePercent: 22 }, palette: { mode: "light", background: "#F7FAFC", primary: "#235789", secondary: "#4F9D8E", accent: "#F2A65A", surface: "#FFFFFF" }, typographyPreset: "public", resources: { icons: "allow", diagramInfographic: "allow", illustration: "allow" },
      introducedIn: 7, facets: { useCases: ["hr", "manual", "training"], audiences: ["employee", "new-hire"], moods: ["friendly", "clear"], media: ["diagram", "typography"], industries: ["general-business"] }, distinctiveRules: ["번호 탭", "짧은 규칙", "반복 위치 고정"], avoidRules: ["장문을 도형 안에 배치", "아동용 캐릭터 톤"],
    },
    {
      id: "training-workshop", category: "korea-commercial", nameKo: "교육·워크숍 플레이북", nameEn: "Training Workshop Playbook",
      aliases: ["워크숍", "교육자료", "강의안", "퍼실리테이션"], description: "학습 목표와 활동·토론·정리 단계를 참여형 워크숍 문법으로 구분합니다.", bestFor: "사내교육 · 워크숍 · 실습 세미나", tags: ["교육", "워크숍", "실습", "참여"],
      promptKo: "학습목표, 짧은 설명, 참여 활동, 토론 질문과 정리 결과가 한눈에 구분되게 한다. 메모지와 마커의 인간적인 감각을 사용하되 정렬과 한글 가독성은 엄격하게 유지한다.", promptEn: "Clearly separate learning objectives, concise explanation, participant activity, discussion prompts, and takeaways. Use the human feel of notes and markers while preserving rigorous alignment and Korean legibility.",
      keywords: "참여, 학습, 활동, 정리", motif: "정돈된 메모지와 활동 타이머", visual: { formality: 3, energy: 4, expression: 4, rationality: 2, geometry: 3, depth: 2 }, compositionProfile: "dynamic",
      composition: { formLanguage: "mixed", lineLanguage: "shapeLed", surfaceLanguage: "material", spatialRhythm: "modular", hierarchyBehavior: "colorScale", container: "cards", density: "balanced", primaryVisualLanguage: "illustration", secondaryVisualLanguage: "typography", whitespacePercent: 18, layerCount: 3 }, palette: { mode: "light", background: "#FFFDF7", primary: "#243B53", secondary: "#48A999", accent: "#F4B740", surface: "#FFFFFF" }, typographyPreset: "public", resources: { illustration: "allow", icons: "allow", diagramInfographic: "allow", typographicFocal: "allow" },
      introducedIn: 7, facets: { useCases: ["training", "workshop"], audiences: ["employee", "student"], moods: ["friendly", "energetic"], media: ["illustration", "typography"], industries: ["education", "general-business"] }, distinctiveRules: ["활동 단계 구분", "정돈된 메모 질감", "토론 질문 강조"], avoidRules: ["무질서한 포스트잇 남발", "낮은 대비 필기체"],
    },
    {
      id: "market-research-board", category: "reporting", nameKo: "시장조사 인사이트", nameEn: "Market Research Insight Board",
      aliases: ["시장조사", "리서치 인사이트", "고객 조사", "트렌드 분석"], description: "조사 근거에서 고객 행동과 사업 기회로 이어지는 인사이트 보드입니다.", bestFor: "시장조사 · 고객분석 · 신사업 탐색", tags: ["리서치", "인사이트", "고객", "기회"],
      promptKo: "조사 출처, 관찰 사실, 고객 인용, 패턴과 사업 기회를 구분하고 근거에서 해석으로 이어지는 관계를 표시한다. 사진·인용문·차트가 경쟁하지 않게 편집 보드 구조로 정리한다.", promptEn: "Separate research sources, observations, customer quotes, patterns, and business opportunities, explicitly linking evidence to interpretation. Organize photos, quotes, and charts in an editorial board without visual competition.",
      keywords: "관찰, 근거, 패턴, 기회", motif: "근거 카드에서 기회로 이어지는 연결선", visual: { formality: 2, energy: 3, expression: 3, rationality: 1, geometry: 2, depth: 2 }, compositionProfile: "editorial",
      composition: { formLanguage: "mixed", lineLanguage: "fineStructural", surfaceLanguage: "mattePanels", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "scalePosition", container: "mixed", density: "dense", primaryVisualLanguage: "data", secondaryVisualLanguage: "photo", whitespacePercent: 16, layerCount: 3 }, palette: { mode: "light", background: "#F6F4EF", primary: "#1F3A4D", secondary: "#687864", accent: "#E07A5F", surface: "#FFFFFF" }, typographyPreset: "editorial", resources: { dataVisualization: "allow", photo: "allow", diagramInfographic: "allow", typographicFocal: "allow" }, photoComposite: { mode: "conditional", visualRole: "evidence", layerLogic: "editorialCollage", styleBlend: "controlledHybrid" },
      introducedIn: 7, facets: { useCases: ["research", "report", "planning"], audiences: ["manager", "client"], moods: ["analytical", "editorial"], media: ["data", "photo"], industries: ["general-business", "consumer"] }, distinctiveRules: ["사실과 해석 분리", "고객 인용 표시", "기회 연결선"], avoidRules: ["근거 없는 인사이트", "장식용 인용문"],
    },
    {
      id: "product-ui-story", category: "startup", nameKo: "프로덕트 UI 스토리", nameEn: "Product UI Story",
      aliases: ["UI 스토리", "앱 소개", "제품 화면", "사용자 여정"], description: "제공된 실제 화면을 사용자 문제와 기능 가치에 연결하는 제품 설명형 구성입니다.", bestFor: "SaaS 데모 · 앱 소개 · 제품 로드맵", tags: ["UI", "제품", "SaaS", "사용자"],
      promptKo: "제공된 실제 UI 화면과 기능 명세만 사용해 사용자의 시작 상황, 핵심 행동, 결과와 제품 가치를 설명한다. 기기 목업 프레임을 남발하지 않고 화면 자체, 짧은 주석과 흐름선을 중심으로 구성한다.", promptEn: "Use only supplied UI screens and feature specifications to explain the user's starting situation, key action, outcome, and product value. Avoid excessive device mockup frames and focus on the interface itself, concise annotations, and flow lines.",
      keywords: "제품, 화면, 행동, 가치", motif: "화면 조각과 기능 주석 레일", visual: { formality: 2, energy: 4, expression: 3, rationality: 1, geometry: 1, depth: 2 }, compositionProfile: "controlled",
      composition: { formLanguage: "preciseGeometric", lineLanguage: "fineStructural", surfaceLanguage: "controlledLayer", spatialRhythm: "modular", hierarchyBehavior: "layerPosition", container: "mixed", density: "balanced", primaryVisualLanguage: "diagram", secondaryVisualLanguage: "typography", whitespacePercent: 18, layerCount: 3 }, palette: { mode: "light", background: "#F7F8FC", primary: "#29356B", secondary: "#5B68D8", accent: "#17A398", surface: "#FFFFFF" }, typographyPreset: "data", resources: { layeredComposite: "allow", diagramInfographic: "allow", icons: "allow", gradients: "allow" },
      recommended: true, introducedIn: 7, facets: { useCases: ["product", "service-introduction", "demo"], audiences: ["customer", "investor"], moods: ["clear", "modern"], media: ["ui", "diagram"], industries: ["software", "platform"] }, distinctiveRules: ["실제 제공 화면만 사용", "기능 주석 레일", "사용자 행동 중심"], avoidRules: ["가짜 UI 생성", "기기 베젤 남발"],
    },
    {
      id: "case-study-portfolio", category: "branding", nameKo: "프로젝트 사례집", nameEn: "Case Study Portfolio",
      aliases: ["케이스 스터디", "수행 사례", "포트폴리오", "레퍼런스"], description: "과제·접근·산출물·결과를 프로젝트별로 일관되게 기록하는 사례집입니다.", bestFor: "에이전시 · 전문서비스 · 수행실적", tags: ["사례", "포트폴리오", "성과", "과정"],
      promptKo: "각 프로젝트를 배경, 핵심 과제, 접근 방식, 주요 산출물과 확인된 결과의 동일한 순서로 보여준다. 대표 비주얼은 크게, 과정과 역할은 짧고 정확하게 배치한다.", promptEn: "Present every project in the same sequence: context, core challenge, approach, key deliverables, and verified outcomes. Give the hero visual generous scale and describe process and role briefly and accurately.",
      keywords: "과제, 접근, 결과, 증거", motif: "대형 결과물과 세로형 프로젝트 인덱스", visual: { formality: 2, energy: 3, expression: 4, rationality: 2, geometry: 2, depth: 3 }, compositionProfile: "editorial",
      composition: { formLanguage: "mixed", lineLanguage: "minimalDivider", surfaceLanguage: "flat", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "scalePosition", container: "borderless", density: "balanced", primaryVisualLanguage: "photo", secondaryVisualLanguage: "typography", whitespacePercent: 28 }, palette: { mode: "light", background: "#FAFAF8", primary: "#171717", secondary: "#6B7280", accent: "#E4572E", surface: "#FFFFFF" }, typographyPreset: "editorial", backgroundProfile: "conditional", resources: { photo: "allow", layeredComposite: "allow", typographicFocal: "allow", dataVisualization: "allow" }, photoComposite: { mode: "preferred", visualRole: "evidence", layerLogic: "editorialCollage", styleBlend: "contrastMedia" },
      introducedIn: 7, facets: { useCases: ["portfolio", "proposal", "company-profile"], audiences: ["client", "partner"], moods: ["editorial", "credible"], media: ["photo", "typography"], industries: ["agency", "professional-service"] }, distinctiveRules: ["프로젝트별 동일 서사", "결과물 대형 배치", "역할과 결과 분리"], avoidRules: ["검증되지 않은 성과", "작은 썸네일 나열"],
    },
  ];
})(window);
