(function (global) {
  "use strict";

  const packs = global.PromptDeckSlideStylePresetPacks || (global.PromptDeckSlideStylePresetPacks = {});

  packs.localTrend = [
    {
      id: "korean-heritage-modern", category: "branding", nameKo: "한국 헤리티지 모던", nameEn: "Korean Heritage Modern",
      aliases: ["한국 전통 현대화", "한지", "단청", "전통문화"], description: "한지 질감과 전통색·기하 원리를 현대적 그리드 안에 절제해 적용합니다.", bestFor: "문화·관광 · 지역 브랜드 · 전통산업", tags: ["한국", "전통", "한지", "로컬"],
      promptKo: "특정 기관이나 브랜드를 복제하지 않고 한지의 섬유 질감, 오방색에서 가져온 절제된 역할색, 단청의 기하 원리를 현대적인 그리드와 여백에 적용한다. 전통 문양은 의미가 있을 때만 작게 사용한다.", promptEn: "Without copying any institution or brand, apply hanji fiber texture, restrained role colors inspired by traditional Korean palettes, and geometric principles from dancheong within a modern grid and generous whitespace. Use traditional motifs sparingly and only when meaningful.",
      keywords: "전통, 현대, 지역성, 절제", motif: "한지 표면과 현대적으로 단순화한 기하 띠", visual: { formality: 2, energy: 3, expression: 4, rationality: 3, geometry: 2, depth: 2 }, compositionProfile: "editorial",
      composition: { formLanguage: "preciseGeometric", lineLanguage: "fineStructural", surfaceLanguage: "material", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "whitespaceScale", container: "borderless", density: "balanced", primaryVisualLanguage: "typography", secondaryVisualLanguage: "illustration", whitespacePercent: 30, layerCount: 2 }, palette: { mode: "light", background: "#F2E9D8", primary: "#1D3B32", secondary: "#7A3E35", accent: "#C28B2C", surface: "#FBF6EA", textPrimary: "#25231F" }, typographyPreset: "editorial", backgroundProfile: "conditional", resources: { illustration: "allow", typographicFocal: "allow", photo: "allow", layeredComposite: "allow" }, photoComposite: { mode: "conditional", visualRole: "concept", layerLogic: "editorialCollage", styleBlend: "unifiedMaterial" },
      recommended: true, introducedIn: 7, facets: { useCases: ["brand", "campaign", "proposal"], audiences: ["public", "visitor", "partner"], moods: ["local", "refined"], media: ["texture", "typography", "illustration"], industries: ["culture", "tourism", "craft"] }, distinctiveRules: ["한지 섬유 질감", "전통색의 역할 기반 사용", "현대적 그리드"], avoidRules: ["특정 문화재·기관 디자인 복제", "전통 문양 장식 남발"],
    },
    {
      id: "hangeul-typographic", category: "creative", nameKo: "한글 타이포그래픽", nameEn: "Hangeul Typographic",
      aliases: ["한글 타이포", "대형 한글", "타이포 포스터", "한글 중심"], description: "한글 단어와 문장의 형태·리듬을 핵심 비주얼로 사용하는 대담한 편집 스타일입니다.", bestFor: "캠페인 · 포럼 · 브랜드 메시지", tags: ["한글", "타이포", "대담", "포스터"],
      promptKo: "제공된 핵심 한글 문구를 정확히 한 번만 사용하고 크기, 굵기, 줄바꿈과 자간의 대비로 화면의 중심을 만든다. 자모를 임의로 분해하거나 장식 문자로 변형하지 않고 본문 가독성을 보호한다.", promptEn: "Use the supplied Korean key phrase exactly once, making it the focal point through contrast in scale, weight, line breaks, and spacing. Do not arbitrarily decompose or distort Hangul glyphs, and protect body-copy legibility.",
      keywords: "한글, 메시지, 리듬, 대비", motif: "초대형 한글 문장과 작은 정보 캡션", visual: { formality: 4, energy: 5, expression: 5, rationality: 3, geometry: 2, depth: 2 }, compositionProfile: "dynamic",
      composition: { formLanguage: "preciseGeometric", lineLanguage: "boldDirectional", surfaceLanguage: "flat", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "scalePosition", container: "borderless", density: "airy", primaryVisualLanguage: "typography", secondaryVisualLanguage: "none", whitespacePercent: 26, focalAreaPercent: 52 }, palette: { mode: "light", background: "#F6F2E8", primary: "#111111", secondary: "#2354A6", accent: "#E34A33", surface: "#FFFFFF" }, typographyPreset: "data", typography: { emphasis: "strong", voice: "editorial", hierarchyStyle: "scaleWeight", rhythm: "dramatic", fallback: "heavy Korean grotesque sans-serif", headlineCharacter: "modern", headlineScale: "xlarge", bodyScale: "standard", letterSpacing: "tight" }, resources: { typographicFocal: "allow", gradients: "exclude", threeD: "exclude", illustration: "exclude" },
      introducedIn: 7, facets: { useCases: ["campaign", "event", "brand"], audiences: ["public", "customer"], moods: ["bold", "local"], media: ["typography"], industries: ["culture", "media", "consumer"] }, distinctiveRules: ["정확한 한글 한 문장", "크기·줄바꿈 중심", "작은 보조 캡션"], avoidRules: ["한글 자모 왜곡", "동일 문구 반복", "영문 장식 대체"],
    },
    {
      id: "tactile-zine-risograph", category: "creative", nameKo: "텍스처 진·리소그래프", nameEn: "Tactile Zine Risograph",
      aliases: ["진 스타일", "리소그래프", "인쇄 질감", "아날로그 편집"], description: "종이 입자와 제한색 인쇄의 어긋남을 활용해 인간적인 편집 감각을 만듭니다.", bestFor: "문화행사 · 창작 제안 · 브랜드 캠페인", tags: ["진", "리소", "질감", "아날로그"],
      promptKo: "거친 종이 입자, 두세 가지 제한색과 미세한 리소그래프 인쇄 어긋남을 사용한다. 불완전한 질감은 사진과 장식에만 적용하고 한글, 수치와 정보 정렬은 선명하고 정확하게 유지한다.", promptEn: "Use rough paper grain, two or three limited inks, and subtle risograph misregistration. Apply imperfect texture only to imagery and decoration while keeping Korean text, figures, and information alignment crisp and accurate.",
      keywords: "아날로그, 질감, 인쇄, 인간적", motif: "제한색 인쇄 레이어와 거친 종이 가장자리", visual: { formality: 5, energy: 4, expression: 5, rationality: 4, geometry: 4, depth: 3 }, compositionProfile: "editorial",
      composition: { formLanguage: "mixed", lineLanguage: "shapeLed", surfaceLanguage: "material", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "layerPosition", container: "borderless", density: "balanced", primaryVisualLanguage: "illustration", secondaryVisualLanguage: "typography", whitespacePercent: 20, layerCount: 4 }, palette: { mode: "light", background: "#EFE6D2", primary: "#173B57", secondary: "#E04B3F", accent: "#F2B632", surface: "#F8F0DF", textPrimary: "#1B242B" }, typographyPreset: "editorial", backgroundProfile: "conditional", resources: { illustration: "allow", layeredComposite: "allow", typographicFocal: "allow", photo: "allow", gradients: "exclude" }, photoComposite: { mode: "conditional", visualRole: "concept", layerLogic: "editorialCollage", styleBlend: "unifiedMaterial" },
      introducedIn: 7, facets: { useCases: ["campaign", "event", "brand"], audiences: ["public", "customer"], moods: ["tactile", "experimental"], media: ["texture", "illustration", "typography"], industries: ["culture", "media", "consumer"] }, distinctiveRules: ["2~3개 제한색", "미세한 인쇄 어긋남", "종이 입자"], avoidRules: ["텍스트에 번짐 적용", "무질서한 찢김 콜라주"],
    },
    {
      id: "surreal-product-composite", category: "creative", nameKo: "초현실 제품 컴포지트", nameEn: "Surreal Product Composite",
      aliases: ["초현실 제품", "서리얼 캠페인", "제품 합성", "컨셉 비주얼"], description: "제품의 실제 형태를 보존하면서 비현실적인 규모와 공간으로 핵심 효익을 상징화합니다.", bestFor: "제품 론칭 · 광고 캠페인 · 콘셉트 피치", tags: ["초현실", "제품", "합성", "캠페인"],
      promptKo: "제공된 제품의 형태, 색상과 라벨을 정확히 보존하고 제품 효익을 상징하는 한 가지 초현실 장면과 합성한다. 장면은 메시지를 설명해야 하며 제품보다 복잡하거나 사실 정보를 왜곡해서는 안 된다.", promptEn: "Preserve the supplied product's form, color, and label accurately, compositing it with one surreal scene that symbolizes the product benefit. The scene must explain the message without becoming more complex than the product or distorting factual information.",
      keywords: "제품, 상징, 초현실, 집중", motif: "한 개 제품과 비현실적 스케일의 단일 장면", visual: { formality: 4, energy: 5, expression: 5, rationality: 4, geometry: 4, depth: 5 }, compositionProfile: "dynamic",
      composition: { formLanguage: "organic", lineLanguage: "minimalDivider", surfaceLanguage: "controlledLayer", spatialRhythm: "flowing", hierarchyBehavior: "layerPosition", container: "borderless", density: "airy", primaryVisualLanguage: "photo", secondaryVisualLanguage: "typography", whitespacePercent: 24, focalAreaPercent: 52, layerCount: 4 }, palette: { mode: "dark", background: "#111421", primary: "#F8FAFC", secondary: "#7E8CE0", accent: "#FF6B5E", surface: "#1B2033", textPrimary: "#FFFFFF" }, typographyPreset: "data", backgroundProfile: "technology", background: { intensity: "expressive", photoMode: "conditional", photoSaturation: "natural", photoOverlay: "light" }, resources: { photo: "allow", layeredComposite: "allow", threeD: "allow", typographicFocal: "allow" }, photoComposite: { mode: "preferred", visualRole: "concept", layerLogic: "heroData", styleBlend: "contrastMedia" },
      introducedIn: 7, facets: { useCases: ["campaign", "product-launch", "brand"], audiences: ["customer", "public"], moods: ["surreal", "dramatic"], media: ["photo", "3d"], industries: ["consumer", "beauty", "food", "technology"] }, distinctiveRules: ["제품 형태 보존", "한 가지 상징 장면", "제품 중심 스케일"], avoidRules: ["제품 라벨 변형", "복수 초현실 장면", "사실 정보 왜곡"],
    },
  ];
})(window);
