(function (global) {
  "use strict";
  const packs = global.PromptDeckSlideStylePresetPacks || (global.PromptDeckSlideStylePresetPacks = {});
  // Original presentation adaptations; sources and selection rationale live in docs/slide-style-trends-2026.md.
  packs.trend2026 = [
    {
      id: "calm-index-editorial", nameKo: "차분한 인덱스 에디토리얼", nameEn: "Calm Index Editorial",
      aliases: ["Explorecore", "Opt-Out Era", "조용한 편집", "인덱스 편집", "2026 트렌드"],
      description: "좁은 장 번호 열과 넓은 여백, 세리프 제목으로 자료를 차분하게 탐색하게 합니다.",
      bestFor: "연구 인사이트 · 경영 브리핑 · 정책 방향", tags: ["2026", "차분함", "인덱스", "에디토리얼"], recommended: true,
      facets: { useCases: ["report", "research", "strategy"], moods: ["calm", "refined"], media: ["typography", "photo", "data"] },
      distinctiveRules: ["좁은 세로 인덱스와 넓은 본문 영역을 분리", "세리프 제목과 산세리프 근거·캡션의 대비", "사진 한 장과 핵심 수치 한 묶음을 비대칭으로 배치"],
      avoidRules: ["여백을 채우기 위한 장식 카드 추가", "세리프 본문을 작게 압축", "핵심 자료보다 큰 무관한 사진"],
      promptKo: "차분한 인덱스 에디토리얼로 좁은 장 번호 열, 넓은 여백, 세리프 제목과 산세리프 본문을 사용한다. 본문은 한 장의 맥락 사진과 핵심 근거를 비대칭으로 연결한다. 보고서의 균등 열 배치와 달리 인덱스가 탐색을 이끌게 하며, 인덱스 번호는 실제 발표 구성에 맞춘다. 종이 질감은 빈 바탕에만 아주 약하게 사용한다.",
      promptEn: "Use a narrow numbered index rail, generous whitespace, serif headlines, and sans-serif evidence in a calm editorial composition. Connect one contextual photograph and the key evidence asymmetrically. Let the index guide navigation rather than repeating equal columns; derive its labels from the actual deck. Confine subtle paper grain to empty background areas.",
      keywords: "탐색, 여백, 인덱스, 차분함", motif: "좁은 세로 인덱스와 넓은 편집 여백",
      visual: { formality: 2, energy: 1, expression: 3, rationality: 2, geometry: 2, depth: 1 },
      composition: { grid: "indexEditorial", container: "borderless", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "indexToEvidence", surfaceLanguage: "material", primaryVisualLanguage: "typography", secondaryVisualLanguage: "photo", whitespacePercent: 36, focalAreaPercent: 46, layerCount: 2 },
      palette: { background: "#F5F1E8", surface: "#FFFCF6", primary: "#242721", secondary: "#62675A", accent: "#526446", textPrimary: "#242721", textSecondary: "#62675A", border: "#C8C8BA" },
      typography: { emphasis: "reading", headlineCharacter: "classic", hierarchyStyle: "whitespaceScale", rhythm: "airy" },
      resources: { photo: "allow", typographicFocal: "allow", threeD: "exclude", gradients: "exclude" },
      pptxGuidance: ["인덱스와 구분선은 텍스트 상자·선 도형으로 만들고 본문 그리드와 정렬한다.", "종이 질감과 사진은 별도 이미지로 두고 제목과 수치를 이미지에 굽지 않는다."],
      preview: { title: "Room to think.", kicker: "RESEARCH OUTLOOK", stat: "72%" },
    },
    {
      id: "field-notes-briefing", nameKo: "현장 메모 브리핑", nameEn: "Field Notes Briefing",
      aliases: ["Notes App Chic", "현장 기록", "필드 노트", "관찰 브리핑", "2026 트렌드"],
      description: "맥락 사진과 세부 사진, 번호를 붙인 관찰 메모를 연결해 현장의 목소리를 전달합니다.",
      bestFor: "현장 조사 · 사용자 인터뷰 · 프로젝트 회고", tags: ["2026", "기록", "사진", "손그림 주석"], recommended: true,
      facets: { useCases: ["report", "research", "story"], moods: ["human", "authentic", "warm"], media: ["photo", "typography", "illustration"] },
      distinctiveRules: ["맥락 사진과 세부 사진을 서로 다른 크기로 배치", "관찰 내용을 번호·출처와 함께 정렬", "핵심 관찰에만 손그림 밑줄·원을 제한적으로 사용"],
      avoidRules: ["모든 문장에 손글씨·스티커 사용", "연출된 사진을 실제 조사 증거로 표시", "주석이 원문이나 피사체를 가림"],
      promptKo: "현장 메모 브리핑처럼 큰 맥락 사진과 작은 세부 사진을 관찰 번호가 붙은 짧은 문장에 연결한다. 실제로 제공된 관찰과 사진 출처를 보존하고 추정과 확인 사실을 구분한다. 손그림 밑줄·원은 한두 곳의 강조에만 사용하며 본문은 정렬된 읽기 좋은 서체로 유지한다. 질감과 약간 어긋난 사진 가장자리는 기록의 촉감을 전달하는 데만 사용한다.",
      promptEn: "Connect a large contextual photo and a smaller detail photo to numbered observations in a field-notes briefing. Preserve supplied observations and photo provenance, separating interpretation from verified facts. Limit drawn underlines or circles to one or two emphasis points and keep body text aligned and legible. Use subtle grain and slightly offset photo edges only to suggest a tactile record.",
      keywords: "관찰, 현장, 기록, 주석", motif: "크기가 다른 현장 사진과 번호 관찰 메모",
      visual: { formality: 3, energy: 2, expression: 4, rationality: 2, geometry: 4, depth: 2 },
      composition: { grid: "fieldObservationPair", container: "borderless", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "photoObservation", formLanguage: "organic", surfaceLanguage: "material", primaryVisualLanguage: "photo", secondaryVisualLanguage: "typography", whitespacePercent: 24, focalAreaPercent: 53, layerCount: 3 },
      palette: { background: "#F4F0E5", surface: "#FFFBF1", primary: "#27342F", secondary: "#58634D", accent: "#A74428", textPrimary: "#27342F", textSecondary: "#626052", border: "#CEC6B4" },
      typography: { emphasis: "reading", hierarchyStyle: "imageCaption", rhythm: "airy" },
      resources: { photo: "allow", illustration: "allow", threeD: "exclude", gradients: "exclude" },
      pptxGuidance: ["메모·번호·캡션은 각각 편집 가능한 텍스트로, 밑줄과 원은 자유형 선 도형으로 작성한다.", "찢어진 가장자리와 종이 질감은 별도 장식 이미지로 분리하며 실제 현장 사진을 새 장면으로 변형하지 않는다."],
      preview: { title: "What the field revealed", kicker: "FIELD OBSERVATIONS", stat: "3 signals" },
    },
    {
      id: "soft-glass-data", nameKo: "소프트 글래스 데이터", nameEn: "Soft Glass Data",
      aliases: ["Texture Check", "촉감 데이터", "프로스티드 글래스", "유리 데이터", "2026 트렌드"],
      description: "얕은 반투명 재질 위에 수치와 차트를 또렷하게 올려 감각과 데이터 가독성을 함께 살립니다.",
      bestFor: "제품 성과 · 서비스 지표 · 기술 브리핑", tags: ["2026", "유리", "촉감", "데이터"], recommended: true,
      facets: { useCases: ["report", "product", "technology"], moods: ["clear", "sensory", "refined"], media: ["data", "3d"] },
      distinctiveRules: ["넓은 반투명 면 한 장에 핵심 수치와 차트를 결합", "얕은 굴절과 흐림은 데이터 면의 가장자리·뒤쪽에 한정", "수치·축·단위는 단색의 또렷한 글자로 유지"],
      avoidRules: ["글자 뒤의 강한 굴절과 과도한 투명도", "중첩 유리 카드·홀로그램 남발", "차트 높이·축을 장식 때문에 왜곡"],
      promptKo: "소프트 글래스 데이터 스타일로 넓고 얕은 프로스티드 면 한 장에 핵심 수치와 근거 차트를 배치한다. 유리의 흐림과 굴절은 가장자리와 뒤쪽 장식에 한정하고 데이터 면은 충분히 불투명하게 유지한다. 정보는 명료한 단색 글자와 정확한 축으로 표현하고 투명 카드 여러 개를 중첩하지 않는다.",
      promptEn: "Place one key metric and its supporting chart on a single broad, shallow frosted sheet. Confine glass blur and refraction to the sheet edges and decorative background; keep the data surface sufficiently opaque. Use crisp solid-color text and accurate chart axes, avoiding stacks of transparent cards.",
      keywords: "촉감, 굴절, 명료, 수치", motif: "프로스티드 데이터 면과 뒤쪽의 얕은 굴절",
      visual: { formality: 2, energy: 3, expression: 4, rationality: 1, geometry: 2, depth: 3 },
      composition: { grid: "singleGlassEvidence", container: "mixed", spatialRhythm: "ordered", hierarchyBehavior: "metricToChart", formLanguage: "softGeometric", surfaceLanguage: "controlledLayer", primaryVisualLanguage: "data", secondaryVisualLanguage: "none", whitespacePercent: 28, focalAreaPercent: 62, layerCount: 2 },
      palette: { background: "#EDF3FA", surface: "#F7FAFF", primary: "#172C48", secondary: "#52749B", accent: "#275AC5", textPrimary: "#172C48", textSecondary: "#52677F", border: "#B3C4DB" },
      typographyPreset: "data", typography: { emphasis: "strong", hierarchyStyle: "scaleWeight", rhythm: "airy" },
      resources: { dataVisualization: "allow", threeD: "allow", gradients: "allow", photo: "exclude" },
      pptxGuidance: ["면은 투명도가 낮은 둥근 사각형으로 구현한다. 복잡한 굴절만 별도 배경 이미지로 처리한다.", "수치와 범례는 텍스트, 차트는 원자료가 연결된 기본 차트로 작성한다. 유리 효과로 데이터 요소를 래스터화하지 않는다."],
      preview: { title: "A clearer view of progress", kicker: "PERFORMANCE SNAPSHOT", stat: "72%" },
    },
    {
      id: "retro-window-story", nameKo: "레트로 윈도 스토리", nameEn: "Retro Window Story",
      aliases: ["Prompt Playground", "레트로 컴퓨팅", "윈도 프레임", "lo-fi tech", "2026 트렌드"],
      description: "예전 컴퓨터의 창 모양을 단계별 정보 틀로 바꿔 과정과 아이디어를 경쾌하게 설명합니다.",
      bestFor: "제품 개발 · 교육 과정 · 실험·프로토타입 소개", tags: ["2026", "레트로", "윈도", "과정"],
      facets: { useCases: ["product", "education", "planning"], moods: ["playful", "nostalgic"], media: ["diagram", "typography", "ui"] },
      distinctiveRules: ["각진 창 프레임을 진행 순서에 따라 계단식으로 배치", "제목 막대에 실제 단계 이름을 표시", "창 안에는 단순한 도식과 짧은 메시지만 배치"],
      avoidRules: ["실제 앱 화면·운영체제 브랜드를 그대로 복제", "작동하지 않는 버튼·메뉴를 설명 없이 배치", "창 중첩으로 내용이나 연결선이 가려짐"],
      promptKo: "레트로 윈도 스토리로 각진 창 프레임과 짧은 제목 막대를 단계별 정보 틀로 사용한다. 실제 자료의 단계·상태를 계단식 창 배열과 단순한 연결 도식으로 설명한다. 옛 컴퓨터의 시각 언어를 차용하되 가짜 소프트웨어 화면을 만들지 않으며 본문은 현대적인 서체로 또렷하게 읽히게 한다. 겹침은 빈 프레임 영역에서만 허용한다.",
      promptEn: "Use squared window frames and compact title bars as sequential information containers. Explain the supplied stages or states with a stepped arrangement and simple connecting diagrams. Borrow early computing geometry without reproducing a real operating system or pretending to provide interactive controls. Use legible modern body type and overlap only empty frame areas.",
      keywords: "단계, 창, 레트로, 실험", motif: "제목 막대가 있는 계단식 정보 창",
      visual: { formality: 4, energy: 4, expression: 4, rationality: 2, geometry: 1, depth: 2 },
      composition: { grid: "steppedWindows", container: "mixed", spatialRhythm: "stepped", hierarchyBehavior: "stageSequence", lineLanguage: "boldOutline", surfaceLanguage: "flat", primaryVisualLanguage: "diagram", secondaryVisualLanguage: "typography", whitespacePercent: 22, focalAreaPercent: 60, layerCount: 3 },
      palette: { background: "#E7E8F5", surface: "#FFFCEF", primary: "#24263D", secondary: "#66617D", accent: "#5940B0", textPrimary: "#24263D", textSecondary: "#66617D", border: "#5B5274" },
      typography: { emphasis: "strong", hierarchyStyle: "scalePosition", rhythm: "balanced" },
      resources: { diagramInfographic: "allow", icons: "allow", typographicFocal: "allow", photo: "exclude", threeD: "exclude" },
      pptxGuidance: ["창 프레임·제목 막대·연결선은 기본 사각형과 선 도형으로 작성하고 단계별로 그룹화한다.", "모노스페이스는 짧은 제목 막대에만 사용한다. 버튼처럼 보이는 도형에 실제 인터랙션을 약속하지 않는다."],
      preview: { title: "From idea to working model", kicker: "BUILD LOG", stat: "03" },
    },
    {
      id: "cinematic-contact-sheet", nameKo: "시네마틱 콘택트 시트", nameEn: "Cinematic Contact Sheet",
      aliases: ["Drama Club", "영화 스틸", "콘택트 시트", "사진 시퀀스", "2026 트렌드"],
      description: "대표 장면과 두 개의 세부 장면을 사진 시퀀스로 엮어 장소·사람·변화를 전달합니다.",
      bestFor: "공간·사업 소개 · 브랜드 사례 · 성과 스토리", tags: ["2026", "시네마틱", "사진", "스토리"],
      facets: { useCases: ["brand", "story", "report"], moods: ["cinematic", "human", "dramatic"], media: ["photo", "typography"] },
      distinctiveRules: ["대표 장면 하나와 서로 크기가 다른 보조 장면을 연결", "장면 번호와 짧은 사실 캡션으로 서사를 형성", "사진의 색온도·명암을 통일하고 바탕은 깊은 잉크색 유지"],
      avoidRules: ["사진 전체를 동일한 카드 크기로 나열", "연출된 장면을 실제 성과나 현장 증거로 제시", "효과를 위한 과도한 레터박스·필름 구멍"],
      promptKo: "시네마틱 콘택트 시트처럼 대표 장면 하나와 두 개의 세부 장면을 비대칭 사진 시퀀스로 연결한다. 같은 맥락의 장소·사람·변화를 장면 번호와 짧은 캡션으로 읽히게 한다. 색온도와 명암의 일관성을 유지하고 사진의 실제 맥락과 인물 존엄성을 보존한다. 사진이 부족하면 장면을 임의로 만들어 사실처럼 채우지 말고 사용 가능한 자료에 맞춰 장면 수를 조정한다.",
      promptEn: "Connect one hero scene and two detail scenes in an asymmetric cinematic contact sheet. Use scene numbers and concise captions to tell a coherent story of place, people, and change. Keep color temperature and contrast consistent while preserving the real context and dignity of subjects. If photos are missing, reduce the scene count rather than fabricating evidence.",
      keywords: "장면, 사람, 변화, 시퀀스", motif: "대표 스틸과 보조 스틸 두 장의 비대칭 시퀀스",
      visual: { formality: 3, energy: 3, expression: 5, rationality: 3, geometry: 2, depth: 3 },
      composition: { grid: "contactSheetSequence", container: "borderless", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "sceneSequence", surfaceLanguage: "mattePanels", primaryVisualLanguage: "photo", secondaryVisualLanguage: "typography", whitespacePercent: 18, focalAreaPercent: 68, layerCount: 2 },
      palette: { mode: "dark", background: "#171B24", surface: "#242C37", primary: "#F4EEE3", secondary: "#BDB7AD", accent: "#D8A55C", textPrimary: "#F4EEE3", textSecondary: "#BDB7AD", border: "#535B68" },
      typography: { emphasis: "strong", headlineCharacter: "classic", hierarchyStyle: "imageCaption", rhythm: "airy" },
      resources: { photo: "allow", typographicFocal: "allow", threeD: "exclude" },
      pptxGuidance: ["장면마다 독립된 사진 개체를 사용하고 캡션·장면 번호는 별도 텍스트로 작성한다.", "주인공 얼굴과 핵심 현장이 잘리지 않게 크롭한다. 필름 효과나 모션 없이도 정적 슬라이드에서 서사가 완결되어야 한다."],
      preview: { title: "One place. Many possibilities.", kicker: "SPACE / PEOPLE / IMPACT", stat: "03" },
    },
    {
      id: "chromatic-type-story", nameKo: "대형 컬러 타이포", nameEn: "Chromatic Type Story",
      aliases: ["Zinegeist", "Zinegiest", "컬러 타이포", "대형 글자", "bold type", "2026 트렌드"],
      description: "대형 제목과 강한 색면 옆에 차분한 근거 영역을 두어 메시지와 설득을 동시에 잡습니다.",
      bestFor: "캠페인 제안 · 비전 발표 · 브랜드 키노트", tags: ["2026", "대형 타이포", "컬러 블록", "인쇄 질감"],
      facets: { useCases: ["campaign", "brand", "proposal"], moods: ["bold", "energetic", "expressive"], media: ["typography", "data"] },
      distinctiveRules: ["대형 제목을 두 개의 강한 색면과 결합", "핵심 수치와 짧은 근거는 차분한 세로 영역에 분리", "인쇄 질감은 빈 색면에만 제한적으로 사용"],
      avoidRules: ["한글 글자 폭을 강제로 압축·왜곡", "제목을 자르거나 본문까지 과도하게 확대", "색상 충돌로 수치와 단위의 가독성 저하"],
      promptKo: "대형 컬러 타이포 스타일로 짧은 핵심 제목을 큰 색면과 결합하고 옆의 차분한 근거 영역에 실제 수치와 짧은 설명을 배치한다. 제목은 자료에 맞춰 자연스럽게 줄바꿈하고 한글 자폭을 강제로 압축하거나 글자를 자르지 않는다. 인쇄 질감과 거친 밑줄은 빈 색면의 제한된 강조에만 사용한다. 본문 슬라이드에서는 제목 규모를 줄여 근거의 가독성을 확보한다.",
      promptEn: "Combine a short oversized headline with bold color fields and place real metrics and concise evidence in a calm side rail. Break lines naturally without horizontally distorting Korean glyphs or clipping letters. Restrict print grain and rough underlines to limited accents on empty fields. Reduce headline scale on content-heavy slides to preserve evidence readability.",
      keywords: "제목, 색면, 규모, 근거", motif: "두 색면을 채우는 대형 제목과 차분한 근거 열",
      visual: { formality: 4, energy: 5, expression: 5, rationality: 2, geometry: 1, depth: 1 },
      composition: { grid: "typeAndEvidenceRail", container: "borderless", spatialRhythm: "asymmetricEditorial", hierarchyBehavior: "headlineEvidence", lineLanguage: "boldAccent", surfaceLanguage: "material", primaryVisualLanguage: "typography", secondaryVisualLanguage: "data", whitespacePercent: 18, focalAreaPercent: 64, layerCount: 2 },
      palette: { background: "#FFF8E9", surface: "#FFF8E9", primary: "#2549C7", secondary: "#F3D24B", accent: "#2549C7", textPrimary: "#222A38", textSecondary: "#56606F", border: "#ABB0B8" },
      typography: { emphasis: "strong", headlineScale: "xlarge", hierarchyStyle: "scaleColor", rhythm: "balanced" },
      resources: { typographicFocal: "allow", dataVisualization: "allow", photo: "exclude", threeD: "exclude", gradients: "exclude" },
      pptxGuidance: ["제목·수치·근거는 텍스트, 색면은 기본 사각형으로 제작한다. 인쇄 질감만 별도 이미지로 분리한다.", "사용 가능한 한글 서체의 굵기와 자연스러운 줄바꿈을 사용하고 자폭을 줄여 영문 견본의 모양을 억지로 복제하지 않는다."],
      preview: { title: "MAKE IT MATTER", kicker: "IDEAS INTO ACTION", stat: "72%" },
    },
  ].map((definition) => ({
    category: "trend-2026", introducedIn: 13, presetKind: "visual", compositionProfile: "editorial", typographyPreset: "editorial",
    ...definition,
  }));
})(window);
