// 비주얼 믹서 프리셋 - 구도
(function () {
  const COMPOSITION_CATEGORIES = [
    { id: 'shot', label: '📸 숏 & 크기' },
    { id: 'angle', label: '📐 카메라 앵글' },
    { id: 'layout', label: '⚖️ 배치 & 기하학' }
  ];

  const MIXER_COMPOSITIONS = [
    { id: 'none', category: 'all', nameKo: '선택 안 함', emoji: '❌', desc: '특정한 구도를 지정하지 않고 자연스러운 배치를 사용합니다.', prefix: '', suffix: '' },
    { id: 'comp-extreme-close-up', category: 'shot', nameKo: '익스트림 클로즈업', emoji: '🔍', desc: '핵심적인 부분이나 텍스처를 화면 전체에 꽉 차게 강조하는 극접사 구도.', prefix: 'extreme close-up macro shot of', suffix: 'focusing on micro details and textures' },
    { id: 'comp-medium-shot', category: 'shot', nameKo: '미디엄 숏', emoji: '🧍', desc: '주체와 주변 배경을 조화롭게 분할하여 안정감을 주는 표준적인 구도.', prefix: 'medium shot of', suffix: 'balanced composition showing subject and environment' },
    { id: 'comp-wide-angle', category: 'shot', nameKo: '와이드 앵글 뷰', emoji: '🏞️', desc: '광활하고 웅장한 공간감을 연출하여 전체적인 스케일을 강조하는 구도.', prefix: 'wide-angle scenic shot of', suffix: 'showcasing expansive surrounding environment and grand scale' },
    { id: 'comp-knolling', category: 'shot', nameKo: '놀링 (Knolling) 배치', emoji: '🍱', desc: '모든 구성 요소를 90도 직각으로 정밀하게 정돈하여 배치하는 탑다운 뷰.', prefix: 'flat lay knolling layout of', suffix: 'neatly organized items arranged at 90-degree angles on clean background' },
    { id: 'comp-extreme-wide', category: 'shot', nameKo: '익스트림 와이드 앵글', emoji: '🌌', desc: '아주 넓은 시야각으로 거대한 주변 경관과 극적 스케일을 한눈에 보여주는 구도.', prefix: 'extreme wide-angle landscape view of', suffix: 'presenting vast scenery and tiny scale contrast' },
    { id: 'comp-macro-bokeh', category: 'shot', nameKo: '매크로 아웃포커스', emoji: '💧', desc: '미세한 질감을 접사하고 뒷배경을 환상적인 보케로 극단적으로 뭉개는 아웃포커싱 구도.', prefix: 'macro photography of', suffix: 'extreme close-up, creamy soft bokeh background, shallow depth of field' },
    { id: 'comp-panoramic', category: 'shot', nameKo: '파노라믹 가로 와이드', emoji: '🎞️', desc: '시네마스코프처럼 좌우로 길게 확장된 화면 비율을 보여주는 웅장한 가로형 시야.', prefix: 'panoramic wide aspect ratio view of', suffix: 'cinematic horizontal stretch and grand scale' },
    { id: 'comp-telescopic', category: 'shot', nameKo: '망원 압축 뷰', emoji: '🔭', desc: '망원 렌즈로 멀리 있는 피사체들을 한데 압축하여 밀도 있게 표현하는 구도.', prefix: 'telephoto lens compression view of', suffix: 'compressed background layers, distant subject detail' },
    { id: 'comp-three-quarter', category: 'shot', nameKo: '3/4 쿼터 숏', emoji: '📐', desc: '정면과 측면의 입체감이 가장 잘 드러나는 비스듬한 45도 초상/제품 촬영 구도.', prefix: 'three-quarter profile shot of', suffix: 'angled perspective, volumetric depth' },
    { id: 'comp-full-shot', category: 'shot', nameKo: '풀 뷰 숏', emoji: '🕴️', desc: '머리끝부터 발끝(혹은 사물의 전경)까지 전체를 안정적으로 다 드러내는 전신/전체 샷.', prefix: 'full shot view of', suffix: 'showing entire subject body and footprint, grounded composition' },
    { id: 'comp-head-on', category: 'shot', nameKo: '헤드 온 정면', emoji: '👁️', desc: '비스듬한 기교 없이 피사체의 정면을 똑바로 직시하여 강한 전달력을 주는 구도.', prefix: 'straightforward head-on portrait view of', suffix: 'front-facing composition, symmetrical focus' },
    { id: 'comp-pov', category: 'shot', nameKo: '1인칭 POV 시점', emoji: '👓', desc: '카메라가 시청자의 실제 눈높이가 되어 현실감을 극대화하는 1인칭 구도.', prefix: 'first-person point-of-view shot of', suffix: 'subjective camera perspective, immersive view' },
    { id: 'comp-candid', category: 'shot', nameKo: '캔디드 다큐멘터리', emoji: '📸', desc: '의식하지 않은 인위성 없는 순간을 자연스럽게 포착한 다큐멘터리 풍 숏.', prefix: 'candid capture of', suffix: 'raw documentary photojournalism style, unposed natural movement' },
    { id: 'comp-super-telephoto', category: 'shot', nameKo: '초망원 세부 크로즈업', emoji: '🧿', desc: '아주 멀리 있는 오브젝트의 핵심 영역만 도려내듯 정밀 묘사한 클로즈업.', prefix: 'super telephoto close-up of', suffix: 'sharp crisp detail from afar, flattened background' },
    { id: 'comp-low-angle', category: 'angle', nameKo: '웅장한 로우 앵글', emoji: '↗️', desc: '아래에서 올려다보는 각도로 주체를 거대하고 역동적으로 표현하는 구도.', prefix: 'low-angle heroic shot of', suffix: 'looking up to emphasize power and monumental scale' },
    { id: 'comp-high-angle', category: 'angle', nameKo: '하이 앵글', emoji: '↘️', desc: '위에서 아래로 내려다보며 전체적인 분포와 상황을 객관적으로 보여주는 구도.', prefix: 'high-angle shot of', suffix: 'looking down to reveal spatial layout and clean organization' },
    { id: 'comp-aerial', category: 'angle', nameKo: '드론 항공 뷰', emoji: '🚁', desc: '하늘 높이 솟구친 공중 시점으로 압도적인 지형지물과 스펙터클을 담는 구도.', prefix: 'aerial drone photography of', suffix: 'birdseye view presenting massive infrastructure and geographic details' },
    { id: 'comp-isometric', category: 'angle', nameKo: '아이소메트릭 뷰', emoji: '📐', desc: '30도 기울어진 각도의 등각 투영법으로 설계 도면 같은 세련미를 주는 구도.', prefix: 'isometric 3D visualization of', suffix: 'technical orthographic clean rendering style' },
    { id: 'comp-worms-eye', category: 'angle', nameKo: '웜즈 아이 로우 앵글', emoji: '🐛', desc: '바닥에 완전히 밀착하여 하늘을 우러러보듯 극적으로 왜곡된 강력한 로우 앵글.', prefix: 'worms-eye view looking straight up at', suffix: 'dramatic ground angle, monumental scale distortion' },
    { id: 'comp-birds-eye', category: 'angle', nameKo: '버즈 아이 직부감', emoji: '🦅', desc: '수직 90도 아래를 똑바로 내려다보는 완전한 탑다운 평면적 부감 구도.', prefix: "bird's-eye view looking directly down at", suffix: '90-degree vertical top-down perspective, blueprint flat layout' },
    { id: 'comp-dutch-angle', category: 'angle', nameKo: '더치 앵글 사선 투시', emoji: '🔀', desc: '지평선을 사선으로 비틀어 긴장감과 속도감, 불안정성을 연출하는 연출용 앵글.', prefix: 'dutch angle shot of', suffix: 'canted horizon tilt, dynamic unstable diagonal perspective' },
    { id: 'comp-eye-level', category: 'angle', nameKo: '아이 레벨 수평 구도', emoji: '↔️', desc: '기교 없이 수평 눈높이에서 보여주어 편안함과 정서적 교감을 유도하는 구도.', prefix: 'eye-level horizontal shot of', suffix: 'straight camera setup, natural human viewpoint' },
    { id: 'comp-ground-level', category: 'angle', nameKo: '그라운드 레벨 로우', emoji: '🛹', desc: '카메라를 지면에 스치듯이 수평으로 눕혀 속도감과 특별한 시각적 재미를 주는 앵글.', prefix: 'ground-level camera placement of', suffix: 'flat surface view, low horizon line' },
    { id: 'comp-side-profile', category: 'angle', nameKo: '측면 프로필', emoji: '👤', desc: '피사체의 정면을 배제하고 한쪽 옆모습이나 단면을 세밀하게 묘사하는 정형 구도.', prefix: 'clean side profile view of', suffix: 'lateral flat perspective, sharp silhouette lines' },
    { id: 'comp-over-shoulder', category: 'angle', nameKo: '어깨너머 오버더숄더', emoji: '👥', desc: '인물이나 오브젝트의 바로 뒷라인 어깨 너머로 대상을 관찰하듯 바라보는 시네마틱 앵글.', prefix: 'over-the-shoulder shot of', suffix: 'foreground framing element, contextual depth layer' },
    { id: 'comp-three-quarter-top', category: 'angle', nameKo: '3쿼터 탑다운', emoji: '📈', desc: '사선 위쪽에서 내려다보며 사물의 두 옆면과 윗면을 입체적으로 모두 포착하는 구도.', prefix: 'three-quarter high-angle shot of', suffix: 'technical product preview angle' },
    { id: 'comp-fisheye', category: 'angle', nameKo: '어안 렌즈 볼록 굴절', emoji: '🌀', desc: '180도 광각 돔 렌즈 효과로 중심은 볼록하고 주변은 둥글게 휘는 왜곡 앵글.', prefix: 'fisheye lens distortion of', suffix: 'ultra-wide circular 180-degree wrap around view' },
    { id: 'comp-low-angle-silhouette', category: 'angle', nameKo: '로우 앵글 실루엣', emoji: '👥', desc: '역광 상태에서 로우 앵글로 촬영하여 주체의 드라마틱한 윤곽 실루엣을 부각하는 구도.', prefix: 'backlit low-angle silhouette of', suffix: 'stark shadow outline, dramatic sky background' },
    { id: 'comp-rule-of-thirds', category: 'layout', nameKo: '3분할 구도', emoji: '🕸️', desc: '화면을 가로/세로 3등분한 교차점에 주요 요소를 매끄럽게 결합하는 구도.', prefix: 'rule of thirds composition of', suffix: 'asymmetric focal points creating dynamic visual balance' },
    { id: 'comp-symmetry', category: 'layout', nameKo: '데칼코마니 대칭', emoji: '⚖️', desc: '좌우 혹은 상하가 완벽하게 일치하여 시각적 절대 안정과 몰입을 주는 구도.', prefix: 'perfectly symmetrical reflection of', suffix: 'centered composition, high graphical stability and reflection mapping' },
    { id: 'comp-spiral', category: 'layout', nameKo: '피보나치 나선', emoji: '🌀', desc: '황금 비율 나선 궤적을 따라 시선이 안쪽으로 빨려 들어가는 몰입형 구도.', prefix: 'golden ratio fibonacci spiral composition of', suffix: 'curved leading lines pulling the eye to the central focus' },
    { id: 'comp-framing', category: 'layout', nameKo: '프레임 인 프레임', emoji: '🖼️', desc: '창문, 틈새, 문틀 등 내부 프레임을 통해 피사체를 한 번 더 감싸는 구조.', prefix: 'framed view of', suffix: 'looking through a clean architectural frame, depth of field layers' },
    { id: 'comp-copy-left', category: 'layout', nameKo: '좌측 텍스트 여백', emoji: '⬅️', desc: '슬라이드 타이틀을 얹기 좋게 좌측 절반의 배경을 완전한 빈 여백으로 유도하는 배치.', prefix: 'asymmetric composition with', suffix: 'optimized with large clean copy-space on the left third of the image' },
    { id: 'comp-copy-right', category: 'layout', nameKo: '우측 텍스트 여백', emoji: '➡️', desc: '텍스트 본문이나 로고를 얹기 좋게 우측 영역을 심플하게 비워두는 배치.', prefix: 'asymmetric composition with', suffix: 'optimized with large clean copy-space on the right third of the image' },
    { id: 'comp-centered-focus', category: 'layout', nameKo: '중앙 집중형 프레임', emoji: '🎯', desc: '불필요한 분산 요소 없이 가장 중요한 대상을 정중앙에 배치해 시선을 고정하는 레이아웃.', prefix: 'dead-center composition of', suffix: 'focused singular focal point, high impact symmetry, clean background' },
    { id: 'comp-diagonals', category: 'layout', nameKo: '대각선 소실점', emoji: '↗️', desc: '대각선 방향으로 뻗어 나가는 강한 가이드라인을 배치해 역동적 속도감을 주는 구도.', prefix: 'strong diagonal composition of', suffix: 'dynamic leading lines stretching across the canvas, forced perspective' },
    { id: 'comp-triangular', category: 'layout', nameKo: '삼각형 피라미드', emoji: '🔺', desc: '하단을 넓게 하고 위로 모아주는 피라미드식 기하학 배치로 압도적인 안정감을 주는 구도.', prefix: 'triangular composition layout of', suffix: 'stable pyramid structures, broad base visual anchor' },
    { id: 'comp-thirds-offset', category: 'layout', nameKo: '황금 삼분할 교차', emoji: '🏁', desc: '황금 분할 교차점 중 하나로 대상을 강하게 오프셋하여 시각적 세련미를 높이는 비대칭 구도.', prefix: 'strongly offset rule of thirds composition of', suffix: 'asymmetric balanced spacing, artistic off-center focus' },
    { id: 'comp-layered-framing', category: 'layout', nameKo: '다중 액자식 구성', emoji: '🔳', desc: '전경의 아웃포커스된 틈새를 거쳐 중경, 배경까지 다층 프레임으로 엮은 구조적 구도.', prefix: 'layered multi-frame perspective of', suffix: 'peek-through foreground, volumetric framing, deep depth of field' },
    { id: 'comp-radial', category: 'layout', nameKo: '방사형 확산', emoji: '🔆', desc: '중앙의 핵심 소실점으로부터 사방으로 선이나 오브젝트가 방사형으로 뿜어 나오는 구도.', prefix: 'radial layout of', suffix: 'explosion lines radiating outward from the visual core, centered focal burst' },
    { id: 'comp-floating-suspension', category: 'layout', nameKo: '플로팅 공중 부양', emoji: '🎈', desc: '오브젝트가 중력을 무시하고 가볍게 둥둥 떠 있는 트렌디한 제품 레이아웃.', prefix: 'gravity-defying floating mockup layout of', suffix: 'suspended objects in mid-air with soft cast shadows, minimalist backdrop' },
    { id: 'comp-split', category: 'layout', nameKo: '수직 이분할 (50:50)', emoji: '🌓', desc: '화면을 수직 또는 수평으로 칼같이 50:50으로 나누는 극단적인 그래픽 구도.', prefix: '50-50 split screen composition of', suffix: 'perfect visual dichotomy, color block division, high symmetry' },

    // 숏 (shot) 추가 8종
    { id: 'comp-tilt-shift', category: 'shot', nameKo: '틸트 시프트 미니어처', emoji: '🏙️', desc: '카메라 틸트-시프트 렌즈로 실제 장면을 미니어처 모형처럼 보이게 만드는 착시 구도.', prefix: 'tilt-shift miniature effect photograph of', suffix: 'selective focus band creating miniature diorama illusion, defocused top and bottom' },
    { id: 'comp-double-exposure', category: 'shot', nameKo: '이중 노출 고스트', emoji: '👻', desc: '두 개의 이미지를 겹쳐 신비로운 고스트 이중 노출 효과를 만드는 예술적 촬영 기법.', prefix: 'double exposure composite of', suffix: 'two images blended in ghostly overlay, dreamlike merged silhouette' },
    { id: 'comp-underwater', category: 'shot', nameKo: '수중 투시', emoji: '🤿', desc: '수면 아래에서 바라본 수중 투시 구도. 굴절된 빛 줄기와 물결 텍스처가 독특한 공간감을 만든다.', prefix: 'underwater perspective shot of', suffix: 'light refracting through water surface, caustic light patterns, aquatic visual depth' },
    { id: 'comp-reflection-mirror', category: 'shot', nameKo: '거울·수면 반사', emoji: '🪞', desc: '완벽한 수면 반사나 거울 반영을 활용해 상하 대칭의 몽환적 공간을 만드는 구도.', prefix: 'perfect mirror reflection composition of', suffix: 'subject and its reflection creating surreal symmetrical world, glassy water or mirror surface' },
    { id: 'comp-zoom-burst', category: 'shot', nameKo: '줌 버스트 방사', emoji: '💫', desc: '노출 중 줌 인/아웃으로 광선이 중심에서 방사형으로 폭발하는 역동적 줌 버스트 효과.', prefix: 'zoom burst exposure effect of', suffix: 'radial light streaks exploding outward from center, energetic speed of light effect' },
    { id: 'comp-split-diopter', category: 'shot', nameKo: '스플릿 딥터 듀얼 포커스', emoji: '🎭', desc: '화면을 두 영역으로 나눠 근거리와 원거리를 동시에 선명하게 잡는 스플릿 딥터 렌즈 구도.', prefix: 'split diopter dual focus shot of', suffix: 'both near and far subjects in sharp focus simultaneously, split screen depth illusion' },
    { id: 'comp-motion-freeze', category: 'shot', nameKo: '순간 포착 모션 프리즈', emoji: '⚡', desc: '고속 셔터로 물방울·먼지·불꽃이 공중에 정지된 순간을 포착한 극적인 하이스피드 프리즈.', prefix: 'high-speed frozen motion capture of', suffix: 'suspended particles or droplets frozen in mid-air, split-second temporal freeze' },
    { id: 'comp-detail-cutaway', category: 'shot', nameKo: '단면 절개 클로즈업', emoji: '🔬', desc: '오브젝트의 내부 단면이나 해부된 구조를 클로즈업으로 드러내는 기술·과학적 절개 구도.', prefix: 'technical cutaway cross-section closeup of', suffix: 'revealing internal structure and layers, scientific dissection visual clarity' },

    // 앵글 (angle) 추가 8종
    { id: 'comp-rear-view', category: 'angle', nameKo: '피사체 후면 백뷰', emoji: '🔙', desc: '피사체 뒤에서 같은 방향으로 바라보는 리어뷰 앵글. 피사체와 관객이 같은 시선을 공유하는 공감형 구도.', prefix: 'rear view following perspective of', suffix: 'shooting from behind subject looking in the same direction, shared point of view' },
    { id: 'comp-orbit-wrap', category: 'angle', nameKo: '오비트 랩어라운드', emoji: '🔄', desc: '카메라가 피사체 주변을 360° 공전하듯 감싸는 오비트 앵글. 입체적 공간 관계와 전체 형태를 드러낸다.', prefix: 'orbiting wrap-around angle of', suffix: '360 degree orbit perspective revealing full spatial relationship and form' },
    { id: 'comp-three-quarter-low', category: 'angle', nameKo: '3쿼터 로우 앵글', emoji: '📐', desc: '아래쪽에서 45° 비스듬히 올려다보는 3쿼터 로우 앵글. 피사체에 압도적 존재감과 권위를 부여한다.', prefix: 'three-quarter low angle upward shot of', suffix: 'camera below eye level tilted up at 45 degrees, dominant imposing presence' },
    { id: 'comp-environmental-portrait', category: 'angle', nameKo: '환경 초상 구도', emoji: '🌍', desc: '피사체를 그 삶의 맥락과 환경 속에 배치해 인물과 공간의 관계를 동시에 담아내는 환경 초상 구도.', prefix: 'environmental portrait angle of', suffix: 'subject placed within their natural environment and context, relationship between person and space' },
    { id: 'comp-steep-oblique', category: 'angle', nameKo: '급각 사선 오블리크', emoji: '🛩️', desc: '거의 수직에 가깝게 내려다보며 동시에 방향 사선이 있는 급각 오블리크 앵글. 지도식 조감과 원근감을 동시에 준다.', prefix: 'steep oblique aerial angle of', suffix: 'nearly vertical downward gaze with directional diagonal, cartographic bird\'s-eye with forced perspective' },
    { id: 'comp-under-surface', category: 'angle', nameKo: '밑면 언더 앵글', emoji: '⬇️', desc: '유리 바닥 아래나 수면 아래에서 완전히 수직으로 올려다보는 극단적 언더 앵글.', prefix: 'under-surface looking straight up angle of', suffix: 'camera directly below the subject looking upward through glass or water, extreme underbelly perspective' },
    { id: 'comp-telephoto-flat', category: 'angle', nameKo: '망원 원근 압축', emoji: '🔭', desc: '초망원 렌즈로 원근감을 극도로 압축해 앞·뒤 요소가 동일 평면에 붙어 보이는 스택 앵글.', prefix: 'super telephoto compressed perspective of', suffix: 'extreme focal length flattening depth, background and foreground elements stacked on same plane' },
    { id: 'comp-corner-peek', category: 'angle', nameKo: '코너 피크 엿보기', emoji: '👁️', desc: '건물 모서리, 벽, 문틀 가장자리 뒤에서 살짝 엿보는 서스펜스 앵글.', prefix: 'peek-around corner candid angle of', suffix: 'partially hidden by edge or corner, voyeuristic suspense angle, natural surveillance framing' },

    // 레이아웃 (layout) 추가 8종
    { id: 'comp-z-pattern', category: 'layout', nameKo: 'Z형 시선 흐름', emoji: '↩️', desc: '시선이 좌상→우상→좌하→우하로 Z자를 그리며 이동하도록 유도하는 레이아웃.', prefix: 'Z-pattern reading flow layout of', suffix: 'visual elements arranged to guide the eye in a Z-path across the frame, editorial flow composition' },
    { id: 'comp-negative-space', category: 'layout', nameKo: '네거티브 스페이스 여백', emoji: '◻️', desc: '피사체보다 빈 공간을 훨씬 크게 남겨 여백 자체가 구도를 지배하는 고급 미니멀 레이아웃.', prefix: 'dominant negative space minimal layout of', suffix: 'subject occupies small portion of frame, vast intentional empty space creating breathing room and tension' },
    { id: 'comp-s-curve-flow', category: 'layout', nameKo: 'S 커브 시선 흐름', emoji: '〰️', desc: '뱀처럼 구불구불 S자를 그리는 곡선 요소가 화면 전체를 흐르며 유기적인 생동감을 부여하는 구도.', prefix: 'S-curve leading line composition of', suffix: 'sinuous S-shaped visual flow path guiding the eye through the entire frame, organic dynamic rhythm' },
    { id: 'comp-cross-grid', category: 'layout', nameKo: '십자형 교차 구성', emoji: '✚', desc: '수직선과 수평선이 교차하는 십자 구조로 화면을 구획하는 강한 건축적 레이아웃.', prefix: 'cross-grid structural composition of', suffix: 'strong vertical and horizontal lines intersecting, architectural division creating four quadrants' },
    { id: 'comp-triptych', category: 'layout', nameKo: '세 폭 분할 트립틱', emoji: '🔛', desc: '화면을 세 패널로 균등 분할해 같은 주제의 다른 관점이나 시퀀스를 병렬 배치하는 3폭 구성.', prefix: 'triptych three-panel composition of', suffix: 'frame divided into three equal panels showing different views or sequences side by side' },
    { id: 'comp-horizontal-band', category: 'layout', nameKo: '수평 밴드 레이어', emoji: '🌅', desc: '하늘·중경·전경을 수평 띠로 명확하게 구분하는 지평선 강조 밴드 레이아웃. 파노라마적 안정감.', prefix: 'horizontal banding layered composition of', suffix: 'distinct horizontal color bands from foreground to sky, layered strata composition, panoramic stability' },
    { id: 'comp-staggered-grid', category: 'layout', nameKo: '어긋난 오프셋 그리드', emoji: '🔲', desc: '격자 배치에서 행마다 절반씩 어긋나게 오프셋하는 벽돌쌓기식 역동적 그리드 레이아웃.', prefix: 'staggered offset grid layout of', suffix: 'brick-pattern offset rows creating dynamic interlocking rhythm, alternating shifted grid modules' },
    { id: 'comp-cluster-scatter', category: 'layout', nameKo: '클러스터 분산 군집', emoji: '🌌', desc: '오브젝트들이 화면 이곳저곳에 밀도 차이를 두며 유기적으로 산포되는 군집 레이아웃.', prefix: 'clustered scatter arrangement of', suffix: 'organic groupings of elements at varying densities scattered across frame, constellation-like distribution' }
  ];

  const MIXER_COMPOSITION_SAMPLES = {
    'comp-extreme-close-up': 'photo-1502082553048-f009c37129b9',
    'comp-medium-shot': 'photo-1534528741775-53994a69daeb',
    'comp-wide-angle': 'photo-1470071459604-3b5ec3a7fe05',
    'comp-knolling': 'photo-1506784983877-45594efa4cbe',
    'comp-low-angle': 'photo-1486406146926-c627a92ad1ab',
    'comp-high-angle': 'photo-1522071820081-009f0129c71c',
    'comp-aerial': 'photo-1473442240418-452f03b7ae40',
    'comp-isometric': 'photo-1541701494587-cb58502866ab',
    'comp-rule-of-thirds': 'photo-1500485035595-cbe6f645feb1',
    'comp-symmetry': 'photo-1439853949127-fa647821eba0',
    'comp-spiral': 'photo-1513002749550-c59d786b8e6c',
    'comp-framing': 'photo-1469854523086-cc02fe5d8800',
    'comp-extreme-wide': 'photo-1472214222541-d510753a49df',
    'comp-macro-bokeh': 'photo-1555597673-b21d5c935865',
    'comp-panoramic': 'photo-1464822759023-fed622ff2c3b',
    'comp-telescopic': 'photo-1516426122078-c23e76319801',
    'comp-three-quarter': 'photo-1506794778202-cad84cf45f1d',
    'comp-full-shot': 'photo-1509631179647-0177331693ae',
    'comp-head-on': 'photo-1544005313-94ddf0286df2',
    'comp-pov': 'photo-1517245386807-bb43f82c33c4',
    'comp-candid': 'photo-1511671782779-c97d3d27a1d4',
    'comp-super-telephoto': 'photo-1447752875215-b2761acb3c5d',
    'comp-worms-eye': 'photo-1509198397868-475647b2a1e5',
    'comp-birds-eye': 'photo-1504608524841-42fe6f032b4b',
    'comp-dutch-angle': 'photo-1536440136628-849c177e76a1',
    'comp-eye-level': 'photo-1500648767791-00dcc994a43e',
    'comp-ground-level': 'photo-1551698618-1ffd5f97d728',
    'comp-side-profile': 'photo-1500648767791-00dcc994a43e',
    'comp-over-shoulder': 'photo-1522075469751-3a6694fb2f61',
    'comp-three-quarter-top': 'photo-1505740420928-5e560c06d30e',
    'comp-fisheye': 'photo-1516035069371-29a1b244cc32',
    'comp-low-angle-silhouette': 'photo-1502082553048-f009c37129b9',
    'comp-copy-left': 'photo-1486312338219-ce68d2c6f44d',
    'comp-copy-right': 'photo-1513542789411-b6a5d4f31634',
    'comp-centered-focus': 'photo-1518709268805-4e9042af9f23',
    'comp-diagonals': 'photo-1519074069444-1ba4ae167512',
    'comp-triangular': 'photo-1513694203232-719a280e022f',
    'comp-thirds-offset': 'photo-1518005020951-eccb494ad742',
    'comp-layered-framing': 'photo-1449034446853-66c86144b0ad',
    'comp-radial': 'photo-1507525428034-b723cf961d3e',
    'comp-floating-suspension': 'photo-1618005182384-a83a8bd57fbe',
    'comp-split': 'photo-1513829092301-a72c4eb04300',

    // shot 추가 8종
    'comp-tilt-shift':             'photo-1477959858617-67f85cf4f1df',
    'comp-double-exposure':        'photo-1508739773434-c26b3d09e071',
    'comp-underwater':             'photo-1503803548695-c2a7b4a5b875',
    'comp-reflection-mirror':      'photo-1501630834273-4b5604d2ee31',
    'comp-zoom-burst':             'photo-1533073526757-2c8ca1df9f1d',
    'comp-split-diopter':          'photo-1559827260-dc66d52bef19',
    'comp-motion-freeze':          'photo-1504701954957-2010ec3bcec1',
    'comp-detail-cutaway':         'photo-1533749047139-189de3cf06d3',

    // angle 추가 8종
    'comp-rear-view':              'photo-1507003211169-0a1dd7228f2d',
    'comp-orbit-wrap':             'photo-1534430480872-3498386e7856',
    'comp-three-quarter-low':      'photo-1486406146926-c627a92ad1ab',
    'comp-environmental-portrait': 'photo-1556157382-97eda2d62296',
    'comp-steep-oblique':          'photo-1473442240418-452f03b7ae40',
    'comp-under-surface':          'photo-1527482937786-6608f6e14c15',
    'comp-telephoto-flat':         'photo-1551135049-8a33b5883817',
    'comp-corner-peek':            'photo-1499678329028-101435549a4e',

    // layout 추가 8종
    'comp-z-pattern':              'photo-1486312338219-ce68d2c6f44d',
    'comp-negative-space':         'photo-1559494007-9f5847c49d94',
    'comp-s-curve-flow':           'photo-1441974231531-c6227db76b6e',
    'comp-cross-grid':             'photo-1448630360428-65456885c650',
    'comp-triptych':               'photo-1509198397868-475647b2a1e5',
    'comp-horizontal-band':        'photo-1464822759023-fed622ff2c3b',
    'comp-staggered-grid':         'photo-1518005020951-eccb494ad742',
    'comp-cluster-scatter':        'photo-1535380210974-fba9d0462c27'
  };

  Object.assign(window.CONCEPT_MIXER_PRESETS, {
    COMPOSITION_CATEGORIES,
    MIXER_COMPOSITIONS,
    MIXER_COMPOSITION_SAMPLES,
  });
})();
