// 홍보용 이미지 생성 탭 — 순수 데이터 상수
// promotion.js 보다 먼저 로드되어야 합니다.

window.PROMO_DATA = (function () {
  const PROMOTION_SCHEMA_VERSION = 1;
  const PROMOTION_DRAFT_STORAGE_KEY = "promptdeck-promotion-draft-v1";
  const PROMOTION_COLOR_PRESETS_KEY = "promptdeck-promotion-color-presets-v1";
  const PROMOTION_SIZE_PRESETS_KEY = "promptdeck-promotion-size-presets-v1";
  const ASSET_TYPES = ["image"];
  const CONTENT_TYPE_VALUES = ["none", "campaign", "result-promo", "event-info", "survey-request", "training-info", "biz-promo"];
  const COLOR_STRATEGY_VALUES = ["manual", "ai"];

  const ASSET_DEFAULTS = {
    image: {
      contentType: "event-info",
      sizeMode: "ratio",
      ratio: "4:5",
      orientation: "vertical",
      directSizeUnit: "px",
      directSizeW: "",
      directSizeH: "",
      customRatioW: "",
      customRatioH: "",
    },
  };

  const DEFAULT_STATE = {
    assetType: "image",
    contentType: "none",
    outputLanguage: "ko",
    promptMode: "review",
    visualPlanningMode: "basic",
    targetEngine: "dalle",
    omitEmptyFields: "true",
    dedupePromptLines: "true",
    autoResolveConflicts: "true",
    commercialBaseline: "premium",
    creativityLevel: "balanced",
    sizeMode: "ratio",
    ratio: "4:5",
    orientation: "vertical",
    customRatioW: "",
    customRatioH: "",
    directSizeUnit: "px",
    directSizeW: "",
    directSizeH: "",
    goal: "",
    audience: "",
    headline: "",
    subheadline: "",
    bodyCopy: "",
    cta: "",
    tone: "",
    toneEnabled: "true",
    toneMode: "ai",
    visualStyle: "",
    visualStyleEnabled: "true",
    visualStyleMode: "ai",
    antiAiStyle: "general",
    qualityNotes: "",
    colorStrategy: "ai",
    colorMode: "light",
    primaryColor: "",
    secondaryColor: "",
    accentColor: "",
    backgroundMode: "solid",
    backgroundColor: "",
    backgroundDetails: "",
    mandatoryElements: "",
    forbiddenElements: "이모지 사용 금지",
    posterKeyVisual: "",
    posterKeyVisualEnabled: "false",
    posterInfoLayout: "",
    posterInfoLayoutEnabled: "false",
    posterOffer: "",
    posterOfferEnabled: "true",
    posterOfferMode: "ai",
    snsHook: "",
    snsHookEnabled: "true",
    snsHookMode: "ai",
    snsHashtags: "",
    snsHashtagsEnabled: "true",
    snsHashtagsMode: "ai",
    snsVisualFocus: "",
    snsVisualFocusEnabled: "false",
    snsPlacementNotes: "",
    snsPlacementNotesEnabled: "false",
    ctaEnabled: "true",
    ctaMode: "ai",
    qrEnabled: "false",
    qrUrl: "",
    bigIdea: "",
    bigIdeaEnabled: "true",
    bigIdeaMode: "ai",
    visualMetaphor: "",
    visualMetaphorEnabled: "true",
    visualMetaphorMode: "ai",
    variationMode: "none",
    keyVisualPlacement: "auto",
    layoutComposition: "centered",
    layoutCompositionEnabled: "true",
    layoutCompositionMode: "ai",
    appliedConceptStyle: "",
    appliedConceptName: "",
    appliedConceptCategory: "",
    appliedConceptEmoji: "",
    appliedConceptPalette: "",
    appliedConceptDesc: "",
    appliedConceptTags: "",
    appliedConceptPromotionPrompt: "",
    appliedConceptVisualDNA: "",
    appliedConceptPaletteStrategy: "",
    appliedConceptTextureRendering: "",
    appliedConceptLightingMood: "",
    appliedConceptShapeLanguage: "",
    appliedConceptLayoutBehavior: "",
    appliedConceptTypographyGuidance: "",
    appliedConceptCampaignAdaptation: "",
    appliedConceptObjectAdaptation: "",
    appliedConceptAvoid: "",
    appliedConceptQualityRules: "",
    conceptInfluenceMode: "strong",
  };

  const ASSET_LABELS = {
    image: "홍보 이미지",
  };

  const ASSET_LABELS_EN = {
    image: "promotion image",
  };

  const ASSET_PROMPT_TARGET_EN = {
    image: "promotion image",
  };

  const KIND_META = {
    visible: { label: "이미지 텍스트", className: "visible" },
    instruction: { label: "설계 지시", className: "instruction" },
    constraint: { label: "구성 조건", className: "constraint" },
  };

  const STATIC_FIELD_KINDS = {
    promotionContentType: "constraint",
    promotionOutputLanguage: "constraint",
    promotionPromptMode: "constraint",
    promotionOmitEmptyFields: "constraint",
    promotionDedupePromptLines: "constraint",
    promotionAutoResolveConflicts: "constraint",
    promotionCommercialBaseline: "constraint",
    promotionCreativityLevel: "constraint",
    promotionVariationModeToggle: "constraint",
    promotionSizeMode: "constraint",
    promotionRatio: "constraint",
    promotionOrientation: "constraint",
    promotionCustomRatioW: "constraint",
    promotionCustomRatioH: "constraint",
    promotionDirectSizeUnit: "constraint",
    promotionDirectSizeW: "constraint",
    promotionDirectSizeH: "constraint",
    promotionGoal: "instruction",
    promotionAudience: "instruction",
    promotionHeadline: "visible",
    promotionSubheadline: "visible",
    promotionBodyCopy: "visible",
    promotionCta: "visible",
    promotionQrEnabled: "constraint",
    promotionQrUrl: "instruction",
    promotionTone: "instruction",
    promotionVisualStyle: "instruction",
    promotionQualityNotes: "instruction",
    promotionBigIdea: "instruction",
    promotionVisualMetaphor: "instruction",
    promotionColorStrategy: "constraint",
    promotionPrimaryColor: "constraint",
    promotionSecondaryColor: "constraint",
    promotionAccentColor: "constraint",
    promotionBackgroundMode: "constraint",
    promotionBackgroundColor: "constraint",
    promotionBackgroundDetails: "instruction",
    promotionMandatoryElements: "visible",
    promotionForbiddenElements: "instruction",
  };

  const FIELD_LABELS = {
    contentType: "컨텐츠 유형",
    outputLanguage: "프롬프트 언어",
    promptMode: "출력 모드",
    omitEmptyFields: "빈 항목 자동 제거",
    dedupePromptLines: "중복 문구 제거",
    autoResolveConflicts: "상충 규칙 자동 정리",
    commercialBaseline: "상업 완성도 기준",
    creativityLevel: "구성 실험 강도",
    variationMode: "다양성 변형 지시",
    keyVisualPlacement: "키비주얼 배치",
    sizeMode: "규격 입력 방식",
    ratio: "비율",
    orientation: "방향",
    customRatioW: "사용자 비율(W)",
    customRatioH: "사용자 비율(H)",
    directSize: "직접 입력 크기",
    directSizeUnit: "직접 입력 단위",
    directSizeW: "너비",
    directSizeH: "높이",
    goal: "홍보 목적",
    audience: "핵심 타깃",
    headline: "헤드라인",
    subheadline: "서브 카피",
    bodyCopy: "본문 포인트",
    cta: "엑션버튼(CTA)",
    qrEnabled: "QR코드 사용 여부",
    qrUrl: "QR코드 연결 주소",
    tone: "브랜드 톤",
    visualStyle: "비주얼 스타일",
    antiAiStyle: "AI 느낌 억제",
    qualityNotes: "결과물 결함 방지",
    colorStrategy: "색상 전략",
    bigIdea: "Big Idea",
    visualMetaphor: "비주얼 은유",
    primaryColor: "메인 색상",
    secondaryColor: "보조 색상",
    accentColor: "포인트 색상",
    backgroundMode: "배경 처리 방식",
    backgroundColor: "배경 색상",
    backgroundDetails: "배경 패턴/이미지 지시",
    mandatoryElements: "반드시 포함할 요소",
    forbiddenElements: "피해야 할 요소",
    posterKeyVisual: "메인 비주얼 포인트",
    posterInfoLayout: "정보 배치 방식",
    posterOffer: "한 줄 오퍼",
    snsHook: "첫 줄 훅",
    snsHashtags: "해시태그/태그",
    snsVisualFocus: "SNS 비주얼 중심 포인트",
    snsPlacementNotes: "배치 메모",
  };

  const FIELD_LABELS_EN = {
    contentType: "content template",
    outputLanguage: "prompt language",
    promptMode: "output mode",
    omitEmptyFields: "auto-remove empty fields",
    dedupePromptLines: "remove duplicate prompt lines",
    autoResolveConflicts: "auto-resolve conflicting rules",
    commercialBaseline: "commercial baseline",
    creativityLevel: "creativity level",
    variationMode: "variation directive",
    keyVisualPlacement: "key visual placement",
    sizeMode: "sizing mode",
    ratio: "aspect ratio",
    orientation: "orientation",
    customRatioW: "custom ratio width",
    customRatioH: "custom ratio height",
    directSize: "exact size",
    directSizeUnit: "size unit",
    directSizeW: "width",
    directSizeH: "height",
    goal: "promotion goal",
    audience: "target audience",
    headline: "headline",
    subheadline: "sub copy",
    bodyCopy: "body points",
    cta: "action button (CTA)",
    qrEnabled: "QR code usage",
    qrUrl: "QR code target URL",
    tone: "brand tone",
    visualStyle: "visual style",
    antiAiStyle: "anti-AI style preset",
    qualityNotes: "quality refinements",
    colorStrategy: "color strategy",
    bigIdea: "big idea",
    visualMetaphor: "visual metaphor",
    primaryColor: "primary color",
    secondaryColor: "secondary color",
    accentColor: "accent color",
    backgroundMode: "background treatment",
    backgroundColor: "background color",
    backgroundDetails: "background pattern/image guidance",
    mandatoryElements: "must-include elements",
    forbiddenElements: "elements to avoid",
    posterKeyVisual: "main visual focal point",
    posterInfoLayout: "information layout",
    posterOffer: "single-line offer",
    snsHook: "opening hook",
    snsHashtags: "hashtags/tags",
    snsVisualFocus: "SNS visual focal point",
    snsPlacementNotes: "placement notes",
  };

  const QUICK_BTNS = {
    tone: [
      "신뢰감 있는",
      "대담한",
      "임팩트 있는",
      "전문적인",
      "세련된",
      "친근한",
      "역동적인",
      "모던한",
      "미니멀한",
      "따뜻한",
      "스마트한",
      "브랜드 광고 같은",
    ],
    visualStyle: [
      "실사 위주",
      "3D 그래픽",
      "대담한 타이포그래피",
      "네온 무드",
      "파스텔 톤",
      "플랫 디자인",
      "글래스모피즘",
      "매거진 편집형",
      "브랜드 포스터형",
      "인포그래픽형",
      "미니멀 그리드형",
      "하이엔드 제품광고형",
      "캠페인 광고형",
      "데이터 중심 레이아웃",
      "에디토리얼 광고형",
    ],
    qualityNotes: [
      "광고 이미지급 디테일",
      "텍스트와 배경 대비 선명",
      "모바일 썸네일 가독성 우선",
      "노이즈 없는 깨끗한 표면",
      "타이포 가장자리 또렷하게",
      "브랜드 색상 정확도 유지",
      "텍스트 외곽선 없이 선명하게",
      "CTA 버튼 한눈에 읽히게",
      "인물과 배경 경계 또렷하게",
      "저해상도 스톡 느낌 금지",
    ],
    backgroundDetails: [
      "은은한 그리드 패턴",
      "기하학 라인 패턴",
      "제품 질감 배경 이미지",
      "도시 야경 블러 배경",
      "메탈 텍스처 배경",
      "그라데이션 배경 위 미세 노이즈",
      "딥 네이비 그라데이션 배경",
      "텍스트 영역만 어둡게 오버레이",
      "현장 사진 흐림 처리 배경",
      "추상 광원 오버레이",
    ],
    visualPoint: [
      "중앙 히어로 제품",
      "금속 질감 배경",
      "기하학적 패턴",
      "인물 클로즈업",
      "자연 풍경",
      "데이터 시각화",
      "추상적 그래픽",
      "오른쪽 인물, 왼쪽 헤드라인",
      "대형 헤드라인과 단일 오브젝트",
      "상단 타이포, 하단 정보 카드",
    ],
    infoLayout: [
      "좌측 텍스트 강조, 우측 비주얼 배치",
      "상단 헤드라인 고정",
      "중앙 집중형",
      "그리드 분할",
      "하단 정보 박스 일체형",
      "상단 훅, 중단 핵심, 하단 CTA",
      "Z자 흐름",
      "여백 강조",
      "좌측 정렬축 통일",
      "정보 카드 1개로 묶기",
    ],
    cardnewsFlow: [
      "문제 인식 → 핵심 데이터 → 해결안 → CTA",
      "질문 → 오해 바로잡기 → 사례 → CTA",
      "혜택 요약 → 세부 포인트 → 일정 → CTA",
      "후킹 문장 → 핵심 사실 3개 → 신청 안내",
      "공감 문제 제시 → 전환 포인트 → 행동 유도",
    ],
    snsVisualFocus: [
      "제품 중심",
      "인물 중심",
      "타이포 중심",
      "정보카드 중심",
      "배경 무드 중심",
      "CTA 버튼 중심",
      "헤드라인과 CTA 이중 강조",
      "인물 반신과 큰 제목 중심",
    ],
    snsPlacement: [
      "상단 25% 훅 카피",
      "중앙 비주얼 중심",
      "하단 CTA 버튼 영역 분리",
      "안전영역 침범 금지",
      "좌측 상단 로고 고정",
      "우측 하단 CTA 배지",
      "텍스트 블록 2개 이하 유지",
      "스티커/링크 영역과 12% 이상 간격",
      "헤드라인과 배경 대비 강하게",
      "썸네일 축소 시도 가독성 유지",
      "상하단 UI 영역 피해 배치",
      "왼쪽 정렬축 유지",
    ],
    bigIdea: [
      "참여",
      "성장",
      "신뢰",
      "변화",
      "연결",
      "혁신",
      "소통",
    ],
    visualMetaphor: [
      "상승 곡선",
      "빛의 경로",
      "확산하는 물결",
      "맞물린 기어",
      "정렬된 큐브",
      "열린 프레임",
      "겹치는 레이어",
    ],
  };

  const DEFAULT_QUALITY_TAGS = {
    ko: [
      "광고 이미지급 고해상도 품질, 4K 초정밀 디테일",
      "텍스트와 배경 대비 선명",
      "텍스트 가장자리 또렷함",
      "픽셀 깨짐 없음",
      "썸네일 축소 시에도 핵심 문구 가독성 유지",
      "작은 글자 번짐 방지",
      "노이즈 없는 깨끗한 표면",
      "인물 얼굴 왜곡 방지",
      "손가락 및 로고 형태 왜곡 방지",
      "제품 윤곽선 선명",
      "과한 광원·네온 번짐·렌즈 플레어 방지",
      "장난감 같은 3D 오브젝트와 가짜 홀로그램 금지",
      "실사 합성의 원근·스케일·그림자·색온도 일관성 유지",
      "외부 프레임 없는 단일 완성 이미지",
    ],
    en: [
      "advertising-grade quality, 4K ultra-detailed, sharp at every output scale",
      "strong text-to-background contrast",
      "crisp text edges",
      "no pixelation",
      "headline legible at thumbnail size",
      "prevent small text blurring",
      "clean noise-free surfaces",
      "prevent face distortion",
      "prevent hand and logo distortion",
      "sharp product contours",
      "avoid excessive lighting effects, neon bloom, and lens flare",
      "no toy-like 3D objects or fake holograms",
      "keep photorealistic compositing consistent in perspective, scale, shadows, and color temperature",
      "single finished image with no outer frame",
    ],
  };

  const COMMERCIAL_BASELINE_PROFILES = {
    off: {
      labelKo: "없음",
      labelEn: "Off",
      linesKo: [],
      linesEn: [],
    },
    standard: {
      labelKo: "스탠다드",
      labelEn: "Standard",
      linesKo: [
        "상업용 홍보 이미지 수준의 정돈감과 명확한 시선 흐름을 유지한다",
        "메시지는 하나의 핵심 포인트로 압축하고, CTA는 즉시 읽히게 정리한다",
        "과장된 효과보다 안정적인 광고 제작물 완성도를 우선한다",
      ],
      linesEn: [
        "Maintain the polish and clarity expected from a commercial promotion image",
        "Compress the message around one primary point and keep the CTA instantly readable",
        "Prioritize dependable advertising-grade finish over exaggerated effects",
      ],
    },
    premium: {
      labelKo: "프리미엄",
      labelEn: "Premium",
      linesKo: [
        "프리미엄 브랜드 캠페인 시안처럼 정교한 위계와 고급스러운 마감을 만든다",
        "하나의 강한 포컬 포인트를 중심으로 비범하지만 과하지 않은 편집형 구도를 만든다",
        "흔한 SNS 썸네일 느낌을 피하고, 광고 아트디렉션이 느껴지는 완성도를 우선한다",
      ],
      linesEn: [
        "Deliver the hierarchy and polish of a premium brand-campaign key visual",
        "Build the composition around one strong focal point with an editorial layout that feels distinctive but controlled",
        "Avoid generic social-thumbnail aesthetics and favor clear advertising art direction",
      ],
    },
    luxury: {
      labelKo: "럭셔리",
      labelEn: "Luxury",
      linesKo: [
        "하이엔드 글로벌 캠페인 시안 수준의 절제된 고급감과 상업적 완성도를 만든다",
        "여백, 재질, 광원, 색상 절제를 통해 럭셔리 브랜드 광고처럼 보이게 만든다",
        "모든 요소가 값비싸고 정밀하게 보이도록 표면 질감과 디테일을 고급스럽게 통제한다",
      ],
      linesEn: [
        "Aim for the restraint and polish of a high-end global campaign visual",
        "Use whitespace, material treatment, lighting, and restrained color to evoke luxury-brand advertising",
        "Control surface detail and finishing so every element feels expensive and precisely crafted",
      ],
    },
  };

  const CREATIVITY_LEVEL_PROFILES = {
    stable: {
      labelKo: "안정형",
      labelEn: "Stable",
      linesKo: [
        "정보 전달과 가독성을 최우선으로 두고 무리한 구도 실험은 줄인다",
        "익숙한 광고 문법 안에서 정교함과 완성도를 높이는 방향으로 설계한다",
      ],
      linesEn: [
        "Prioritize clarity and readability over aggressive compositional experimentation",
        "Stay within familiar advertising grammar to ensure a stable layout while raising precision and finish",
      ],
    },
    balanced: {
      labelKo: "균형형",
      labelEn: "Balanced",
      linesKo: [
        "가독성과 창의성의 균형을 맞추고, 과하지 않은 긴장감 있는 레이아웃을 허용한다",
        "브랜드 광고처럼 안정적이되 한두 개의 신선한 조형 포인트를 넣는다",
      ],
      linesEn: [
        "Balance readability with creativity and allow controlled layout tension",
        "Keep the composition brand-safe while introducing one or two fresh formal ideas",
      ],
    },
    experimental: {
      labelKo: "실험형",
      labelEn: "Experimental",
      linesKo: [
        "비대칭, 오버랩, 프레임 돌출, 색면 분할 같은 공격적인 구도 실험을 허용한다",
        "단, 헤드라인과 CTA 가독성은 유지한 채 예측 가능한 레이아웃을 피한다",
      ],
      linesEn: [
        "Allow assertive experimental layouts such as asymmetry, overlap, frame-breaking, and color-field splits",
        "Preserve headline and CTA readability while avoiding predictable layouts",
      ],
    },
  };

  const VARIATION_SEEDS = [
    {
      id: "typo",
      labelKo: "타이포그래피 중심",
      labelEn: "Typography-driven",
      linesKo: [
        "타이포그래피를 주인공으로, 비주얼 오브젝트는 보조 역할로 제한한다",
        "여백을 적극적으로 활용해 텍스트 위계를 단순하고 강하게 잡는다",
        "서체 크기 대비를 과감하게 벌려 시선 흐름을 타이포 중심으로 유도한다",
        "색상 수는 최대 3가지로 제한하고, 포인트색은 CTA 요소에만 사용한다",
      ],
      linesEn: [
        "Typography is the hero; limit visual objects to supporting roles only",
        "Use generous white space to keep the text hierarchy simple and powerful",
        "Exaggerate the scale contrast between type sizes to guide the eye through copy first",
        "Restrict the palette to 3 colors maximum; reserve the accent color for the CTA element only",
      ],
    },
    {
      id: "visual",
      labelKo: "비주얼 오브젝트 중심",
      labelEn: "Visual-object-driven",
      linesKo: [
        "강렬한 단일 비주얼 오브젝트를 화면 중심에 배치해 시선을 즉시 집중시킨다",
        "텍스트는 오브젝트 주변에 최소화하고, 헤드라인과 CTA만 전면에 노출한다",
        "배경과 오브젝트 사이의 명도·채도 대비를 극대화해 입체감을 강조한다",
        "오브젝트의 질감·조명·그림자를 세밀하게 묘사해 광고 시안 수준의 완성도를 낸다",
      ],
      linesEn: [
        "Place one dominant visual object at the focal center to capture attention instantly",
        "Minimize on-image text to headline and CTA only; let the object carry the message",
        "Maximize the brightness and saturation contrast between background and object for depth",
        "Describe texture, lighting, and shadow on the object in detail to achieve advertising-grade polish",
      ],
    },
    {
      id: "experimental",
      labelKo: "실험적 레이아웃",
      labelEn: "Experimental layout",
      linesKo: [
        "대칭을 의도적으로 깨고 비대칭 구성으로 긴장감과 역동성을 연출한다",
        "텍스트 블록을 사선 또는 불규칙 각도로 배치해 시선에 에너지를 준다",
        "그리드 경계를 벗어나는 블리드(bleed) 요소를 활용해 화면 밖으로 확장되는 느낌을 준다",
        "색면 분할이나 중첩 레이어로 공간에 깊이감을 더하고 단조로운 레이아웃을 탈피한다",
        "헤드라인과 CTA 가독성은 유지하되 예측 가능한 정보 카드 배열을 피한다",
      ],
      linesEn: [
        "Intentionally break symmetry with an asymmetric composition to create tension and energy",
        "Angle or tilt text blocks to inject kinetic momentum into the eye path",
        "Use bleed elements that appear to extend beyond the frame edge for a dynamic, expansive feel",
        "Add depth with color-field splits or overlapping layers to escape a flat, predictable layout",
        "Preserve headline and CTA readability while avoiding predictable card-array layouts",
      ],
    },
    {
      id: "color-graphic",
      labelKo: "컬러 그래픽",
      labelEn: "Color-graphic",
      linesKo: [
        "사진이 아닌 굵고 선명한 색면·기하 도형·그래픽 요소를 화면의 주인공으로 사용한다",
        "배경에서 전경까지 색상 블록과 선형 요소로 공간을 나누어 브랜드 아이덴티티를 강조한다",
        "타이포는 색면과 강한 대비를 이루는 위치에 크고 단호하게 배치한다",
        "일러스트레이션 또는 아이콘 기반 요소를 사진 대신 활용해 그래픽 선명도를 높인다",
        "같은 색상 계열 안에서도 명도·채도 차이로 레이어 깊이를 만들어 평면처럼 보이지 않게 한다",
      ],
      linesEn: [
        "Use bold color fields, geometric shapes, and graphic elements as the hero instead of photography",
        "Divide the space from background to foreground with color blocks and linear elements to reinforce brand identity",
        "Place typography large and assertively where it contrasts strongly against the color fields",
        "Use illustration or icon-based elements in place of photography to maximize graphic sharpness",
        "Create layer depth within the same color family through lightness and saturation differences to avoid a flat appearance",
      ],
    },
    {
      id: "cinematic",
      labelKo: "감성 배경",
      labelEn: "Cinematic",
      linesKo: [
        "분위기 있는 풀블리드 배경 이미지가 공간 전체를 채우고 텍스트는 그 위에 최소로 얹는다",
        "감정과 상황을 텍스트로 설명하지 않고 장면과 빛으로 먼저 전달한다",
        "헤드라인과 CTA는 반투명 오버레이 또는 명도 차이를 활용해 배경과 분리한다",
        "사진 또는 렌더링의 조명·피사계 심도·색감을 영화적으로 처리해 완성도를 높인다",
        "정보 밀도를 낮추고 공간 여운을 남겨 감성적 잔상이 생기도록 한다",
      ],
      linesEn: [
        "A full-bleed atmospheric background fills the entire frame; overlay text is kept to a minimum",
        "Convey emotion and context through scene and light first, not through explanatory text",
        "Separate headline and CTA from the background using semi-transparent overlays or luminance contrast",
        "Apply cinematic lighting, depth of field, and color grading to the photo or rendered scene",
        "Lower information density and leave spatial breathing room so an emotional afterimage remains",
      ],
    },
    {
      id: "proof",
      labelKo: "수치/증거",
      labelEn: "Proof-driven",
      linesKo: [
        "크고 선명한 숫자, 통계, 수치가 화면에서 가장 먼저 읽히는 시각 요소가 되도록 배치한다",
        "수치 주변에 신뢰 신호(로고, 배지, 출처 레이블)를 정보 카드 형태로 정렬한다",
        "비주얼 은유나 감성 이미지보다 증거 데이터의 명확성과 가독성을 최우선으로 둔다",
        "정보 밀도가 높아도 여백과 위계를 명확히 유지해 신뢰감 있게 정리한다",
        "숫자 폰트는 가장 큰 크기 계층에 두고, 보조 설명은 작은 레이어로 눌러 데이터가 돋보이게 한다",
      ],
      linesEn: [
        "Place large, clear numbers, statistics, or data points as the first visual element the eye lands on",
        "Arrange trust signals such as logos, badges, and source labels in structured information cards around the numbers",
        "Prioritize legibility and clarity of proof data over visual metaphors or emotional imagery",
        "Maintain clear whitespace and hierarchy even under high information density to keep the layout credible",
        "Set number typography at the largest scale tier and suppress supporting text to a smaller layer so the data stands out",
      ],
    },
    {
      id: "content-focus",
      labelKo: "콘텐츠 집중",
      labelEn: "Content-first",
      linesKo: [
        "키비주얼·비주얼 오브젝트는 배경층(color wash, 반투명 이미지, 질감)에만 배치하고 전경에 독립 오브젝트로 등장하지 않는다",
        "전경 전체를 헤드라인 / 핵심 정보 카드 / CTA 텍스트 위계로만 채운다",
        "배경 비주얼의 채도·명도를 낮추거나 오버레이를 적용해 텍스트와의 명도 대비를 확보한다",
        "비주얼 오브젝트가 텍스트 가독성을 방해하는 위치에 절대 오지 않는다",
        "레이아웃 우선순위: 정보 위계 → 행동 유도 → 배경 분위기 순서로 처리한다",
      ],
      linesEn: [
        "Limit the key visual and visual objects to the background layer only (color wash, semi-transparent image, texture); they must not appear as standalone foreground objects",
        "The entire foreground is occupied by the headline, core information cards, and CTA hierarchy",
        "Reduce the saturation and brightness of the background visual or apply an overlay to ensure sufficient contrast with the text",
        "No visual object may appear in a position that obstructs text readability",
        "Layout priority order: information hierarchy first, action guidance second, background atmosphere third",
      ],
    },
    {
      id: "official-notice",
      labelKo: "공식 공고/안내판",
      labelEn: "Official Announcement",
      linesKo: [
        "상업용 광고 포스터 대신 공공기관·기업의 공식 지원사업 모집 공고 및 안내문 레이아웃을 사용한다",
        "상단에는 크고 명확한 고대비 타이틀을 배치하고, 우측 상단 또는 배경에 단정한 테마 일러스트(3D 그래픽, 심플 아이콘)를 작게 배치한다",
        "중하단 전체를 가득 채우는 둥근 모서리의 흰색 또는 미색 정보 보드판(Information Board)을 명확하게 렌더링한다",
        "정보 보드 내부에는 '지원대상, 지원규모, 신청방법, 문의처' 등의 정보가 깔끔하게 구분된 행(Row)과 배지(Badge) 라벨 형태로 정돈되게 묘사한다",
        "이미지 최하단에는 주최 및 파트너 기관들의 로고가 가로 일렬로 평평하게 들어설 수 있는 깔끔한 흰색/푸른색 로고 밴드 영역을 확보한다"
      ],
      linesEn: [
        "Use a formal public announcement and business notice layout instead of a commercial ad poster",
        "Place a large, high-contrast title at the top, and position a clean, small thematic visual (3D blocks, simple icons) in the top-right or background",
        "Render a prominent light-colored or white information board with rounded corners filling the middle and bottom sections",
        "Inside the board, arrange details like eligibility, budget, and contact info in neat rows with badge labels",
        "Ensure a clean horizontal band at the very bottom of the image to serve as a placeholder for hosting/partner organization logos"
      ],
    }
  ];

  const CONTENT_PROMOTION_STRATEGIES = {
    none: {
      linesKo: [
        "헤드라인과 핵심 혜택을 가장 먼저 읽히게 하고, 나머지 정보는 보조 레이어로 낮춘다",
      ],
      linesEn: [
        "Make the headline and core benefit read first; push secondary information into supporting layers",
      ],
    },
    campaign: {
      linesKo: [
        "감정적 공감과 참여 동기를 먼저 만들고, 캠페인 슬로건을 강한 첫 인상으로 고정한다",
        "상징 오브젝트나 은유 장면을 활용해 메시지를 설명하지 않고 직관적으로 느끼게 만든다",
        "행동 유도는 참여 선언, 서약, 공유, 신청 중 하나로 명확하게 좁힌다",
      ],
      linesEn: [
        "Build emotional empathy and participation motive first, then lock the campaign slogan as the strongest first impression",
        "Use a symbolic object or metaphorical scene so the message is felt intuitively rather than explained literally",
        "Narrow the action prompt to one clear behavior such as pledge, share, register, or join",
      ],
    },
    "result-promo": {
      linesKo: [
        "핵심 수치와 성과 타이틀을 가장 먼저 보이게 하고, 신뢰감을 주는 정보 카드 구조로 정돈한다",
        "성과 데이터는 장식이 아니라 증거처럼 보여야 하며, 숫자·출처·라벨의 가독성을 최우선으로 둔다",
        "비주얼 은유는 상승, 확장, 누적, 신뢰 같은 방향으로 제한해 과장된 축제 분위기를 피한다",
      ],
      linesEn: [
        "Make the key metric and outcome title read first, then organize supporting information into trustworthy information cards",
        "Performance data must read like evidence rather than decoration; prioritize legibility of numbers, sources, and labels",
        "Limit visual metaphors to growth, expansion, accumulation, or trust; avoid exaggerated celebratory styling",
      ],
    },
    "event-info": {
      linesKo: [
        "행사명과 날짜·장소·신청 행동을 빠르게 읽히게 하고, 분위기는 참여하고 싶은 장면으로 연출한다",
        "메인 비주얼은 행사 경험을 상상하게 만드는 인물, 공간, 조명, 움직임 중 하나로 잡는다",
        "정보 박스는 하단 또는 한쪽 축에 묶어 포스터처럼 즉시 스캔 가능하게 만든다",
      ],
      linesEn: [
        "Make the event title, date, location, and registration action readable quickly, while staging the mood as an experience people want to join",
        "Use one main visual cue such as people, venue, light, or motion to make the event experience imaginable",
        "Group event details into a bottom or side information zone so the image scans like a poster",
      ],
    },
    "survey-request": {
      linesKo: [
        "참여 부담을 낮추는 친근한 첫 인상과 짧은 소요 시간·혜택·의미를 명확히 보여준다",
        "딱딱한 조사 문서처럼 보이지 않게 라운드 카드, 부드러운 색면, 간단한 아이콘을 활용한다",
        "CTA는 선물·의견·참여 의미 중 하나를 중심으로 가볍고 즉각적인 행동으로 만든다",
      ],
      linesEn: [
        "Create a friendly first impression that lowers participation friction, while clearly showing duration, reward, and purpose",
        "Avoid a rigid survey-document look by using rounded cards, soft color fields, and simple icons",
        "Shape the CTA around reward, opinion, or contribution so the action feels light and immediate",
      ],
    },
    "training-info": {
      linesKo: [
        "교육 혜택, 성장 가능성, 마감일을 한눈에 보이게 하고 신청 동기를 분명히 만든다",
        "학습·성장 은유는 계단, 상승 그래프, 경로, 열린 문, 연결된 네트워크 노드, 도약하는 로켓처럼 긍정적이고 전문적인 상징 중에서 다양하게 선택한다",
        "커리큘럼 정보는 길게 설명하지 말고 핵심 혜택을 겹친 단계 카드, 연결 노드, 메인 은유 안의 텍스트 블록처럼 다양한 정보 묶음 방식으로 정리한다",
      ],
      linesEn: [
        "Make training benefits, growth potential, and deadline visible at a glance, with a clear reason to apply",
        "Use diverse positive professional learning metaphors such as stairs, rising graphs, paths, open doors, connected network nodes, or a rising rocket",
        "Do not explain curriculum at length; organize the core benefits into diverse visual formats such as overlapping step-up cards, connected nodes, or integrated text blocks inside the main metaphor",
      ],
    },
    "biz-promo": {
      linesKo: [
        "지원 혜택과 신청 자격을 명확히 보여주되, 스타트업·비즈니스 광고처럼 에너지 있는 장면을 만든다",
        "비주얼은 기회, 연결, 확장, 투자, 파트너십을 상징하는 오브젝트나 공간 구조로 잡는다",
        "과도한 네온이나 장난감 같은 3D를 피하고, 전문성과 성장감을 동시에 준다",
      ],
      linesEn: [
        "Show program benefits and eligibility clearly while creating an energetic startup or business-advertising scene",
        "Build the visual around objects or spatial structures symbolizing opportunity, connection, expansion, investment, or partnership",
        "Avoid excessive neon or toy-like 3D; balance professionalism with growth energy",
      ],
    },
  };

  const CREATIVE_DIVERSITY_PROFILES = {
    stable: {
      linesKo: [
        "동일한 정보라도 흔한 공지형 템플릿을 피하고, 색면·여백·타이포 스케일 중 하나에 차별점을 둔다",
        "결과물은 안정적이어야 하지만 스톡 이미지처럼 평범하거나 무난한 안내문처럼 보이면 안 된다",
      ],
      linesEn: [
        "Even with the same information, avoid a generic notice-template look by differentiating one element: color fields, whitespace, or type scale",
        "The result should remain stable, but must not look like a generic stock image or plain announcement",
      ],
    },
    balanced: {
      linesKo: [
        "서로 다른 결과가 나오도록 타이포 중심, 오브젝트 중심, 공간 분할 중 하나를 과감하게 선택한다",
        "하나의 신선한 시각 아이디어를 반드시 포함하되, 헤드라인과 CTA의 가독성은 절대 희생하지 않는다",
        "뻔한 중앙 정렬 포스터 대신 비대칭 축, 오버랩 레이어, 대담한 크롭 중 하나를 활용한다",
      ],
      linesEn: [
        "Choose one decisive direction among typography-led, object-led, or spatially split composition so outputs vary meaningfully",
        "Include one fresh visual idea, but never sacrifice headline or CTA readability",
        "Avoid a predictable centered poster by using one of: asymmetric axis, overlapping layers, or bold cropping",
      ],
    },
    experimental: {
      linesKo: [
        "예측 가능한 템플릿 구성을 피하고, 비대칭·블리드·색면 분할·초현실적 은유 중 하나를 명확히 사용한다",
        "장면은 광고 아트디렉션처럼 의도적으로 낯설고 기억에 남아야 하며, 단순 정보 나열로 끝나면 안 된다",
        "단, 문구 왜곡·정보 누락·CTA 가독성 저하는 허용하지 않는다",
      ],
      linesEn: [
        "Avoid predictable templates and clearly use one of: asymmetry, bleed, color-field split, or surreal metaphor",
        "The scene should feel intentionally distinctive and memorable like advertising art direction, not just a list of information",
        "However, do not allow text distortion, missing information, or reduced CTA readability",
      ],
    },
  };

  const LAYOUT_COMPOSITION_PROFILES = {
    centered: {
      labelKo: "중앙 대칭형",
      labelEn: "Centered symmetrical",
      linesKo: [
        "전형적인 중앙 집중 대칭 구도를 사용한다.",
        "헤드라인과 메인 비주얼, 행동버튼이 캔버스 세로 중앙 축을 기준으로 차례대로 정렬되며, 시선 흐름이 위에서 아래로 정직하게 흐른다.",
        "좌우 여백을 균등하게 배분하여 안정감을 극대화한다."
      ],
      linesEn: [
        "Apply a classic centered symmetrical composition.",
        "Align the headline, key visual, and action button sequentially along the vertical center axis of the canvas, ensuring a straightforward top-to-bottom eye flow.",
        "Distribute margins evenly on both sides to maximize formal stability."
      ]
    },
    "left-heavy": {
      labelKo: "비대칭 좌측 집중",
      labelEn: "Asymmetric left-heavy",
      linesKo: [
        "캔버스를 4:6 비율의 비대칭 수직 열로 나누어 배치한다.",
        "모든 텍스트 요소와 행동버튼(CTA)은 좌측 40% 영역(어두운 배경 영역) 내에 왼쪽 정렬하여 밀도 높게 몰아넣는다.",
        "우측 60% 영역은 텍스트 없이 메인 비주얼 오브젝트의 과감하게 크롭된 모습만을 보여주고, 텍스트가 비주얼 위로 절대 침범하지 않게 한다."
      ],
      linesEn: [
        "Split the canvas into a 4:6 asymmetric vertical columns.",
        "Place all text elements and the action button neatly left-aligned inside the left 40% column (with a dark overlay/background).",
        "Reserve the right 60% column solely for the bold cropped visual object, ensuring zero text overlaps onto the key visual."
      ]
    },
    "typo-first": {
      labelKo: "거대 타이포 분할",
      labelEn: "Typography-first split",
      linesKo: [
        "타이포그래피 중심의 분할 레이아웃을 사용한다.",
        "거대하게 렌더링된 헤드라인 텍스트가 화면 상단 60%를 가득 채우며 시선을 즉각적으로 사로잡는다.",
        "메인 비주얼 오브젝트와 콤팩트한 행동버튼(CTA)은 하단 40% 영역에 넓은 빈 여백을 확보한 상태로 작게 배치하여 텍스트의 임팩트를 극대화한다."
      ],
      linesEn: [
        "Employ a typography-driven split composition.",
        "A gigantic rendered headline text must dominate and occupy the top 60% of the screen area to grab immediate focus.",
        "Position the main visual object and a compact action button inside the bottom 40% area with generous negative space, maximizing the typographic impact."
      ]
    },
    "clean-split": {
      labelKo: "사선 공간 분할",
      labelEn: "Clean diagonal split",
      linesKo: [
        "사선 또는 면 대비를 통해 시각 영역을 선명하게 분할한다.",
        "텍스트가 올라가는 배경 레이어는 아무런 노이즈가 없는 완전한 단색 어두운 면으로 분리하여 가독성을 100% 확보한다.",
        "반대편 대비되는 밝고 강렬한 색상 필드 영역에 추상적인 기하학 오브젝트를 배치하여, 글씨가 없는 예술 영역과 글씨 영역을 물리적으로 격리한다."
      ],
      linesEn: [
        "Apply a clean diagonal or high-contrast split composition.",
        "Isolate the text background layer as a pure solid dark surface with zero visual noise behind the letters to guarantee 100% readability.",
        "Position the abstract geometric object in a contrasting bright color field on the opposite side, physically separating the text zone from the purely artistic visual zone."
      ]
    }
  };

  const ATTENTION_FLOW_VARIANTS = [
    {
      id: "visual-first",
      labelKo: "패턴 A: 비주얼 중심",
      labelEn: "Pattern A: visual-first",
      linesKo: [
        "Order 1: 메인 비주얼 오브젝트 또는 상징 장면",
        "Order 2: 헤드라인 또는 가장 중요한 후킹 문구",
        "Order 3: 혜택, 일정, 장소, 핵심 조건 등 보조 정보",
        "Order 4: 행동버튼, QR 자리, 링크 안내 같은 행동 유도 요소",
      ],
      linesEn: [
        "Order 1: main visual object or symbolic scene",
        "Order 2: headline or most important hook copy",
        "Order 3: supporting details such as benefit, date, location, or key condition",
        "Order 4: action button, QR placeholder, link guide, or other conversion element",
      ],
    },
    {
      id: "information-first",
      labelKo: "패턴 B: 정보 중심",
      labelEn: "Pattern B: information-first",
      linesKo: [
        "Order 1: 헤드라인 또는 핵심 제안",
        "Order 2: 혜택, 일정, 장소, 핵심 조건 등 보조 정보",
        "Order 3: 메인 비주얼 오브젝트 또는 상징 장면",
        "Order 4: 행동버튼, QR 자리, 링크 안내 같은 행동 유도 요소",
      ],
      linesEn: [
        "Order 1: headline or core offer",
        "Order 2: supporting details such as benefit, date, location, or key condition",
        "Order 3: main visual object or symbolic scene",
        "Order 4: action button, QR placeholder, link guide, or other conversion element",
      ],
    },
    {
      id: "typography-first",
      labelKo: "패턴 C: 타이포그래피 중심",
      labelEn: "Pattern C: typography-first",
      linesKo: [
        "Order 1: 거대한 헤드라인 타이포그래피",
        "Order 2: 짧은 서브카피 또는 한 줄 오퍼",
        "Order 3: 축소된 메인 비주얼 또는 배경 은유",
        "Order 4: 행동버튼 또는 신청/참여 안내",
      ],
      linesEn: [
        "Order 1: oversized headline typography",
        "Order 2: short sub-copy or single-line offer",
        "Order 3: reduced main visual or background metaphor",
        "Order 4: action button or application/join guide",
      ],
    },
    {
      id: "proof-first",
      labelKo: "패턴 D: 증거/수치 중심",
      labelEn: "Pattern D: proof-first",
      linesKo: [
        "Order 1: 핵심 수치, 혜택, 마감일, 장소처럼 행동 판단에 필요한 증거",
        "Order 2: 헤드라인 또는 캠페인 메시지",
        "Order 3: 보조 비주얼 은유 또는 브랜드 분위기",
        "Order 4: 행동버튼, QR 자리, 링크 안내 같은 행동 유도 요소",
      ],
      linesEn: [
        "Order 1: proof needed for action such as key metric, benefit, deadline, or location",
        "Order 2: headline or campaign message",
        "Order 3: supporting visual metaphor or brand mood",
        "Order 4: action button, QR placeholder, link guide, or other conversion element",
      ],
    },
  ];

  const AI_LAYOUT_STRATEGY_OPTIONS = [
    {
      labelKo: "Asymmetrical axis composition (비대칭축 구성)",
      labelEn: "Asymmetrical axis composition",
      descKo: "정보를 한쪽 축에 몰고 반대편에 비주얼을 과감하게 배치한다.",
      descEn: "Concentrate information on one axis and place the visual boldly on the opposite side.",
    },
    {
      labelKo: "Split-screen composition (분할 화면 구성)",
      labelEn: "Split-screen composition",
      descKo: "화면을 좌우 또는 상하로 명확히 나누어 정보 영역과 비주얼 영역을 분리한다.",
      descEn: "Divide the canvas vertically or horizontally to separate the information zone and the visual zone.",
    },
    {
      labelKo: "Typography-led minimalist composition (타이포그래피 중심 미니멀 구성)",
      labelEn: "Typography-led minimalist composition",
      descKo: "비주얼을 줄이고 글자 크기, 굵기, 여백의 대비로 화면을 구성한다.",
      descEn: "Reduce visual objects and build the image through type scale, weight, and whitespace contrast.",
    },
    {
      labelKo: "Radial composition from center (중심 방사형 구성)",
      labelEn: "Radial composition from center",
      descKo: "중앙 핵심 비주얼에서 정보가 주변으로 퍼지는 구조를 만든다.",
      descEn: "Place a core visual at the center and arrange information radiating around it.",
    },
    {
      labelKo: "Diagonal progression composition (대각선 진행형 구성)",
      labelEn: "Diagonal progression composition",
      descKo: "계단, 성장, 이동, 전환 메시지를 대각선 진행 축으로 표현한다.",
      descEn: "Express steps, growth, movement, or transition along a diagonal progression axis.",
    },
  ];

  const AI_VISUAL_METAPHOR_EXAMPLES = [
    "stairs",
    "rising graphs",
    "paths",
    "open doors",
    "connected network nodes",
    "rising rocket",
    "spotlight corridor",
    "bridge",
    "portal",
    "expanding orbit",
  ];

  const INFORMATION_ITEM_LAYOUT_VARIANTS = [
    {
      labelKo: "타임라인 리본",
      labelEn: "timeline ribbon",
      descKo: "일정, 마감일, 단계 정보를 얇은 흐름선이나 리본 위에 배치한다.",
      descEn: "Place schedule, deadline, or step details along a slim flow line or ribbon.",
    },
    {
      labelKo: "세로 마일스톤 레일",
      labelEn: "vertical milestone rail",
      descKo: "자격, 일정, 혜택, 마감일을 세로 축의 체크포인트처럼 배열한다.",
      descEn: "Arrange eligibility, schedule, benefits, and deadline as checkpoints on a vertical axis.",
    },
    {
      labelKo: "방사형 정보 노드",
      labelEn: "radial information nodes",
      descKo: "중앙 비주얼 주변에 핵심 정보가 노드처럼 퍼지게 구성한다.",
      descEn: "Let key details radiate as nodes around the central visual.",
    },
    {
      labelKo: "대각선 스텝 시퀀스",
      labelEn: "diagonal step sequence",
      descKo: "성장, 신청, 참여 흐름을 대각선 단계 구조로 보여준다.",
      descEn: "Show growth, application, or participation flow as a diagonal step structure.",
    },
    {
      labelKo: "사이드 정보 레일",
      labelEn: "side information rail",
      descKo: "본문 정보는 좌우 한쪽의 정돈된 레일에 묶고 반대편에는 비주얼을 크게 둔다.",
      descEn: "Group body details into a clean side rail while the visual occupies the opposite side.",
    },
    {
      labelKo: "배지 스택",
      labelEn: "badge stack",
      descKo: "마감, 혜택, 자격 같은 핵심 조건을 작은 배지 묶음으로 변주한다.",
      descEn: "Use compact badge groups for key conditions such as deadline, benefit, and eligibility.",
    },
    {
      labelKo: "비주얼 내장 라벨",
      labelEn: "integrated labels inside the visual metaphor",
      descKo: "정보를 별도 카드가 아니라 메인 은유의 일부로 붙여 넣는다.",
      descEn: "Attach information to the main metaphor instead of using separate cards.",
    },
    {
      labelKo: "컴팩트 표 스트립",
      labelEn: "compact table strip",
      descKo: "정확성이 중요한 일정, 장소, 접수 정보를 얇은 표 형태의 스트립으로 정리한다.",
      descEn: "Organize precise schedule, location, and application details in a slim table-like strip.",
    },
  ];

  const QR_PLACEMENT_VARIANTS = [
    {
      labelKo: "코너 배지",
      labelEn: "corner badge",
      descKo: "QR 자리와 짧은 안내문구를 한쪽 모서리의 독립 배지로 둔다.",
      descEn: "Place the QR slot and helper text as an independent badge in one corner.",
    },
    {
      labelKo: "사이드 레일 슬롯",
      labelEn: "side rail slot",
      descKo: "QR을 정보 레일 안의 한 항목으로 통합한다.",
      descEn: "Integrate the QR into the information rail as one item.",
    },
    {
      labelKo: "CTA 인접 클러스터",
      labelEn: "CTA-adjacent cluster",
      descKo: "행동버튼 주변에 QR을 배치하되 전체 구도를 하단 박스로 고정하지 않는다.",
      descEn: "Place the QR near the action button without locking the whole composition into a bottom box.",
    },
    {
      labelKo: "플로팅 라벨 블록",
      labelEn: "floating label block",
      descKo: "QR을 메인 비주얼 옆에 떠 있는 작은 정보 블록으로 배치한다.",
      descEn: "Place the QR as a small floating information block near the main visual.",
    },
    {
      labelKo: "상단 유틸리티 영역",
      labelEn: "top utility area",
      descKo: "상단 우측 또는 좌측의 보조 정보 영역에 QR을 작게 둔다.",
      descEn: "Place a compact QR in a top-left or top-right utility area.",
    },
    {
      labelKo: "컴팩트 푸터 스트립",
      labelEn: "compact footer strip",
      descKo: "선택한 구도에 맞을 때만 얇은 푸터 스트립에 QR을 둔다.",
      descEn: "Use a slim footer strip only when it fits the selected composition.",
    },
    {
      labelKo: "정보 노드 통합",
      labelEn: "integrated information node",
      descKo: "QR을 일정, 신청방법, 마감 정보와 같은 노드 체계 안에 통합한다.",
      descEn: "Integrate the QR into the same node system as schedule, application method, or deadline.",
    },
  ];

  const MANDATORY_ELEMENT_PLACEMENT_VARIANTS = [
    {
      labelKo: "헤더 마이크로 라벨",
      labelEn: "header micro-label",
      descKo: "주최기관, 브랜드명, 필수 문구를 상단의 작은 라벨로 둔다.",
      descEn: "Place organizer, brand name, or required phrase as a small top label.",
    },
    {
      labelKo: "코너 태그",
      labelEn: "corner tag",
      descKo: "로고 자리나 필수 문구를 모서리 태그처럼 배치한다.",
      descEn: "Place a logo slot or required phrase as a corner tag.",
    },
    {
      labelKo: "사이드 레일",
      labelEn: "side rail",
      descKo: "필수 정보가 많을 때 한쪽 세로 레일에 정리한다.",
      descEn: "Use a vertical side rail when there are several required elements.",
    },
    {
      labelKo: "푸터 크레덴셜 스트립",
      labelEn: "footer credential strip",
      descKo: "저작권, 출처, 주최/주관 표기가 필요할 때만 얇은 하단 스트립을 사용한다.",
      descEn: "Use a slim bottom strip only when copyright, source, or organizer credentials require it.",
    },
    {
      labelKo: "CTA 인접 라벨",
      labelEn: "CTA-adjacent label",
      descKo: "신청 방법, 바로가기, 필수 행동 문구를 CTA 근처에 붙인다.",
      descEn: "Attach application method, shortcut, or required action copy near the CTA.",
    },
    {
      labelKo: "통합 캡션",
      labelEn: "integrated caption",
      descKo: "필수 문구를 메인 비주얼의 설명 캡션처럼 자연스럽게 통합한다.",
      descEn: "Integrate required copy as a natural caption for the main visual.",
    },
  ];

  const AI_TOGGLE_FIELDS = new Set(["posterOffer", "snsHook", "snsHashtags", "cta"]);
  const FIELD_ENABLE_TOGGLE_FIELDS = new Set(["posterKeyVisual", "posterInfoLayout", "snsVisualFocus", "snsPlacementNotes"]);

  const STEP5_QUALITY_OPTIONS = [
    "텍스트 가장자리 선명",
    "작은 글자 번짐 방지",
    "저해상도 픽셀 깨짐 방지",
    "노이즈 없는 깨끗한 표면",
    "인물 얼굴 왜곡 방지",
    "손가락·로고 형태 왜곡 방지",
    "제품 윤곽선 선명",
    "과한 합성 광택 방지",
    "스톡 이미지 같은 질감 방지",
  ];

  const STEP3_VISUAL_OPTION_GROUPS = {
    tone: ["신뢰감", "전문적", "따뜻함", "활기", "프리미엄", "차분함"],
    bigIdea: ["연결", "성장", "참여", "전환", "기회", "신뢰"],
    visualMetaphor: ["빛의 경로", "열린 문", "상승 곡선", "연결된 카드", "투명한 큐브", "중심으로 모이는 흐름"],
    visualStyle: [
      "실사 중심",
      "에디토리얼 광고형",
      "미니멀 정보형",
      "인포그래픽형",
      "3D 오브젝트",
      "대담한 타이포그래피",
      "플랫 일러스트",
      "아이소메트릭",
      "데이터 시각화형",
      "콜라주형",
      "제품 광고형",
      "공공 안내형",
      "매거진 커버형",
      "모션 그래픽 느낌",
      "따뜻한 캐릭터형",
      "하이엔드 캠페인형",
      "테크 UI형",
      "포토그래픽 포스터형",
      "유리 카드형",
      "입체 레이어형",
      "페이퍼 콜라주형",
    ],
  };

  const STEP3_IDEA_PRESETS = [
    {
      id: "trust",
      label: "신뢰형",
      desc: "공공성, 기관 신뢰, 안정적인 안내",
      fields: {
        tone: "신뢰감, 전문적, 차분함",
        bigIdea: "신뢰",
        visualMetaphor: "안정적인 중심축과 정돈된 정보 카드",
        visualStyle: "미니멀 정보형, 에디토리얼 광고형",
      },
    },
    {
      id: "growth",
      label: "성장형",
      desc: "기회, 확장, 참여 동기",
      fields: {
        tone: "활기, 긍정적, 미래지향",
        bigIdea: "성장",
        visualMetaphor: "상승 곡선과 빛의 경로",
        visualStyle: "캠페인 광고형, 대담한 타이포그래피",
      },
    },
    {
      id: "connection",
      label: "연결형",
      desc: "네트워크, 협력, 커뮤니티",
      fields: {
        tone: "따뜻함, 신뢰감, 현대적",
        bigIdea: "연결",
        visualMetaphor: "여러 카드와 경로가 하나의 중심으로 연결되는 장면",
        visualStyle: "인포그래픽형, 미니멀 정보형",
      },
    },
    {
      id: "premium",
      label: "프리미엄형",
      desc: "고급 캠페인, 선명한 키비주얼",
      fields: {
        tone: "프리미엄, 세련된, 절제된",
        bigIdea: "전환",
        visualMetaphor: "빛이 통과하는 투명한 큐브와 넓은 여백",
        visualStyle: "에디토리얼 광고형, 실사 중심, 대담한 타이포그래피",
      },
    },
  ];

  const ANTI_AI_PRESETS = [
    {
      id: "general",
      labelKo: "일반/범용",
      labelEn: "General / Universal",
      descKo: "스타일 왜곡 없는 AI 결함 억제 · 형태/화질 보정",
      descEn: "Style-agnostic suppression · general quality corrections",
      visualHintKo: "왜곡 없는 자연스러운 비주얼 구조, 형태적 안정성과 균형",
      visualHintEn: "natural visual structure without distortion, formal stability and balance",
      forbiddenKo: "이모지 사용 금지, 광택 CTA 버튼, 저해상도 스톡 느낌, 비정상적 형태 왜곡, 뭉개진 손가락, 붕괴된 외곽선, 부자연스럽고 조악한 인공 광택, 엉성한 AI 스톡 느낌",
      forbiddenEn: "no emoji usage, glossy action buttons, low-resolution stock appearance, deformed shapes, mutated fingers, collapsed outlines, unnatural cheap synthetic gloss, poorly crafted AI stock aesthetic",
    },
    {
      id: "flat_vector",
      labelKo: "플랫/벡터",
      labelEn: "Flat / Vector",
      descKo: "기어·회로 콜라주 금지 · 단순 아이콘·선형 일러스트",
      descEn: "No gear/circuit collage · flat icons, line illustration",
      visualHintKo: "플랫 벡터 스타일, 단순한 아이콘 조합, 선형 일러스트",
      visualHintEn: "flat vector style, simple icon composition, line illustration",
      forbiddenKo: "기어 콜라주, 회로판 오버레이, 부품 합성, 과도한 3D 렌더링, 기계 파편 콜라주, AI 스톡 일러스트 무드",
      forbiddenEn: "gear collage, circuit board overlay, mechanical parts composition, over-rendered 3D, AI stock illustration aesthetic",
    },
    {
      id: "photo_real",
      labelKo: "실사/사진",
      labelEn: "Photo / Real",
      descKo: "AI 합성 이미지 금지 · 실제 촬영 사진 느낌",
      descEn: "No AI-generated composites · real photo mood",
      visualHintKo: "실사 사진 무드, 촬영 기반 이미지, 자연스러운 조명",
      visualHintEn: "photo-realistic mood, camera-based imagery, natural lighting",
      forbiddenKo: "AI 합성 느낌, 가상 오브젝트 조합, 투명 레이어 부유 효과, 인공적인 렌더링 광택, 비현실적 구조물",
      forbiddenEn: "AI composite feel, floating virtual objects, translucent layer stacking, artificial render gloss, unrealistic structures",
    },
    {
      id: "minimal_typo",
      labelKo: "미니멀/타이포",
      labelEn: "Minimal / Typo",
      descKo: "복잡한 오브젝트 금지 · 타이포 + 여백 중심",
      descEn: "No complex objects · typography and whitespace only",
      visualHintKo: "타이포그래피 중심, 최소한의 오브젝트, 넓은 여백, 강한 서체 대비",
      visualHintEn: "typography-driven, minimal objects, generous whitespace, strong typeface contrast",
      forbiddenKo: "복잡한 배경 오브젝트, 장식적 파티클, AI 생성 텍스처, 과도한 그래픽 요소, 어지러운 콜라주",
      forbiddenEn: "complex background objects, decorative particles, AI-generated textures, excessive graphic elements, cluttered collage",
    },
  ];

  Object.assign(COMMERCIAL_BASELINE_PROFILES, {
    off: {
      labelKo: "기본",
      labelEn: "Basic",
      linesKo: [],
      linesEn: [],
    },
    standard: {
      labelKo: "실무형",
      labelEn: "Production-ready",
      linesKo: [
        "기본적인 상업 홍보물 수준의 선명도와 정돈된 마감을 유지한다",
        "정보가 과장되지 않게 보이도록 안정적인 밀도와 균형을 유지한다",
      ],
      linesEn: [
        "Maintain production-ready clarity and a clean commercial finish",
        "Keep density and balance stable so the information does not feel exaggerated",
      ],
    },
    premium: {
      labelKo: "프리미엄",
      labelEn: "Premium",
      linesKo: [
        "캠페인 키비주얼 수준의 정교한 마감, 선명한 초점, 고급스러운 표면 품질을 만든다",
        "장식보다 완성도를 우선해 모든 요소가 의도적으로 정돈된 광고 시안처럼 보이게 한다",
      ],
      linesEn: [
        "Deliver campaign-key-visual polish with refined finishing, clear focal control, and premium surface quality",
        "Prioritize finish over decoration so every element feels intentionally controlled",
      ],
    },
    luxury: {
      labelKo: "하이엔드",
      labelEn: "High-end luxury",
      linesKo: [
        "하이엔드 브랜드 캠페인처럼 절제된 밀도, 정밀한 질감, 값비싸 보이는 마감을 구현한다",
        "과장된 효과보다 여백, 표면, 조명, 디테일의 정교함으로 완성도를 높인다",
      ],
      linesEn: [
        "Create a high-end campaign finish with restrained density, precise material detail, and expensive-looking polish",
        "Use whitespace, surface, lighting, and detail refinement rather than exaggerated effects",
      ],
    },
  });

  Object.assign(CREATIVITY_LEVEL_PROFILES, {
    stable: {
      labelKo: "안정형",
      labelEn: "Stable",
      linesKo: [
        "검증된 정보형 구성을 사용하고 시선 흐름을 예측 가능하게 유지한다",
        "구성 실험보다 정보 전달 안정성과 오독 방지를 우선한다",
      ],
      linesEn: [
        "Use a proven stable informational composition with a predictable eye path",
        "Prioritize communication stability and misread prevention over layout experimentation",
      ],
    },
    balanced: {
      labelKo: "균형형",
      labelEn: "Balanced",
      linesKo: [
        "기본 정보 구조는 유지하되 하나의 신선한 구성 포인트만 허용한다",
        "시선 흐름이 깨지지 않는 범위에서 비대칭, 크기 대비, 여백 변화를 제한적으로 사용한다",
      ],
      linesEn: [
        "Keep the core information structure while allowing one fresh composition idea",
        "Use asymmetry, scale contrast, or whitespace variation only where the eye path remains clear",
      ],
    },
    experimental: {
      labelKo: "실험형",
      labelEn: "Experimental",
      linesKo: [
        "비대칭, 겹침, 프레임 절단, 과감한 스케일 대비 같은 구성 실험을 허용한다",
        "단, 핵심 문구와 주요 정보의 판독성은 반드시 유지한다",
      ],
      linesEn: [
        "Allow experimental composition layouts such as asymmetry, overlap, frame cuts, and bold scale contrast",
        "Keep the main copy and key information readable at all times",
      ],
    },
  });

  const DEFAULT_COLOR_PRESETS = [
    {
      id: "preset_corporate_blue",
      name: "신뢰감 있는 기업 블루",
      primaryColor: "#0F3D8A",
      secondaryColor: "#D9E4F5",
      accentColor: "#FF7A00",
      backgroundMode: "solid",
      backgroundColor: "#F5F7FB",
      backgroundDetails: "은은한 그리드 패턴",
      isDefault: true,
    },
    {
      id: "preset_modern_dark",
      name: "프리미엄 테크 다크",
      primaryColor: "#101828",
      secondaryColor: "#344054",
      accentColor: "#7F56D9",
      backgroundMode: "image",
      backgroundColor: "#0B1220",
      backgroundDetails: "도시 야경 블러 배경",
      isDefault: true,
    },
    {
      id: "preset_vibrant_energy",
      name: "역동적인 스타트업 그린",
      primaryColor: "#1FA971",
      secondaryColor: "#ECFDF3",
      accentColor: "#FF6B2C",
      backgroundMode: "pattern",
      backgroundColor: "#FFFFFF",
      backgroundDetails: "기하학 라인 패턴",
      isDefault: true,
    },
    {
      id: "preset_elegant_gold",
      name: "우아한 골드 & 화이트",
      primaryColor: "#996515",
      secondaryColor: "#F3E5AB",
      accentColor: "#333333",
      backgroundMode: "solid",
      backgroundColor: "#FFFFFF",
      backgroundDetails: "고급스러운 질감 배경",
      isDefault: true,
    },
    {
      id: "preset_soft_creative",
      name: "부드러운 크리에이티브 퍼플",
      primaryColor: "#6941C6",
      secondaryColor: "#F9F5FF",
      accentColor: "#FBBC05",
      backgroundMode: "mixed",
      backgroundColor: "#FFFFFF",
      backgroundDetails: "파스텔 톤 그라데이션",
      isDefault: true,
    },
    {
      id: "preset_high_contrast",
      name: "강렬한 고대비 레드",
      primaryColor: "#D92D20",
      secondaryColor: "#FEE4E2",
      accentColor: "#101828",
      backgroundMode: "solid",
      backgroundColor: "#FFFFFF",
      backgroundDetails: "대담한 타이포 그래픽 배경",
      isDefault: true,
    },
    {
      id: "preset_nature_eco",
      name: "친근한 자연 에코",
      primaryColor: "#027A48",
      secondaryColor: "#D1FADF",
      accentColor: "#F79009",
      backgroundMode: "solid",
      backgroundColor: "#F9FAFB",
      backgroundDetails: "자연적인 질감 패턴",
      isDefault: true,
    },
    {
      id: "preset_minimal_mono",
      name: "미니멀 모노",
      primaryColor: "#111111",
      secondaryColor: "#E5E5E5",
      accentColor: "#555555",
      backgroundMode: "solid",
      backgroundColor: "#FFFFFF",
      backgroundDetails: "극도로 절제된 여백 배경",
      isDefault: true,
    },
    {
      id: "preset_warm_sunset",
      name: "따뜻한 선셋",
      primaryColor: "#E65100",
      secondaryColor: "#FFF3E0",
      accentColor: "#FB8C00",
      backgroundMode: "mixed",
      backgroundColor: "#FFF8F0",
      backgroundDetails: "부드러운 오렌지 빛 그라데이션",
      isDefault: true,
    },
    {
      id: "preset_cyberpunk",
      name: "사이버펑크 네온",
      primaryColor: "#00F2FF",
      secondaryColor: "#FF00E5",
      accentColor: "#FFFF00",
      backgroundMode: "image",
      backgroundColor: "#050505",
      backgroundDetails: "화려한 네온 사인 광원 효과",
      isDefault: true,
    },
    {
      id: "preset_luxury_orange",
      name: "럭셔리 오렌지 (에르메스 테마)",
      primaryColor: "#F37021",
      secondaryColor: "#4A3C31",
      accentColor: "#D4AF37",
      backgroundMode: "solid",
      backgroundColor: "#F9F6F0",
      backgroundDetails: "고급스러운 크림 질감 배경",
      isDefault: true,
    },
    {
      id: "preset_luxury_mint",
      name: "럭셔리 민트 (티파니 테마)",
      primaryColor: "#0ABAB5",
      secondaryColor: "#8A8D8F",
      accentColor: "#1C2833",
      backgroundMode: "solid",
      backgroundColor: "#F4F7F6",
      backgroundDetails: "깨끗하고 매끄러운 쿨그레이 배경",
      isDefault: true,
    }
  ];

  const TYPE_FIELD_DEFS = {
    image: [
      {
        key: "posterKeyVisual",
        domId: "promotionPosterKeyVisual",
        kind: "instruction",
        tag: "textarea",
        rows: 4,
        label: "메인 비주얼 포인트",
        guide: "가장 크게 보일 이미지 소재나 상징 오브젝트를 적습니다.",
        placeholder: "예: 중앙 히어로 오브젝트, 인물 반신, 추상 유리 큐브, 대형 타이포",
        quickBtns: QUICK_BTNS.visualPoint,
      },
      {
        key: "posterInfoLayout",
        domId: "promotionPosterInfoLayout",
        kind: "instruction",
        tag: "textarea",
        rows: 4,
        label: "정보 배치 방식",
        guide: "헤드라인, 정보 블록, CTA가 어떤 흐름으로 배치되는지 적습니다.",
        placeholder: "예: 상단 헤드라인 고정, 하단 정보 카드 1개, 좌측 텍스트 강조",
        quickBtns: QUICK_BTNS.infoLayout,
      },
      {
        key: "snsVisualFocus",
        domId: "promotionSnsVisualFocus",
        kind: "instruction",
        tag: "textarea",
        rows: 3,
        label: "비주얼 중심 포인트",
        guide: "화면에서 가장 먼저 시선이 가야 하는 축을 적습니다.",
        placeholder: "예: 인물 반신과 큰 헤드라인 중심, CTA보다 제목이 먼저 보이게",
        quickBtns: QUICK_BTNS.snsVisualFocus,
      },
      {
        key: "snsPlacementNotes",
        domId: "promotionSnsPlacementNotes",
        kind: "instruction",
        tag: "textarea",
        rows: 5,
        label: "배치 메모",
        guide: "안전영역, CTA 위치, 텍스트 블록 수 같은 배치 메모를 적습니다.",
        placeholder: "예: 상단 25% 훅 카피, 하단 CTA 영역 분리, 좌측 정렬축 유지",
        quickBtns: QUICK_BTNS.snsPlacement,
        wide: true,
      },
    ],
    poster: [
      {
        key: "posterKeyVisual",
        domId: "promotionPosterKeyVisual",
        kind: "instruction",
        tag: "textarea",
        rows: 4,
        label: "메인 비주얼 포인트",
        guide: "가장 크게 보여줄 이미지 소재나 상징 오브젝트를 적습니다.",
        placeholder: "예: 중앙 히어로 제품 컷, 금속 질감 위 대형 타이포",
        quickBtns: QUICK_BTNS.visualPoint,
      },
      {
        key: "posterInfoLayout",
        domId: "promotionPosterInfoLayout",
        kind: "instruction",
        tag: "textarea",
        rows: 4,
        label: "정보 배치 방식",
        guide: "일정, 장소, 가격 같은 정보를 어느 위치에 묶을지 적습니다.",
        placeholder: "예: 우측 하단 정보 박스, 상단 헤드라인 고정",
        quickBtns: QUICK_BTNS.infoLayout,
      },
    ],
    cardnews: [
      {
        key: "cardnewsFlow",
        domId: "promotionCardFlow",
        kind: "instruction",
        tag: "textarea",
        rows: 5,
        label: "카드 흐름",
        guide: "첫 장부터 마지막 장까지 어떤 순서로 메시지를 전개할지 적습니다.",
        placeholder: "예: 문제 인식 → 핵심 데이터 → 해결안 → 참가 혜택 → CTA",
        quickBtns: QUICK_BTNS.cardnewsFlow,
        wide: true,
      },
      {
        key: "cardnewsCardCount",
        domId: "promotionCardCount",
        kind: "constraint",
        tag: "select",
        label: "카드 수",
        guide: "시리즈 전체 컷 수를 정합니다.",
        options: [
          { value: "3", label: "3장" },
          { value: "4", label: "4장" },
          { value: "5", label: "5장" },
          { value: "6", label: "6장" },
          { value: "7", label: "7장" },
        ],
      },
      {
        key: "cardnewsCoverHook",
        domId: "promotionCardCoverHook",
        kind: "visible",
        tag: "input",
        label: "커버 카드 훅",
        guide: "첫 카드에 크게 보여줄 도입 문장입니다.",
        placeholder: "예: 3분 안에 이해하는 공급망 리스크 핵심",
      },
      {
        key: "cardnewsEndingCta",
        domId: "promotionCardEndingCta",
        kind: "visible",
        tag: "input",
        label: "마지막 카드 CTA",
        guide: "마지막 카드에서 행동을 유도할 문구입니다.",
        placeholder: "예: 저장하고 팀에 공유하세요",
      },
    ],
    sns: [
      {
        key: "snsVisualFocus",
        domId: "promotionSnsVisualFocus",
        kind: "instruction",
        tag: "textarea",
        rows: 3,
        label: "SNS 비주얼 중심 포인트",
        guide: "화면에서 가장 먼저 시선을 잡아야 하는 피사체나 강조 축을 적습니다.",
        placeholder: "예: CTA 버튼보다 먼저 보이는 인물 상반신과 큰 헤드라인",
        quickBtns: QUICK_BTNS.snsVisualFocus,
      },
      {
        key: "snsPlacementNotes",
        domId: "promotionSnsPlacementNotes",
        kind: "instruction",
        tag: "textarea",
        rows: 5,
        label: "배치 메모",
        guide: "스토리 안전영역, CTA 버튼 위치 같은 연출 지시입니다.",
        placeholder: "예: 상단 25% 훅 카피, 하단 20% CTA, 스티커 영역과 겹치지 않게",
        quickBtns: QUICK_BTNS.snsPlacement,
        wide: true,
      },
    ],
  };

  const CONTENT_TYPE_TEMPLATES = {
    campaign: {
      name: "캠페인",
      goal: "캠페인 동참 및 대중 인식 확산",
      audience: "일반 대중, 잠재 참여자",
      tone: "임팩트 있는, 대담한, 세련된, 브랜드 광고 같은",
      visualStyle: "대담한 타이포그래픽, 하이엔드 제품광고형, 캠페인 광고형, 강렬한 대비",
      qualityNotes: "광고 이미지급 디테일, 텍스트와 배경 대비 선명, 타이포 가장자리 또렷하게",
      mandatoryElements: "캠페인 슬로건, 로고, 참여 태그",
      forbiddenElements: "이모지 사용 금지, 장문 문단, 정보 과밀 배치",
      posterKeyVisual: "대형 헤드라인과 단일 오브젝트, 추상적 그래픽",
      posterInfoLayout: "여백 강조, 상단 헤드라인 고정",
      cardnewsFlow: "문제 제시(공감) → 캠페인 핵심 가치 → 대안/비전 → 참여 안내(CTA)",
      snsVisualFocus: "헤드라인과 핵심 문구 중심",
    },
    "result-promo": {
      name: "성과홍보",
      goal: "주요 성과 발표 및 신뢰도 확보",
      audience: "파트너사, 일반 시민, 주요 이해관계자",
      tone: "신뢰감 있는, 전문적인, 차분한, 명확한",
      visualStyle: "데이터 중심 레이아웃, 인포그래픽형, 미니멀 그리드형",
      qualityNotes: "텍스트와 배경 대비 선명, 노이즈 없는 깨끗한 표면, 브랜드 색상 정확도 유지",
      mandatoryElements: "성과 타이틀, 주요 수치 데이터, 로고, 출처",
      forbiddenElements: "과한 네온 효과, 흐릿한 배경 이미지, 불명확한 수치 표기",
      posterKeyVisual: "데이터 시각화, 기하학적 패턴",
      posterInfoLayout: "그리드 분할, 좌측 정렬축 통일",
      cardnewsFlow: "성과 요약 → 핵심 지표 3개 → 향후 비전 → 문의/피드백",
      snsVisualFocus: "정보카드 중심 (수치 및 인포그래픽)",
    },
    "event-info": {
      name: "행사안내 (참여요청)",
      goal: "행사 개최 안내 및 참가 신청 유도",
      audience: "신청 대상자, 유관 기관 실무자, 참여 희망자",
      tone: "역동적인, 세련된, 모던한, 친근한",
      visualStyle: "매거진 편집형, 실사 위주, 에디토리얼 광고형",
      qualityNotes: "행사 핵심 정보(일시/장소) 시각적 위계 강조, 모바일 썸네일 가독성 우선, CTA 버튼 한눈에 읽히게",
      mandatoryElements: "행사명, 일시, 장소, 신청 방법(QR/링크), 주최/주관 로고",
      forbiddenElements: "장황한 본문, 흐릿한 인물 사진, 가독성 낮은 폰트",
      posterKeyVisual: "인물 클로즈업, 대형 헤드라인과 단일 오브젝트",
      posterInfoLayout: "상단 헤드라인 고정, 하단 정보 박스 일체형",
      cardnewsFlow: "행사 취지 → 프로그램 핵심 → 참가 혜택 → 신청 안내(CTA)",
      snsVisualFocus: "헤드라인과 CTA 이중 강조",
    },
    "survey-request": {
      name: "설문조사 (참여요청)",
      goal: "설문 참여율 향상 및 의견 수집",
      audience: "서비스 이용자, 설문 조사 대상 고객층",
      tone: "친근한, 따뜻한, 심플한, 차분한",
      visualStyle: "파스텔 톤, 미니멀 그리드형, 라운드 형태의 요소",
      qualityNotes: "모바일 썸네일 가독성 우선, 텍스트와 배경 대비 선명, CTA 버튼 한눈에 읽히게",
      mandatoryElements: "설문 주제, 소요 시간, 경품 혜택, 참여 링크(QR)",
      forbiddenElements: "딱딱한 관공서 느낌, 정보 과밀 배치, 장문 문단",
      posterKeyVisual: "친근한 상징 아이콘, 심플한 그래픽",
      posterInfoLayout: "중앙 집중형, 정보 카드 1개로 묶기",
      cardnewsFlow: "참여 유도 훅 → 설문 목적 → 경품 혜택 → 참여 방법(CTA)",
      snsVisualFocus: "CTA 버튼 중심 (선물 쿠폰 등)",
    },
    "training-info": {
      name: "교육안내 (참여요청)",
      goal: "교육생 모집 및 신청 등록 유도",
      audience: "취업 준비생, 역량 강화 희망 실무자",
      tone: "스마트한, 전문적인, 신뢰감 있는, 성장을 돕는",
      visualStyle: "인포그래픽형, 미니멀 그리드형, 정돈된 에디토리얼 레이아웃",
      qualityNotes: "커리큘럼 및 혜택 가독성 최우선, 모집 마감일 임팩트 강조, 타이포 가장자리 또렷하게",
      mandatoryElements: "교육 과정명, 교육 기간, 신청 자격, 접수 마감일, 교육 혜택(수강료 등)",
      forbiddenElements: "복잡한 도표, 두꺼운 텍스트 외곽선, 어두운 무드",
      posterKeyVisual: "성장/배움을 상징하는 오브젝트, 단일 기하학 오브젝트",
      posterInfoLayout: "좌측 텍스트 강조, 우측 비주얼 배치, 상하단 레이아웃 분리",
      cardnewsFlow: "실무 고민 제기 → 교육 해결책 → 상세 혜택/일정 → 지원 양식(CTA)",
      snsVisualFocus: "인물 반신과 큰 제목 중심",
    },
    "biz-promo": {
      name: "사업홍보 (참여요청)",
      goal: "지원사업 모집 접수 및 파트너 발굴",
      audience: "기업 실무자, 예비 창업자, 스타트업 임직원",
      tone: "전문적인, 신뢰감 있는, 세련된, 임팩트 있는",
      visualStyle: "3D 그래픽, 글래스모피즘, 브랜드 포스터형",
      qualityNotes: "광고 이미지급 디테일, 브랜드 색상 정확도 유지, CTA 버튼 한눈에 읽히게",
      mandatoryElements: "사업명, 지원 내용, 접수 기간, 신청 자격 및 방법, 주관 기관 로고",
      forbiddenElements: "촌스러운 원색 배색, 저해상도 스톡 이미지, 정보 과밀 배치",
      posterKeyVisual: "기하학적 3D 오브젝트, 추상적 그래픽",
      posterInfoLayout: "Z자 흐름, 정보 카드 1개로 묶기",
      cardnewsFlow: "사업 추진 목적 → 핵심 지원 혜택 → 신청 자격 및 일정 → 온라인 접수(CTA)",
      snsVisualFocus: "헤드라인과 CTA 이중 강조",
    },
  };

  const CONTENT_TYPE_TEMPLATES_EN = {
    campaign: {
      name: "Campaign",
      goal: "Drive campaign participation and raise public awareness",
      audience: "general public, potential participants",
      tone: "impactful, bold, refined, brand advertisement style",
      visualStyle: "bold typography, high-end product advertisement layout, campaign advertisement layout, high-contrast palette",
      qualityNotes: "advertising-grade detail, strong text-to-background contrast, crisp typography edges",
      mandatoryElements: "campaign slogan, logo, participation hashtags",
      forbiddenElements: "emojis, long paragraphs, cluttered layout",
      posterKeyVisual: "large headline with a single hero object, abstract graphics",
      posterInfoLayout: "whitespace-focused, headline locked at top",
      cardnewsFlow: "problem empathy → core campaign values → vision/alternative → participation CTA",
      snsVisualFocus: "headline and core message centered",
    },
    "result-promo": {
      name: "Result Promotion",
      goal: "Announce key performance outcomes and establish trust",
      audience: "partners, citizens, key stakeholders",
      tone: "trustworthy, professional, calm, clear",
      visualStyle: "data-led layout, infographic style, minimal grid layout",
      qualityNotes: "strong text-to-background contrast, clean noise-free surfaces, brand color accuracy",
      mandatoryElements: "performance title, key numeric data, logo, data source",
      forbiddenElements: "excessive neon effects, blurry backgrounds, unclear numbers",
      posterKeyVisual: "data visualization, geometric pattern",
      posterInfoLayout: "grid split, unified left alignment",
      cardnewsFlow: "result summary → 3 key metrics → future vision → contact/feedback",
      snsVisualFocus: "information card focus (numbers and infographics)",
    },
    "event-info": {
      name: "Event Announcement",
      goal: "Announce event schedule and drive registration",
      audience: "target applicants, partner agency practitioners, prospective attendees",
      tone: "dynamic, refined, modern, friendly",
      visualStyle: "editorial magazine layout, photo-real direction, editorial advertising style",
      qualityNotes: "visual hierarchy for event details (date/location), mobile thumbnail legibility, prominent CTA button",
      mandatoryElements: "event title, date and time, location, application method (QR/link), organizer logo",
      forbiddenElements: "wordy body copy, blurry portrait photos, low-readability font choice",
      posterKeyVisual: "portrait close-up, large headline with a single hero object",
      posterInfoLayout: "headline locked at top, integrated bottom information box",
      cardnewsFlow: "event purpose → key program highlights → participation benefits → registration CTA",
      snsVisualFocus: "dual emphasis on headline and CTA",
    },
    "survey-request": {
      name: "Survey Request",
      goal: "Drive survey response rates and collect feedback",
      audience: "service users, survey target audience segments",
      tone: "friendly, warm, simple, calm",
      visualStyle: "pastel tone, minimal grid layout, rounded elements",
      qualityNotes: "mobile thumbnail legibility, strong text-to-background contrast, prominent CTA button",
      mandatoryElements: "survey topic, estimated duration, reward details, participation link (QR)",
      forbiddenElements: "rigid bureaucratic look, cluttered layout, long paragraphs",
      posterKeyVisual: "friendly symbolic icon, simple graphic",
      posterInfoLayout: "centered layout, single information card group",
      cardnewsFlow: "hook copy → survey purpose → reward details → participation method CTA",
      snsVisualFocus: "CTA button focus (gift coupon etc.)",
    },
    "training-info": {
      name: "Training Recruitment",
      goal: "Recruit trainees and drive course applications",
      audience: "job seekers, professionals seeking upskilling",
      tone: "smart, professional, trustworthy, growth-oriented",
      visualStyle: "infographic style, minimal grid layout, organized editorial layout",
      qualityNotes: "curriculum and benefit readability, recruitment deadline emphasis, crisp typography edges",
      mandatoryElements: "course title, training period, eligibility, application deadline, program benefits (tuition details)",
      forbiddenElements: "complex tables, thick text outlines, dark background colors",
      posterKeyVisual: "growth/learning symbolic object, single geometric object",
      posterInfoLayout: "text-first on left and visual on right, top-bottom layout split",
      cardnewsFlow: "practical dilemma → training solution → key benefits/dates → application form CTA",
      snsVisualFocus: "subject portrait and bold title focus",
    },
    "biz-promo": {
      name: "Business Promotion",
      goal: "Drive public project applications and recruit business partners",
      audience: "business practitioners, aspiring founders, startup employees",
      tone: "professional, trustworthy, refined, impactful",
      visualStyle: "3D graphics, glassmorphism, brand poster layout",
      qualityNotes: "advertising-grade detail, brand color accuracy, prominent CTA button",
      mandatoryElements: "program title, support details, application period, eligibility and method, host agency logo",
      forbiddenElements: "cheap primary colors, low-resolution stock images, cluttered layout",
      posterKeyVisual: "geometric 3D object, abstract graphics",
      posterInfoLayout: "Z-flow layout, single information card group",
      cardnewsFlow: "project goal → key program benefits → eligibility and dates → online application CTA",
      snsVisualFocus: "dual emphasis on headline and CTA",
    },
  };

  const CONTENT_TYPE_SAMPLE_PROFILES = {
    none: {
      paletteId: "preset_modern_dark",
      state: {
        contentType: "none",
        sizeMode: "ratio",
        ratio: "4:5",
        orientation: "vertical",
        directSizeUnit: "px",
        directSizeW: "",
        directSizeH: "",
        headline: "WORK FASTER, THINK DEEPER",
        subheadline: "팀의 기획, 문서, 리서치 흐름을 하나로 묶는 AI 협업 워크스페이스",
        bodyCopy: "- 실무 문서 초안과 피드백 정리 자동화\n- 조사, 요약, 정리 작업을 한 화면에서 연결\n- 팀 단위 도입 데모와 맞춤형 파일럿 지원",
        cta: "도입 데모 요청하기",
        posterOffer: "상담 신청 시 14일 파일럿 체험과 운영 가이드 제공",
        snsHook: "팀 생산성, 이번 분기에 바꿔보세요",
        snsHashtags: "#AI협업 #업무자동화 #생산성도구",
      },
      quickFields: {
        promotionGoal: ["브랜드 인지도 제고"],
        promotionAudience: ["브랜드 관심 고객"],
        promotionTone: ["프리미엄", "세련된", "브랜드 광고 같은"],
        promotionVisualStyle: ["하이엔드 제품광고형", "에디토리얼 광고형", "대담한 타이포그래피"],
        promotionQualityNotes: ["광고 이미지급 디테일", "텍스트와 배경 대비 선명", "타이포 가장자리 또렷하게"],
        promotionBackgroundDetails: ["딥 네이비 그라데이션 배경", "추상 광원 오버레이", "텍스트 영역만 어둡게 오버레이"],
        promotionMandatoryElements: ["브랜드명", "CTA 버튼", "로고"],
        promotionForbiddenElements: ["이모지 사용 금지", "장문 문단", "저해상도 스톡 느낌"],
        promotionPosterKeyVisual: ["중앙 히어로 제품", "대형 헤드라인과 단일 오브젝트"],
        promotionPosterInfoLayout: ["상단 헤드라인 고정", "정보 카드 1개로 묶기"],
        promotionSnsVisualFocus: ["타이포 중심"],
        promotionSnsPlacementNotes: ["상단 25% 훅 카피", "하단 CTA 버튼 영역 분리", "좌측 정렬축 유지"],
      },
    },
    campaign: {
      paletteId: "preset_vibrant_energy",
      state: {
        contentType: "campaign",
        sizeMode: "ratio",
        ratio: "4:5",
        orientation: "vertical",
        directSizeUnit: "px",
        directSizeW: "",
        directSizeH: "",
        headline: "지구를 구하는 작은 약속: ZERO PLASTIC 2026",
        subheadline: "일상의 플라스틱 소비를 50% 줄이는 탄소 중립 참여 캠페인",
        bodyCopy: "- 하루 한 번 텀블러 사용 인증\n- 에코백 사용 및 다회용기 장보기 동참\n- 누적 참여자 1만 명 달성 시 친환경 숲 조성\n- 캠페인 웹사이트에서 실시간 서약 진행",
        cta: "탄소중립 서약 참여하기",
        posterOffer: "서약 참여 선착순 1,000명에게 친환경 스타터 키트 무료 증정",
        snsHook: "플라스틱 없는 하루, 당신의 작은 실천으로 시작됩니다",
        snsHashtags: "#제로플라스틱 #탄소중립 #에코캠페인",
      },
      quickFields: {
        promotionGoal: ["캠페인 동참 및 대중 인식 확산"],
        promotionAudience: ["일반 대중", "잠재 참여자"],
        promotionTone: ["임팩트 있는", "대담한", "세련된", "브랜드 광고 같은"],
        promotionVisualStyle: ["대담한 타이포그래픽", "하이엔드 제품광고형", "캠페인 광고형"],
        promotionQualityNotes: ["광고 이미지급 디테일", "텍스트와 배경 대비 선명", "타이포 가장자리 또렷하게"],
        promotionBackgroundDetails: ["고급스러운 질감 배경", "추상 광원 오버레이", "텍스트 영역만 어둡게 오버레이"],
        promotionMandatoryElements: ["캠페인 슬로건", "로고", "참여 태그"],
        promotionForbiddenElements: ["이모지 사용 금지", "장문 문단", "정보 과밀 배치"],
        promotionPosterKeyVisual: ["대형 헤드라인과 단일 오브젝트", "추상적 그래픽"],
        promotionPosterInfoLayout: ["여백 강조", "상단 헤드라인 고정"],
        promotionSnsVisualFocus: ["헤드라인과 핵심 문구 중심"],
        promotionSnsPlacementNotes: ["상단 25% 훅 카피", "하단 CTA 버튼 영역 분리", "텍스트 블록 2개 이하 유지"],
      },
    },
    "result-promo": {
      paletteId: "preset_corporate_blue",
      state: {
        contentType: "result-promo",
        sizeMode: "ratio",
        ratio: "4:5",
        orientation: "vertical",
        directSizeUnit: "px",
        directSizeW: "",
        directSizeH: "",
        headline: "2025 스마트 청년 창업 지원 사업 성과 보고",
        subheadline: "도전하는 청년 기업들과 함께 만든 혁신적 성장 지표를 공유합니다",
        bodyCopy: "- 청년 스타트업 누적 150개사 육성 완료\n- 신규 고용 창출 450명 및 후속 투자 유치 210억 원 달성\n- 글로벌 시장 진출 지원 및 수출 계약 50억 원 계약 완료\n- 2026년도 예산 대폭 확대로 청년 기업 동반성장 강화",
        cta: "상세 성과 인포그래픽 보기",
        posterOffer: "보고서 PDF 다운로드 시 우수 스타트업 디렉토리 북 동시 제공",
        snsHook: "청년 스타트업과 함께 만든 기적 같은 혁신 성과를 공개합니다",
        snsHashtags: "#스타트업지원 #사업성과 #청년창업",
      },
      quickFields: {
        promotionGoal: ["주요 성과 발표 및 신뢰도 확보"],
        promotionAudience: ["파트너사", "일반 시민", "주요 이해관계자"],
        promotionTone: ["신뢰감 있는", "전문적인", "차분한", "명확한"],
        promotionVisualStyle: ["데이터 중심 레이아웃", "인포그래픽형", "미니멀 그리드형"],
        promotionQualityNotes: ["텍스트와 배경 대비 선명", "노이즈 없는 깨끗한 표면", "브랜드 색상 정확도 유지"],
        promotionBackgroundDetails: ["은은한 그리드 패턴", "텍스트 영역만 어둡게 오버레이"],
        promotionMandatoryElements: ["성과 타이틀", "주요 수치 데이터", "로고", "출처"],
        promotionForbiddenElements: ["과한 네온 효과", "흐릿한 배경 이미지", "불명확한 수치 표기"],
        promotionPosterKeyVisual: ["데이터 시각화", "기하학적 패턴"],
        promotionPosterInfoLayout: ["그리드 분할", "좌측 정렬축 통일"],
        promotionSnsVisualFocus: ["정보카드 중심 (수치 및 인포그래픽)"],
        promotionSnsPlacementNotes: ["텍스트 블록 2개 이하 유지", "안전영역 침범 금지", "왼쪽 정렬축 유지"],
      },
    },
    "event-info": {
      paletteId: "preset_modern_dark",
      state: {
        contentType: "event-info",
        sizeMode: "ratio",
        ratio: "4:5",
        orientation: "vertical",
        directSizeUnit: "px",
        directSizeW: "",
        directSizeH: "",
        headline: "NEXT HORIZON: 2026 글로벌 기술 포럼",
        subheadline: "디지털 전환과 AI 생태계의 내일을 조망하는 국내 최대 오프라인 세미나",
        bodyCopy: "- 일시: 2026. 09. 15 (화) 10:00 ~ 17:00\n- 장소: 서울 크리에이티브 파크 그랜드볼룸\n- 연사: AI 및 로보틱스 산업 분야 최고 권위자 5인 기조강연\n- 비용: 무료 (사전 등록 마감: 09. 08)",
        cta: "선착순 사전 등록 신청",
        posterOffer: "사전 등록자 전원 강연 핵심 요약 자료집 및 네트워킹 초청장 발송",
        snsHook: "디지털 혁신의 미래, 현장에서 직접 경험하세요",
        snsHashtags: "#테크포럼 #인공지능 #사전등록",
      },
      quickFields: {
        promotionGoal: ["행사 개최 안내 및 참가 신청 유도"],
        promotionAudience: ["신청 대상자", "유관 기관 실무자", "참여 희망자"],
        promotionTone: ["역동적인", "세련된", "모던한", "친근한"],
        promotionVisualStyle: ["매거진 편집형", "실사 위주", "에디토리얼 광고형"],
        promotionQualityNotes: ["행사 핵심 정보(일시/장소) 시각적 위계 강조", "모바일 썸네일 가독성 우선", "CTA 버튼 한눈에 읽히게"],
        promotionBackgroundDetails: ["딥 네이비 그라데이션 배경", "추상 광원 오버레이", "텍스트 영역만 어둡게 오버레이"],
        promotionMandatoryElements: ["행사명", "일시", "장소", "신청 방법(QR/링크)", "주최/주관 로고"],
        promotionForbiddenElements: ["장황한 본문", "흐릿한 인물 사진", "가독성 낮은 폰트"],
        promotionPosterKeyVisual: ["인물 클로즈업", "대형 헤드라인과 단일 오브젝트"],
        promotionPosterInfoLayout: ["상단 헤드라인 고정", "하단 정보 박스 일체형"],
        promotionSnsVisualFocus: ["헤드라인과 CTA 이중 강조"],
        promotionSnsPlacementNotes: ["상단 25% 훅 카피", "하단 CTA 버튼 영역 분리", "모바일 썸네일 축소 시 가독성 유지"],
      },
    },
    "survey-request": {
      paletteId: "preset_soft_creative",
      state: {
        contentType: "survey-request",
        sizeMode: "ratio",
        ratio: "4:5",
        orientation: "vertical",
        directSizeUnit: "px",
        directSizeW: "",
        directSizeH: "",
        headline: "2026 시민 참여형 정책 혁신 설문조사",
        subheadline: "더 편리한 공공 서비스를 만들기 위해 여러분의 소중한 의견을 들려주세요",
        bodyCopy: "- 참여 기간: 2026. 06. 10 ~ 06. 30\n- 참여 대상: 공공 서비스를 이용하는 누구나\n- 설문 시간: 약 3분 (총 10개 문항)\n- 모바일 링크 및 QR코드로 참여",
        cta: "3분 설문 참여하기",
        posterOffer: "참여 완료자 전원 커피 쿠폰 지급 및 추첨 100명 3만원 상당 경품 제공",
        snsHook: "여러분의 한마디가 내일의 정책을 바꿉니다",
        snsHashtags: "#시민소통 #정책설문 #의견제출",
      },
      quickFields: {
        promotionGoal: ["설문 참여율 향상 및 의견 수집"],
        promotionAudience: ["서비스 이용자", "설문 조사 대상 고객층"],
        promotionTone: ["친근한", "따뜻한", "심플한", "차분한"],
        promotionVisualStyle: ["파스텔 톤", "미니멀 그리드형", "라운드 형태의 요소"],
        promotionQualityNotes: ["모바일 썸네일 가독성 우선", "텍스트와 배경 대비 선명", "CTA 버튼 한눈에 읽히게"],
        promotionBackgroundDetails: ["부드러운 질감 배경", "텍스트 영역만 어둡게 오버레이"],
        promotionMandatoryElements: ["설문 주제", "소요 시간", "경품 혜택", "참여 링크(QR)"],
        promotionForbiddenElements: ["딱딱한 관공서 느낌", "정보 과밀 배치", "장문 문단"],
        promotionPosterKeyVisual: ["친근한 상징 아이콘", "심플한 그래픽"],
        promotionPosterInfoLayout: ["중앙 집중형", "정보 카드 1개로 묶기"],
        promotionSnsVisualFocus: ["CTA 버튼 중심 (선물 쿠폰 등)"],
        promotionSnsPlacementNotes: ["텍스트 블록 2개 이하 유지", "안전영역 침범 금지"],
      },
    },
    "training-info": {
      paletteId: "preset_corporate_blue",
      state: {
        contentType: "training-info",
        sizeMode: "ratio",
        ratio: "4:5",
        orientation: "vertical",
        directSizeUnit: "px",
        directSizeW: "",
        directSizeH: "",
        headline: "2026 미래 인재 스킬업: 데이터 분석 전문가 과정",
        subheadline: "실제 비즈니스 프로젝트로 배우는 전액 국비 지원 부트캠프 교육생 모집",
        bodyCopy: "- 교육 일정: 2026. 10. 12 ~ 12. 18 (10주)\n- 지원 자격: 미취업 청년 및 데이터 실무 스킬업 희망자\n- 혜택: 전액 무료 교육 + 매월 학습 장려금 30만원 지원\n- 접수 기한: 2026. 09. 25 까지",
        cta: "부트캠프 즉시 지원하기",
        posterOffer: "지원자 전원 기초 SQL 온라인 VOD 강의 및 커리큘럼 로드맵 무료 배포",
        snsHook: "비전공자도 가능합니다. 데이터 분석 실무형 인재로 도약하세요",
        snsHashtags: "#국비부트캠프 #데이터전문가 #무료교육",
      },
      quickFields: {
        promotionGoal: ["교육생 모집 및 신청 등록 유도"],
        promotionAudience: ["취업 준비생", "역량 강화 희망 실무자"],
        promotionTone: ["스마트한", "전문적인", "신뢰감 있는", "성장을 돕는"],
        promotionVisualStyle: ["인포그래픽형", "미니멀 그리드형", "정돈된 에디토리얼 레이아웃"],
        qualityNotes: ["커리큘럼 및 혜택 가독성 최우선", "모집 마감일 임팩트 강조", "타이포 가장자리 또렷하게"],
        promotionBackgroundDetails: ["은은한 그리드 패턴", "텍스트 영역만 어둡게 오버레이"],
        promotionMandatoryElements: ["교육 과정명", "교육 기간", "신청 자격", "접수 마감일", "교육 혜택(수강료 등)"],
        promotionForbiddenElements: ["복잡한 도표", "두꺼운 텍스트 외곽선", "어두운 무드"],
        promotionPosterKeyVisual: ["성장/배움을 상징하는 오브젝트", "단일 기하학 오브젝트"],
        promotionPosterInfoLayout: ["좌측 텍스트 강조, 우측 비주얼 배치", "상하단 레이아웃 분리"],
        promotionSnsVisualFocus: ["인물 반신과 큰 제목 중심"],
        promotionSnsPlacementNotes: ["상단 25% 훅 카피", "하단 CTA 버튼 영역 분리", "왼쪽 정렬축 유지"],
      },
    },
    "biz-promo": {
      paletteId: "preset_vibrant_energy",
      state: {
        contentType: "biz-promo",
        sizeMode: "ratio",
        ratio: "4:5",
        orientation: "vertical",
        directSizeUnit: "px",
        directSizeW: "",
        directSizeH: "",
        headline: "2026 유망 벤처기업 도약 패키지 지원사업",
        subheadline: "기술 상용화와 판로 개척을 위한 스케일업 자금 및 비즈니스 멘토링 연계",
        bodyCopy: "- 지원 대상: 창업 3년 이상 7년 미만의 혁신 성장 벤처기업\n- 지원 금액: 기업당 최대 1억 원 (사업화 자금)\n- 접수 기간: 2026. 08. 01 ~ 08. 25 18:00\n- 접수 방법: 정부 창업지원 포털 온라인 신청",
        cta: "사업 공고 및 제안서 접수",
        posterOffer: "온라인 설명회 영상 및 FAQ 가이드북 실시간 무료 다운로드 제공",
        snsHook: "혁신 벤처의 스케일업 파트너, 최대 1억원의 사업화 지원을 신청하세요",
        snsHashtags: "#지원사업 #스케일업 #창업지원",
      },
      quickFields: {
        promotionGoal: ["지원사업 모집 접수 및 파트너 발굴"],
        promotionAudience: ["기업 실무자", "예비 창업자", "스타트업 임직원"],
        promotionTone: ["전문적인", "신뢰감 있는", "세련된", "임팩트 있는"],
        promotionVisualStyle: ["3D 그래픽", "글래스모피즘", "브랜드 포스터형"],
        promotionQualityNotes: ["광고 이미지급 디테일", "브랜드 색상 정확도 유지", "CTA 버튼 한눈에 읽히게"],
        promotionBackgroundDetails: ["기하학적 3D 오브젝트", "추상적 그래픽"],
        promotionMandatoryElements: ["사업명", "지원 내용", "접수 기간", "신청 자격 및 방법", "주관 기관 로고"],
        promotionForbiddenElements: ["촌스러운 원색 배색", "저해상도 스톡 이미지", "정보 과밀 배치"],
        promotionPosterKeyVisual: ["기하학적 3D 오브젝트", "추상적 그래픽"],
        promotionPosterInfoLayout: ["Z자 흐름", "정보 카드 1개로 묶기"],
        promotionSnsVisualFocus: ["헤드라인과 CTA 이중 강조"],
        promotionSnsPlacementNotes: ["상단 25% 훅 카피", "하단 CTA 버튼 영역 분리", "헤드라인과 배경 대비 강하게"],
      },
    },
  };

  const UNIFIED_RANDOMIZABLE_PRESET_FIELDS = [
    "promotionGoal",
    "promotionAudience",
    "promotionTone",
    "promotionVisualStyle",
    "promotionQualityNotes",
    "promotionBackgroundDetails",
    "promotionForbiddenElements",
    "promotionPosterKeyVisual",
    "promotionPosterInfoLayout",
    "promotionSnsVisualFocus",
    "promotionSnsPlacementNotes",
  ];

  const COLOR_FIELD_IDS = [
    { stateKey: "primaryColor", inputId: "promotionPrimaryColor", pickerId: "promotionPrimaryColorPicker", swatchId: "promotionPrimaryColorSwatch" },
    { stateKey: "secondaryColor", inputId: "promotionSecondaryColor", pickerId: "promotionSecondaryColorPicker", swatchId: "promotionSecondaryColorSwatch" },
    { stateKey: "accentColor", inputId: "promotionAccentColor", pickerId: "promotionAccentColorPicker", swatchId: "promotionAccentColorSwatch" },
    { stateKey: "backgroundColor", inputId: "promotionBackgroundColor", pickerId: "promotionBackgroundColorPicker", swatchId: "promotionBackgroundColorSwatch" },
  ];
  return {
    PROMOTION_SCHEMA_VERSION,
    PROMOTION_DRAFT_STORAGE_KEY,
    PROMOTION_COLOR_PRESETS_KEY,
    PROMOTION_SIZE_PRESETS_KEY,
    ASSET_TYPES,
    CONTENT_TYPE_VALUES,
    COLOR_STRATEGY_VALUES,
    ASSET_DEFAULTS,
    DEFAULT_STATE,
    ASSET_LABELS,
    ASSET_LABELS_EN,
    ASSET_PROMPT_TARGET_EN,
    KIND_META,
    STATIC_FIELD_KINDS,
    FIELD_LABELS,
    FIELD_LABELS_EN,
    QUICK_BTNS,
    DEFAULT_QUALITY_TAGS,
    COMMERCIAL_BASELINE_PROFILES,
    CREATIVITY_LEVEL_PROFILES,
    VARIATION_SEEDS,
    CONTENT_PROMOTION_STRATEGIES,
    CREATIVE_DIVERSITY_PROFILES,
    LAYOUT_COMPOSITION_PROFILES,
    ATTENTION_FLOW_VARIANTS,
    AI_LAYOUT_STRATEGY_OPTIONS,
    AI_VISUAL_METAPHOR_EXAMPLES,
    INFORMATION_ITEM_LAYOUT_VARIANTS,
    QR_PLACEMENT_VARIANTS,
    MANDATORY_ELEMENT_PLACEMENT_VARIANTS,
    AI_TOGGLE_FIELDS,
    FIELD_ENABLE_TOGGLE_FIELDS,
    STEP5_QUALITY_OPTIONS,
    STEP3_VISUAL_OPTION_GROUPS,
    STEP3_IDEA_PRESETS,
    ANTI_AI_PRESETS,
    DEFAULT_COLOR_PRESETS,
    TYPE_FIELD_DEFS,
    CONTENT_TYPE_TEMPLATES,
    CONTENT_TYPE_TEMPLATES_EN,
    CONTENT_TYPE_SAMPLE_PROFILES,
    UNIFIED_RANDOMIZABLE_PRESET_FIELDS,
    COLOR_FIELD_IDS,
  };
})();
